### ISSUE TITLE
SonarQube API reimport problem

### ISSUE THREAD

**Issue by Nafanyya** [DefectDojo/django-DefectDojo#10098]
Hi!

When import result scan master branch from SonarQube with API. Import is correct.
Then reimport result scan PR with "branch tag" first time, reimport correct:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/164300555/6e3790d7-11fd-4d7f-b390-4e927c5bfb26)
But if reimport second time this result scan PR with "branch tag", i have error: An exception error occurred during the report import:'NoneType' object is not iterable
![image](https://github.com/DefectDojo/django-DefectDojo/assets/164300555/d3fc53a8-8d33-443e-808e-2c0c3e8c1ef5)

**Environment information**
 - Operating System: [e.g. Ubuntu 22.04]
 - DefectDojo version 2.29.3

**Comment by kiblik** [comment]
Can you please check and provide logs from uwsgi container? To see a whole context.

**Comment by Nafanyya** [comment]
> Can you please check and provide logs from uwsgi container? To see a whole context.

Logs:

[14/May/2024 08:29:06] ERROR [dojo.tools.api_sonarqube.importer:204] Unable to find the project projectname due to 404 - {"errors":[{"msg":"Component \u0027projectname\u0027 on branch \u002713752\u0027 not found"}]}
Traceback (most recent call last):
  File "/app/dojo/tools/api_sonarqube/importer.py", line 109, in import_issues
    component = client.get_project(
                ^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/api_sonarqube/api_client.py", line 126, in get_project
    raise Exception(
Exception: Unable to find the project projectname due to 404 - {"errors":[{"msg":"Component \u0027projectname\u0027 on branch \u002713752\u0027 not found"}]}
[14/May/2024 08:29:06] ERROR [dojo.tools.api_sonarqube.importer:327] Unable to find the project projectname due to 404 - {"errors":[{"msg":"Component \u0027projectname\u0027 on branch \u002713752\u0027 not found"}]}
Traceback (most recent call last):
  File "/app/dojo/tools/api_sonarqube/importer.py", line 228, in import_hotspots
    component = client.get_project(
                ^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/api_sonarqube/api_client.py", line 126, in get_project
    raise Exception(
Exception: Unable to find the project projectname due to 404 - {"errors":[{"msg":"Component \u0027projectname\u0027 on branch \u002713752\u0027 not found"}]}
[14/May/2024 08:29:06] ERROR [dojo.test.views:872] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/dojo/test/views.py", line 863, in re_import_scan_results
    reimporter.reimport_scan(scan, scan_type, test, active=active, verified=verified,
  File "/app/dojo/importers/reimporter/reimporter.py", line 682, in reimport_scan
    ) = self.process_parsed_findings(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/decorators.py", line 48, in __wrapper__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 71, in process_parsed_findings
    for item in items:
TypeError: 'NoneType' object is not iterable


link from sonarqube: https://sonar.domain/dashboard?id=projectname&pullRequest=13753
in the branch tag field, I specified 13753, pullRequest=13753, &pullRequest=13753 and all the time i have a error 'NoneType' object is not iterable

**Comment by kiblik** [comment]
DD-SQ integration supports branches only right now. You can use the name of the branch on which PR is open.

**Comment by kiblik** [comment]
But it looks like a useful feature. Can you change the title and redefine it to a feature request? Somebody might have time and implement it for pullRequests as well.

**Comment by Nafanyya** [comment]
> DD-SQ integration supports branches only right now. You can use the name of the branch on which PR is open.

Name of branch like this? 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/164300555/260d7d9b-9c46-4b1f-bcd4-1e6d0e8bd1f7)

**Comment by kiblik** [comment]
Not 100% sure. I never used this functionality.

**Comment by Nafanyya** [comment]
> Not 100% sure. I never used this functionality.

I try reimport with name of branch and results was only error :(

**Comment by Nafanyya** [comment]
> But it looks like a useful feature. Can you change the title and redefine it to a feature request? Somebody might have time and implement it for pullRequests as well.

how can i changed to feature request?

**Comment by kiblik** [comment]
@mtesauro, can we ask you to change this issue from 🐛 to feature request, please?

**Comment by Nafanyya** [comment]
> @mtesauro, can we ask you to change this issue from 🐛 to feature request, please?

I talked to my lead and he says that it's not a feature request it's a bug

**Comment by valentijnscholten** [comment]
The `NoneType` was already fixed, but added another defense in the linked PR. 

For supporting import of PRs from SonarQube we'll need help from the community.
