### ISSUE TITLE
Logs level for defect Dojo

### ISSUE THREAD

**Issue by Aminoss46** [DefectDojo/django-DefectDojo#10278]
Hello everyone,

i need your help please to access all logs of defect dojo especially the uwsgi ( django ) container

I use a Docker compose installation and i added gitlab oidc to connect all my users but unfortunately i get an error : 

- " Authentication process canceled "

When i execute the same command manually i get an HTTP 200 OK, so i am guessing that could be an error with defect dojo in the request he's sending to gitlab to get the token, and unfortunately i can't access to all logs ( DEBUG ) to see what request he's sending exactly to compare it with the one i did manually

Anyone please have an idea how to change the log level via the docker compose ?

Thank you in advance

**Comment by mtesauro** [comment]
Setting `DD_LOG_LEVEL` as an environmental variable will change the log level

See https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L1525C18-L1525C30

Note: Do no change settings.dist.py but use a local_settings.py file - you can see an example of that at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/template-local_settings#L29

**Comment by Aminoss46** [comment]
Thank you for your response,

unfortunately i didn't get more info for my problem, do you have any idea please ?


Environment:
Request Method: GET
Request URL: http://my-gitlab-url.com/complete/gitlab/?code=41fc4464d801ad97ceebb65f9ea2944059dafb4e4ad73887c8f658507dc75441&state=Jz5OyXaiaeOJvDBBIgS6pbd5KNrBMX9R

Django Version: 4.1.13
Python Version: 3.11.4
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'django.contrib.admin',
 'django.contrib.humanize',
 'auditlog',
 'dojo',
 'watson',
 'tagging',
 'imagekit',
 'multiselectfield',
 'rest_framework',
 'rest_framework.authtoken',
 'dbbackup',
 'django_celery_results',
 'social_django',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'tagulous',
 'fontawesomefree',
 'django_filters')
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'dojo.middleware.APITrailingSlashMiddleware',
 'dojo.middleware.DojoSytemSettingsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'dojo.remote_user.RemoteUserMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware',
 'dojo.middleware.AdditionalHeaderMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'watson.middleware.SearchContextMiddleware',
 'auditlog.middleware.AuditlogMiddleware',
 'crum.CurrentRequestUserMiddleware',
 'dojo.request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/social_core/utils.py", line 253, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/social_core/backends/oauth.py", line 418, in auth_complete
    response = self.request_access_token(
  File "/usr/local/lib/python3.11/site-packages/social_core/backends/oauth.py", line 397, in request_access_token
    return self.get_json(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/social_core/backends/base.py", line 250, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/usr/local/lib/python3.11/site-packages/social_core/backends/base.py", line 246, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

During handling of the above exception (400 Client Error: Bad Request for url: https://devin-source-recette.rte-france.com/oauth/token), another exception occurred:
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/social_django/views.py", line 31, in complete
    return do_complete(
  File "/usr/local/lib/python3.11/site-packages/social_core/actions.py", line 49, in do_complete
    user = backend.complete(user=user, redirect_name=redirect_name, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/social_core/backends/base.py", line 39, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/social_core/utils.py", line 256, in wrapper
    raise AuthCanceled(args[0], response=err.response)

Exception Type: AuthCanceled at /complete/gitlab/
Exception Value: Authentication process canceled
