### ISSUE TITLE
Internal server error on re-import with auto groups

### ISSUE THREAD

**Issue by obormot** [DefectDojo/django-DefectDojo#10400]
**Bug description**
Getting a 500 Internal Server Error response when using DefectDojo's reimport API with group_by parameter. Narrowed it down to a missing required argument to a function call causing an exception in Python. Observed this error when running /reimport-scan over an existing test created earlier by /import-scan with the same group_by parameter. Looks like auto-groups were created upon the initial import, and then new findings were to be added to these groups by the re-import.

**Steps to reproduce**
`POST /api/v2/reimport-scan/` with  `group_by='component_name+component_version' ` as one of the parameters

**Expected behavior**
No 500 error.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04 LTS
 - DefectDojo version: 2.35.0 (release mode)

**Logs** 
```
[13/Jun/2024 23:37:07] ERROR [dojo.api_v2.exception_handler:43] add_findings_to_auto_group() missing 1 required positional argument: 'group_by'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 2801, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2590, in save
    self.process_scan(auto_create_manager, data, context)
  File "/app/dojo/api_v2/serializers.py", line 2542, in process_scan
    ).process_scan(
      ^^^^^^^^^^^^^
  File "/app/dojo/importers/default_reimporter.py", line 100, in process_scan
    ) = self.determine_process_method(self.parsed_findings, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/base_importer.py", line 263, in determine_process_method
    return self.sync_process_findings(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/base_importer.py", line 234, in sync_process_findings
    return self.process_findings(parsed_findings, sync=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/default_reimporter.py", line 245, in process_findings
    self.process_groups_for_all_findings(**kwargs)
  File "/app/dojo/importers/default_reimporter.py", line 688, in process_groups_for_all_findings
    finding_helper.add_findings_to_auto_group(
TypeError: add_findings_to_auto_group() missing 1 required positional argument: 'group_by'
[13/Jun/2024 23:37:12] ERROR [django.request:241] Internal Server Error: /api/v2/reimport-scan/
[pid: 33|app: -|req: -/-] 192.168.1.111 (-) {44 vars in 744 bytes} [Thu Jun 13 23:36:31 2024] POST /api/v2/reimport-scan/ => generated 59 bytes in 41274 msecs (HTTP/1.1 500) 8 headers in 253 bytes (1 switches on core 0)
```

**Comment by obormot** [comment]
I see this was already addressed in 2.35.1, closing.
