### ISSUE TITLE
dumpdata does not work - exception

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1052]
**Bug description**
Trying to run `dumpdata` results in an exception. It would be useful to have this to generate json files that could easily be leveraged with `loaddata` for testing things quickly.

**Steps to reproduce**

Done on the `dev` branch. 

1.docker exec into the uwsgi container (or just run the command directly through docker exec)
2. run `python manage.py dumpdata auth.user`
3. See the stracktrace, as shown below.

```
I have no name!@f62fe3af47fc:/app$ python manage.py dumpdata
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/dojo/urls.py", line 6, in <module>
    from tastypie.api import Api
  File "/usr/local/lib/python2.7/site-packages/tastypie/api.py", line 11, in <module>
    from tastypie.resources import Resource
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 22, in <module>
    from django.contrib.gis.db.models.fields import GeometryField
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
    from django.contrib.gis.db.models.aggregates import *  # NOQA
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/models/aggregates.py", line 1, in <module>
    from django.contrib.gis.db.models.fields import ExtentField
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/forms/fields.py", line 4, in <module>
    from django.contrib.gis.geos import GEOSException, GEOSGeometry
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
    from .collections import (  # NOQA
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/geos/collections.py", line 11, in <module>
    from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/geos/geometry.py", line 11, in <module>
    from django.contrib.gis import gdal
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 37, in <module>
    lib_path = find_library(lib_name)
  File "/usr/local/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/local/lib/python2.7/ctypes/util.py", line 264, in _findSoname_ldconfig
    env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'add_command'
```

**Expected behavior**
The dumpdata commands outputs the expected results.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by madchap** [comment]
So, it turns out that no command except `python manage.py shell` worked.

Since I was running `dev` with my unprocessed [PR](https://github.com/DefectDojo/django-DefectDojo/pull/1051) that adds a check for `DD_DEBUG` in `manage.py` in order to launch `pvstd.Server`, I tried the same commands on the shell with `export DD_DEBUG=off` and then it worked.

I don't really understand why this would do this, so if anyone could shed some light? (and remove the `bug` label).

Thank you.

**Comment by madchap** [comment]
OK, so it turns out it is simply an uncaught exception when calling `ptvsd.enable_attach` again, which is not a `socket_error`. Simply `pass`ing over, and everything looks fine.

**Comment by devEricA** [comment]
@madchap Are you still having trouble with dumpdata? I just tested the command in my docker container and it ran through just fine.

**Comment by madchap** [comment]
This is good, we can close. Thanks for the ping.
