### ISSUE TITLE
Fix Genereic CSV

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#1065]
the generic CSV format doesn't allow to upload Findings with Active=True and Verified=True: once the import is done, even by setting these columns to "True", the findings are always Inactive and Verified is unticked. Is that expected? In that case, what's the point to have these columns in the CSV format?

**Comment by devGregA** [comment]
More info: https://github.com/DefectDojo/django-DefectDojo/issues/810

**Comment by devGregA** [comment]
Eric, Sample file is here: https://github.com/DefectDojo/sample-scan-files/tree/master/generic

**Comment by ptrovatelli** [comment]
@devGregA I think this broke the APIV1 importscan call (there is no test on this; only apiv2 import is tested). 
Found on python2 and python3 branch
python2 branch: 
```
Internal Server Error: /api/v1/importscan/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 221, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 461, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 493, in dispatch
    response = method(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1401, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "./dojo/api.py", line 1467, in obj_create
    parser = import_parser_factory(bundle.data['file'], t, bundle.data['scan_type'])
TypeError: import_parser_factory() takes at least 4 arguments (3 given)
```

python3 branch: 
```
Internal Server Error: /api/v1/importscan/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 228, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 468, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 500, in dispatch
    response = method(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 1409, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "./dojo/api.py", line 1466, in obj_create
    parser = import_parser_factory(bundle.data['file'], t, bundle.data['scan_type'])
TypeError: import_parser_factory() missing 1 required positional argument: 'verified'
Internal Server Error: /api/v1/importscan/
```

This is due to the change in import_parser_factory signature in factory.py: there are 2 calls in api.py with only 3 parameters: 
```
parser = import_parser_factory(bundle.data['file'], t, bundle.data['scan_type'])
parser = import_parser_factory(bundle.data['file'], test, scan_type)

```
We could add a dummy "true","true" parameter in the calls but do we really need to have those fields at import_parser_factory level? 

To reproduce: see https://defectdojo.readthedocs.io/en/latest/api-docs.html "Manually calling the API"

**Comment by aaronweaver** [comment]
@devEricA Can you investigate?

**Comment by devEricA** [comment]
I am on it @aaronweaver
