### ISSUE TITLE
Endpoint duplicates and migration

### ISSUE THREAD

**Issue by ptitkosmos** [DefectDojo/django-DefectDojo#10719]
**Bug description**
I got duplicated endpoints on finding. They seem to be created by the MS Defender Parser. 
In the logs, I see (too) many warning about them when the container restarts whereas I have only 3 duplicates and they are linked to few findings.
Running the migration fails due to unique key.

**Steps to reproduce**
1. Import by api MS Defender zip file with machines and vulnerabilities (not sure if it's the first import or after which duplicates the endpoints, I will try to provide new steps for this part later)
2. Go to Endpoint migration
3. See that it detects duplicates
4. Click on migrate
5. See error in log (in UI it's only the "Well, that's unexpected" message)

**Expected behavior**
1. Endpoints should not have duplicates in first intention
2. Log should not verbose so much
3. Migration may handle such cases

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo: v. 2.35.4 ( release mode ) 

**Logs** 
For endpoint migration error
```
[08/Aug/2024 09:28:53] INFO [dojo.endpoint.utils:205] There is not broken endpoint.
[08/Aug/2024 09:28:53] INFO [dojo.endpoint.utils:231] Merging Endpoints ['10.33.128.30 (id=1731)'] into '10.33.128.30 (id=1730)'
[08/Aug/2024 09:28:53] ERROR [django.request:241] Internal Server Error: /endpoint/migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "endpoint-finding relation"
DETAIL:  Key (finding_id, endpoint_id)=(379942, 1730) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/endpoint/views.py", line 469, in migrate_endpoints_view
    html_log = clean_hosts_run(apps=apps, change=(request.method == 'POST'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/endpoint/utils.py", line 234, in clean_hosts_run
    .update(endpoint=ep_ids[0])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1191, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: duplicate key value violates unique constraint "endpoint-finding relation"
DETAIL:  Key (finding_id, endpoint_id)=(379942, 1730) already exists.

```

**Screenshots**
An example of a finding with duplicated endpoints
![image](https://github.com/user-attachments/assets/907bb86b-cda9-46e8-8b96-24dae972a210)
Endpoint > Migrate page
![image](https://github.com/user-attachments/assets/38983da4-3f7b-4eab-b2bc-1b276be862dc)
Log in my container after restarting the pod (80% is this warning)
![image](https://github.com/user-attachments/assets/d21f3dd8-faee-41c4-a0f3-24851a92c8a5)

**Comment by valentijnscholten** [comment]
@ptitkosmos Can you try again, I remember early in the year we did quite some changes to this parser. If it still happens, please provide a way to reproduce it or a detailed stacktrace as above.
