### ISSUE TITLE
Error in new update

### ISSUE THREAD

**Issue by mhsinj0** [DefectDojo/django-DefectDojo#10833]
after new update in defectdojo project i update the docker images from latest via docker pull 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
django-defectdojo-uwsgi-1         |     raise ex.with_traceback(None)
django-defectdojo-uwsgi-1         | django.db.utils.ProgrammingError: relation "django_session" does not exist
django-defectdojo-uwsgi-1         | LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
django-defectdojo-uwsgi-1         |                                                              ^
django-defectdojo-uwsgi-1         | 
django-defectdojo-uwsgi-1         | During handling of the above exception, another exception occurred:
django-defectdojo-uwsgi-1         | 
django-defectdojo-uwsgi-1         | Traceback (most recent call last):
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
django-defectdojo-uwsgi-1         |     return self._session_cache
django-defectdojo-uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^
django-defectdojo-uwsgi-1         | AttributeError: 'SessionStore' object has no attribute '_session_cache'
django-defectdojo-uwsgi-1         | 
django-defectdojo-uwsgi-1         | During handling of the above exception, another exception occurred:
django-defectdojo-uwsgi-1         | 
django-defectdojo-uwsgi-1         | Traceback (most recent call last):
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
django-defectdojo-uwsgi-1         |     return self.cursor.execute(sql, params)
django-defectdojo-uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
django-defectdojo-uwsgi-1         |     raise ex.with_traceback(None)
django-defectdojo-uwsgi-1         | psycopg.errors.UndefinedTable: relation "django_session" does not exist
django-defectdojo-uwsgi-1         | LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
django-defectdojo-uwsgi-1         |                                                              ^

i don't make code to fetch data from django_session table or columns and i don't make new databases like this names iam edit in the project but why this error show after update?

**Comment by mhsinj0** [comment]
complete of error from postgresql
django-defectdojo-postgres-1      | 2024-08-31 14:11:25.405 UTC [44] ERROR:  relation "django_session" does not exist at character 109
django-defectdojo-postgres-1      | 2024-08-31 14:11:25.405 UTC [44] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2024-08-31 14:11:25.402278+00:00'::timestamptz AND "django_session"."session_key" = 'gqzh921664z64zytqkybsqld38vr21sz') LIMIT 21
django-defectdojo-postgres-1      | 2024-08-31 14:11:25.411 UTC [45] ERROR:  relation "django_session" does not exist at character 109
django-defectdojo-postgres-1      | 2024-08-31 14:11:25.411 UTC [45] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2024-08-31 14:11:25.408755+00:00'::timestamptz AND "django_session"."session_key" = '2twx74lprs3tsb4u8fwpsl4nr41r2d0w') LIMIT 21
django-defectdojo-postgres-1      | 2024-08-31 14:11:25.412 UTC [45] ERROR:  relation "django_session" does not exist at character 109

**Comment by mhsinj0** [comment]
i solved this issues but with baaad way 

i copy database from the before the last docker image and insert it to new image 

if you have any good ways for next times tell me

**Comment by mtesauro** [comment]
@mhsinj0 You don't mention how you did the install so I'm going to answer as if you were running DefectDojo in docker compose.

The initialization container is what's responsible for doing upgrades especially any DB changes required. If you stop your compose, update the image references in the yaml compose file and start up the compose, the initialization container will run any needed migrations between DefectDojo versions.

I've been running the [public DefectDojo demo](https://demo.defectdojo.org) updating weekly using this method for 8+ years without issue.
