### ISSUE TITLE
Error on worker after upgrading to 2.38.4

### ISSUE THREAD

**Issue by sebglon** [DefectDojo/django-DefectDojo#10982]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp.org/slack/invite)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
A clear and concise description of what the bug is. For errors include at least the exact error message you are seeing (including traceback).

**Steps to reproduce**
1. Upgrade helm chart from 1.6.151 to 1.6.152
2. Wait for the deployment
3. An helm rollback is trigered due to timeout
4. new version is 1.6.151
5.  re-upgrade to 1.6.152 with success but now we have the crashloop on celery pods
Now we have no other logs on celery worker because it crash every time with the provided logs below.

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Kubernetes / Helm
 - DefectDojo version (see footer) or commit message:  1.6.152

**Logs** 
```
celery [01/Oct/2024 13:44:34] INFO [dojo.models:4572] enabling audit logging
celery System check identified no issues (0 silenced).
celery Traceback (most recent call last):
celery   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 94, in convert
celery     return tuple(reversed(sorted(map(int, value))))
celery                           ^^^^^^^^^^^^^^^^^^^^^^^
celery ValueError: invalid literal for int() with base 10: ''
celery
celery During handling of the above exception, another exception occurred:
celery
celery Traceback (most recent call last):
celery   File "/usr/local/bin/celery", line 8, in <module>
celery     sys.exit(main())
celery              ^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
celery     sys.exit(_main())
celery              ^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
celery     return celery(auto_envvar_prefix="CELERY")
celery            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
celery     return self.main(*args, **kwargs)
celery            ^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
celery     rv = self.invoke(ctx)
celery          ^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1686, in invoke
celery     sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
celery               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 943, in make_context
celery     self.parse_args(ctx, args)
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args
celery     value, args = param.handle_parse_result(ctx, opts, args)
celery                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result
celery     value = self.process_value(ctx, value)
celery             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 2356, in process_value
celery     value = self.type_cast_value(ctx, value)
celery             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 2344, in type_cast_value
celery     return convert(value)
celery            ^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 2316, in convert
celery     return self.type(value, param=self, ctx=ctx)
celery            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/click/types.py", line 83, in __call__
celery     return self.convert(value, param, ctx)
celery            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 97, in convert
celery     f"Got {value.join(',')} instead.")
celery            ^^^^^^^^^^
celery AttributeError: 'list' object has no attribute 'join'
```
**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by mtesauro** [comment]
Appreciate the log entries but there's little else to go one - version of DefectDojo, deploy method, ...

All those things you scrolled past to paste the log entries actually help us triage issues.

**Comment by sebglon** [comment]
Hi, 
Thanks for your reply.
I have updated the issue description.

The issue is probably related to a data corruption due to a rolloback during our first upgrade.
Now, we need to find a way to identify a workarround to fix the data corruption an retrieve the celery de-duplication tasks.

**Comment by sebglon** [comment]
here are some debug logs from celery workers:
```
[04/Oct/2024 09:28:27] DEBUG [celery.utils.functional:335]
def add_epic(*args, **kwargs):
    return 1

[04/Oct/2024 09:28:27] DEBUG [celery.utils.functional:335]
def add_comment(*args, **kwargs):
    return 1

[04/Oct/2024 09:28:27] DEBUG [celery.utils.functional:335]
def post_process_finding_save(*args, **kwargs):
    return 1

[04/Oct/2024 09:28:27] DEBUG [celery.utils.functional:335]
def add_endpoints_to_unsaved_finding(self, finding, endpoints, **kwargs):
    return 1

[04/Oct/2024 09:28:27] DEBUG [celery.utils.functional:335]
def mitigate_endpoint_status(self, endpoint_status_list, user, **kwargs):
    return 1

[04/Oct/2024 09:28:27] DEBUG [celery.utils.functional:335]
def reactivate_endpoint_status(self, endpoint_status_list, **kwargs):
    return 1

System check identified no issues (0 silenced).
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 94, in convert
    return tuple(reversed(sorted(map(int, value))))
                          ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:
```

**Comment by sebglon** [comment]
After droping all my helm and re-create it, i have no more error

**Comment by mtesauro** [comment]
@sebglon Thanks for providing the extra details - it's appreciated.

Unfortunately, our timezone differences didn't allow me to make use of those extra details.  Very happy you got it sorted out though :tada:
