### ISSUE TITLE
Import of Trivy Scan with empty ClusterName fails

### ISSUE THREAD

**Issue by paraddise** [DefectDojo/django-DefectDojo#10991]
**Bug description**

I'm trying to setup scanning of kubernetes cluster with trivy and secureCodeBox.
When trivy k8s scan finished, parses tries to upload results to DefectDojo with test type `Trivy Scan`.
But DefectDojo rejects because of `ClusterName` field is empty.

```json
{
  "ClusterName": "",
  "Resources": [...]
}
```

**Steps to reproduce**
Deploy latest secureCodeBox operator
Deploy defectdojo hook version 4.6.0
Run `trivy-k8s` scan.

**Expected behavior**
Scan results successfully uploaded.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: defectdojo/defectdojo-django
 - DefectDojo version: 2.38.4

**Logs** 
Use `docker compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

DefectDojo logs
```
uwsgi [pid: 19|app: -|req: -/-] 192.168.109.79 (-) {60 vars in 2278 bytes} [Wed Oct  2 12:39:28 2024] POST /api/v2/reimport-scan/ => generated 62 bytes in 55 msecs (HTTP/1.1 400) 8 headers in 243 bytes (1 switches on core 1)
```

persistence-defectdojo logs
```
2024-10-02 12:40:01 ERROR DefaultImportScanService:128 - Exception while attaching findings to engagement: 400 Bad Request: "{"message":"['Schema of Trivy json report is not supported']"}"
2024-10-02 12:40:01 ERROR DefectDojoPersistenceProvider:30 - Failed to attach findings to engagement.
io.securecodebox.persistence.defectdojo.exception.PersistenceException: Failed to attach findings to engagement.
    at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.createFindings(DefaultImportScanService.java:129)
    at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.reimportScan(DefaultImportScanService.java:80)
    at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:144)
    at io.securecodebox.persistence.DefectDojoPersistenceProvider.execute(DefectDojoPersistenceProvider.java:50)
    at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:28)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"message":"['Schema of Trivy json report is not supported']"}"
    at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
    at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.exchangeRequest(DefaultImportScanService.java:135)
    at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.createFindings(DefaultImportScanService.java:126)
    ... 4 more
```

**Additional Context**

This bug was mentioned in [old secure code box issue](https://github.com/secureCodeBox/secureCodeBox/issues/2364#issuecomment-2009381947).
And I'am suggesting the same solution to check `cluster_name` with `None`.

**Comment by manuel-sommer** [comment]
Please close this issue if it is resolved @paraddise
