### ISSUE TITLE
500 server error Internal Server Error: /product/1/import_scan_results

### ISSUE THREAD

**Issue by elenabdc** [DefectDojo/django-DefectDojo#1124]
**Bug description**
When trying to upload large Burp XML scan, obtained 500 server error.

**Steps to reproduce**
1. Get XML Burp scan report
2. Upload it into DefectDojo
3. See error

**Expected behavior**
Scan should be uploaded

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: c4e38e01: Merge pull request #1121 from DefectDojo/revert-1112-dev [2019-05-10 10:42:22 -0400]

**Console logs** (optional)

> uwsgi_1         | Internal Server Error: /product/1/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/product/views.py", line 382, in import_scan_results_prod
uwsgi_1         |     return import_scan_results(request, pid=pid)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 519, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t)
uwsgi_1         |   File "./dojo/tools/factory.py", line 53, in import_parser_factory
uwsgi_1         |     parser = BurpXmlParser(file, test)
uwsgi_1         |   File "./dojo/tools/burp/parser.py", line 47, in __init__
uwsgi_1         |     self.items = [data for data in self.get_items(tree, test)]
uwsgi_1         |   File "./dojo/tools/burp/parser.py", line 82, in get_items
uwsgi_1         |     item = get_item(node, test)
uwsgi_1         |   File "./dojo/tools/burp/parser.py", line 202, in get_item
uwsgi_1         |     collab_details.append(event.findall('lookupType')[0].text)
uwsgi_1         | IndexError: list index out of range
uwsgi_1         | [pid: 1|app: 0|req: 266/266] 172.18.0.1 () {52 vars in 1253 bytes} [Fri May 10 16:22:00 2019] POST /product/1/import_scan_results => generated 27 bytes in 437 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)
nginx_1         | 172.18.0.1 - - [10/May/2019:16:22:00 +0000] "POST /product/1/import_scan_results HTTP/1.1" 500 27 "http://127.0.0.1:9090/product/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" "-"

**Comment by adracea** [comment]
Okay , this looks like it's hitting my code. It seems like you have some burp collaborator issues in there , could you upload a redacted version of the report/collaborator issues ?

**Comment by devGregA** [comment]
Can't validate without a sample scan file.

**Comment by dragos-sh** [comment]
@devGregA we can share with you a working sample to have a look over because we just hit the same issue. Burp 2.0.21. xml base64 encoded data, size 55 megs. Please let us know if that would help you out. Cheers.

**Comment by adracea** [comment]
@dragos-sh That would be really helpful in order to properly triage this issue and get a fix going. Cheers .

**Comment by dragos-sh** [comment]
@adracea here is it. https://drive.google.com/open?id=1tzslTqYC_fHpDO7SnURKLfBm40WpiFb1 

Is an encrypted archive with some real data. Please have me updated it would be alright to send the password on your current GitHub associated email address. 

Cheers. 

Dragos

**Comment by adracea** [comment]
> @adracea here is it. https://drive.google.com/open?id=1tzslTqYC_fHpDO7SnURKLfBm40WpiFb1
> 
> Is an encrypted archive with some real data. Please have me updated it would be alright to send the password on your current GitHub associated email address.
> 
> Cheers.
> 
> Dragos

It would be best if you could try to somehow redact the confidential parts out and upload it here as a .txt for further reference in the unit testing effort we have going on .

**Comment by dragos-sh** [comment]
@adracea I am affraid I cannot do that atm. We have decided to try to help you out and provide some real data. To be fair, except a small part, the file does not contain any high sensitive details which you guys should not have access while doing an **inhouse** debugging, without exposing this file to the open Internet.  I'm sorry if this does not represent an option for you.

**Comment by exenin** [comment]
Ive been running into random  500s on importing scan results,  first it was ZAP, then NMAP.

For the  NMAP xml results file:
Turns out the XML file was malformed, missing the closing tag for 
  </nmaprun>  

I am generating the result from python-nmap
