### ISSUE TITLE
Import of burp XML fails at do_clean

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/django-DefectDojo#1224]
**Bug description**
If the XML report contains empty ```<issue>``` items like: ```<issueBackground>``` or ```<remediationDetail>``` or ``` <issueDetail>``` then import (via web upload) fails with the message below (console logs)

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Screenshots** 
![image](https://user-images.githubusercontent.com/1497172/59093279-71e52900-890b-11e9-9245-2fa830cc6396.png)

**Console logs**
```
Internal Server Error: /product/3/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/product/views.py", line 382, in import_scan_results_prod
    return import_scan_results(request, pid=pid)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/engagement/views.py", line 519, in import_scan_results
    parser = import_parser_factory(file, t)
  File "./dojo/tools/factory.py", line 53, in import_parser_factory
    parser = BurpXmlParser(file, test)
  File "./dojo/tools/burp/parser.py", line 47, in __init__
    self.items = [data for data in self.get_items(tree, test)]
  File "./dojo/tools/burp/parser.py", line 82, in get_items
    item = get_item(node, test)
  File "./dojo/tools/burp/parser.py", line 273, in get_item
    background = do_clean(item_node.findall('issueBackground'))
  File "./dojo/tools/burp/parser.py", line 148, in do_clean
    myreturn += x.text
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by devGregA** [comment]
Hi @wheelq we can't investigate without a sample scan. Please feel free to reopen if you can provide.

**Comment by adracea** [comment]
@wheelq are those issues generated by burp itself or extensions or manually modified ? This happens because those fields are mandatory .

**Comment by wheelq** [comment]
> @wheelq are those issues generated by burp itself or extensions or manually modified ? This happens because those fields are mandatory .

I have extracted all the findings and it turns out the fileds were missing because of the extensions generating those reports. 

How come those fields are mandatory? There are some findings which do not require any content/explanation in those fields. .

But yes, this is the case here. Would be nice having more explicit error rather than a complete failure ;)
