### ISSUE TITLE
Report builder fails with Server Error (500)

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/django-DefectDojo#1228]
**Bug description**
DD site returns Server Error (500) after submitting 'Save and Run' button in Report Builder using default settings.

**Steps to reproduce**
1. Go to '/reports/builder'
2. Click on the 'Save and Run'
3. Server Error (500) is displayed

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Screenshots**
![image](https://user-images.githubusercontent.com/1497172/59186098-efa67000-8b69-11e9-9aad-0a70ec741b3f.png)

**Console logs**
```
Internal Server Error: /reports/custom
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/reports/views.py", line 81, in custom_report
    finding_notes=False, finding_images=False, host=host)
  File "./dojo/reports/widgets.py", line 445, in report_widget_factory
    'value']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Additional context**
In my DB I have roughly over 2000 findings from different tools

**Comment by underfl0w** [comment]
I've been able to reproduce this issue. 28 findings in total from Nikto, Nmap and OpenVAS. 
Consolelog from  django-defectdojo_uwsgi_1 
`Exception raised while rendering {% include %} for template 'dojo/report_widget.html'. Empty string rendered instead.


Traceback (most recent call last):


  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 216, in render


    return template.render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render


    return self._render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render


    return self.nodelist.render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render


    bit = node.render_annotated(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated


    return self.render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render


    nodelist.append(node.render_annotated(context))


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated


    return self.render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render


    return nodelist.render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render


    bit = node.render_annotated(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated


    return self.render(context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1046, in render


    return render_value_in_context(output, context)


  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context


    value = force_text(value)


  File "/usr/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text


    s = six.text_type(s)


  File "/usr/local/lib/python2.7/site-packages/django/utils/html.py", line 385, in <lambda>


    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))


  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 41, in __str__


    return self.as_widget()


  File "./dojo/templatetags/event_tags.py", line 22, in as_widget


    return old_as_widget(widget, attrs, only_initial)


  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 101, in as_widget


    attrs = self.build_widget_attrs(attrs, widget)


  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 257, in build_widget_attrs


    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:


  File "/usr/local/lib/python2.7/site-packages/django/forms/widgets.py", line 692, in use_required_attribute


    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)


  File "/usr/local/lib/python2.7/site-packages/django/forms/widgets.py", line 675, in _choice_has_empty_value


    value, _ = choice


ValueError: too many values to unpack


[pid: 1|app: 0|req: 209/209] 172.18.0.1 () {44 vars in 801 bytes} [Tue Jun 11 12:44:17 2019] GET /reports/builder => generated 79487 bytes in 298 msecs (HTTP/1.1 200) 6 headers in 420 bytes (1 switches on core 0)


Internal Server Error: /reports/custom


Traceback (most recent call last):


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner


    response = get_response(request)


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response


    response = self._get_response(request)


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response


    response = self.process_exception_by_middleware(e, request)


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response


    response = wrapped_callback(request, *callback_args, **callback_kwargs)


  File "./dojo/reports/views.py", line 81, in custom_report


    finding_notes=False, finding_images=False, host=host)


  File "./dojo/reports/widgets.py", line 445, in report_widget_factory
`

Console log from django-defectdojo_nginx_1 

`
2019/06/11 12:44:17 [error] 6#6: *169 open() "/usr/share/nginx/html/static/fullcalendar/dist/fullcalendar.min.css" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /static/fullcalendar/dist/fullcalendar.min.css HTTP/1.1", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/reports/builder"


172.18.0.1 - - [11/Jun/2019:12:44:17 +0000] "GET /static/fullcalendar/dist/fullcalendar.min.css HTTP/1.1" 404 154 "http://0.0.0.0:8080/reports/builder" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"


2019/06/11 12:44:17 [error] 6#6: *169 open() "/usr/share/nginx/html/static/fullcalendar/dist/fullcalendar.min.js" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /static/fullcalendar/dist/fullcalendar.min.js HTTP/1.1", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/reports/builder"


172.18.0.1 - - [11/Jun/2019:12:44:17 +0000] "GET /static/fullcalendar/dist/fullcalendar.min.js HTTP/1.1" 404 154 "http://0.0.0.0:8080/reports/builder" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"


2019/06/11 12:44:17 [error] 6#6: *169 open() "/usr/share/nginx/html/static/fullcalendar/dist/fullcalendar.min.js" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /static/fullcalendar/dist/fullcalendar.min.js HTTP/1.1", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/reports/builder"


172.18.0.1 - - [11/Jun/2019:12:44:17 +0000] "GET /static/fullcalendar/dist/fullcalendar.min.js HTTP/1.1" 404 154 "http://0.0.0.0:8080/reports/builder" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"


172.18.0.1 - - [11/Jun/2019:12:44:17 +0000] "GET /static/dojo/img/favicon.ico HTTP/1.1" 200 1150 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"


2019/06/11 12:44:18 [error] 6#6: *238 open() "/usr/share/nginx/html/static/dojo/img/openhand.cur" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /static/dojo/img/openhand.cur HTTP/1.1", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/static/dojo/css/dojo.css"


172.18.0.1 - - [11/Jun/2019:12:44:18 +0000] "GET /static/dojo/img/openhand.cur HTTP/1.1" 404 154 "http://0.0.0.0:8080/static/dojo/css/dojo.css" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"


2019/06/11 12:44:19 [error] 6#6: *238 open() "/usr/share/nginx/html/static/dojo/img/closedhand.cur" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /static/dojo/img/closedhand.cur HTTP/1.1", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/reports/builder"


172.18.0.1 - - [11/Jun/2019:12:44:19 +0000] "GET /static/dojo/img/closedhand.cur HTTP/1.1" 404 154 "http://0.0.0.0:8080/reports/builder" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"


172.18.0.1 - - [11/Jun/2019:12:44:27 +0000] "POST /reports/custom HTTP/1.1" 500 27 "http://0.0.0.0:8080/reports/builder" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"`

**Comment by exenin** [comment]
- [11/Jun/2019:12:44:17 +0000] "GET /static/fullcalendar/dist/fullcalendar.min.js HTTP/1.1" 404 154    could this be it?

**Comment by Maffooch** [comment]
Hello all. A few of the mentioned issues have been fixed on the dev branch and will make it to the master branch in the next upcoming release. Check them out and see if they are still creating problems for you.
