### ISSUE TITLE
Server Error (500) Upload Risk Exception

### ISSUE THREAD

**Issue by Oxima69** [DefectDojo/django-DefectDojo#1323]
**Bug description**
when saving a risk exception error 500 appears

**Steps to reproduce**
1. Go to 'Engagement.'
2. Click on '+ Add Risk Acceptance'
3. Scroll down to 'save.'

**Deployment method**
- [ ] Kubernetes
- [ ] Docker
- [X] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: Dev branch
2d099e39: Merge pull request #1312 from madchap/fix-twistlock-sev-1302 [2019-06-27 13:17:19 -0500]

**Console logs** (optional)
Jun 28 14:12:24 dojo celeryworker[1629]: [2019-06-28 08:12:24,136: INFO/ForkPoolWorker-3] Task dojo.tasks.async_dupe_delete[353a001a-ec6c-427a-9891-d9a8bf2b763f] succeeded in 0.004296302000511787s: None
Jun 28 14:12:26 dojo dojo[1621]: [pid: 1854|app: 0|req: 541/1162] 172.17.166.1 () {44 vars in 836 bytes} [Fri Jun 28 08:12:26 2019] GET /alerts/count => generated 12 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 147 bytes (1 switches on core 0)
Jun 28 14:12:36 dojo dojo[1621]: [pid: 1750|app: 0|req: 250/1163] 172.17.166.1 () {44 vars in 836 bytes} [Fri Jun 28 08:12:36 2019] GET /alerts/count => generated 12 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 147 bytes (1 switches on core 0)
Jun 28 14:12:37 dojo dojo[1621]: applying rules
Jun 28 14:12:37 dojo dojo[1621]: Internal Server Error: /engagement/1/upload_risk_acceptance
Jun 28 14:12:37 dojo dojo[1621]: Traceback (most recent call last):
Jun 28 14:12:37 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Jun 28 14:12:37 dojo dojo[1621]:     response = get_response(request)
Jun 28 14:12:37 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Jun 28 14:12:37 dojo dojo[1621]:     response = self.process_exception_by_middleware(e, request)
Jun 28 14:12:37 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Jun 28 14:12:37 dojo dojo[1621]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 28 14:12:37 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Jun 28 14:12:37 dojo dojo[1621]:     return view_func(request, *args, **kwargs)
Jun 28 14:12:37 dojo dojo[1621]:   File "./dojo/engagement/views.py", line 736, in upload_risk
Jun 28 14:12:37 dojo dojo[1621]:     risk.accepted_findings = findings
Jun 28 14:12:37 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 538, in __set__
Jun 28 14:12:37 dojo dojo[1621]:     % self._get_set_deprecation_msg_params(),
Jun 28 14:12:37 dojo dojo[1621]: TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use accepted_findings.set() instead.
Jun 28 14:12:37 dojo dojo[1621]: [pid: 1851|app: 0|req: 111/1164] 172.17.166.1 () {52 vars in 1247 bytes} [Fri Jun 28 08:12:37 2019] POST /engagement/1/upload_risk_acceptance => generated 27 bytes in 507 msecs (HTTP/1.1 500) 5 headers in 159 bytes (1 switches on core 0)

**Comment by Oxima69** [comment]
Nice ....it works, thank you for your effort.
