### ISSUE TITLE
Veracode ssllabs import fail

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/django-DefectDojo#1337]
DD fails when ssllabs report file doesn't contain `suites` for any of the scanned hosts.

## Error:
```
Internal Server Error: /engagement/38/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/engagement/views.py", line 519, in import_scan_results
    parser = import_parser_factory(file, t)
  File "./dojo/tools/factory.py", line 107, in import_parser_factory
    parser = SSLlabsParser(file, test)
  File "./dojo/tools/ssllabs/parser.py", line 76, in __init__
    if "list" in endpoints["details"]["suites"]:
KeyError: 'suites'
```

**Comment by wheelq** [comment]
nice #1337 :D
