### ISSUE TITLE
 Veracode Static Dynamic upload fail

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/django-DefectDojo#1338]
File to import: veracode/veracode.Sample_Static_and_Dynamic.xml
Issue: DD reports Server Error (500)
Logs:

```
Internal Server Error: /product/2/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/product/views.py", line 382, in import_scan_results_prod
    return import_scan_results(request, pid=pid)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/engagement/views.py", line 519, in import_scan_results
    parser = import_parser_factory(file, t)
  File "./dojo/tools/factory.py", line 69, in import_parser_factory
    parser = VeracodeXMLParser(file, test)
  File "./dojo/tools/veracode/parser.py", line 59, in __init__
    dupe_key = sev + flaw.attrib['cweid'] + flaw.attrib['module'] + flaw.attrib['type'] + flaw.attrib['line'] + flaw.attrib['issueid']
KeyError: 'line'
```

**Comment by wheelq** [comment]
why is it marked as closed? the issue still exists

**Comment by dr3dd589** [comment]
hello, @wheelq make a pull on the dev branch it is fixed in dev branch. Master branch is still not updated it will take some time to merge dev branch to master.

**Comment by wheelq** [comment]
> hello, @wheelq make a pull on the dev branch it is

Thanks, I already did, but dev needs some hacks (python tool not found etc). Thanks, will try and hopefully it works :)
