### ISSUE TITLE
ValueError on importing Immuniweb sample.

### ISSUE THREAD

**Issue by dr3dd589** [DefectDojo/django-DefectDojo#1476]
**Bug description**

**Steps to reproduce**
1. import immuniweb sample [here](https://github.com/DefectDojo/sample-scan-files/blob/master/immuniweb/ImmuniWeb-multiple-vuln.xml)

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: [use `git show -s --format="%h: %s [%ci]"`]

**Sample scan files** (optional)
 [sample](https://github.com/DefectDojo/sample-scan-files/blob/master/immuniweb/ImmuniWeb-multiple-vuln.xml)
**Screenshots** (optional)

**Console logs** (optional)
```
item blowup
Code Injection in /contributions
applying rules
applying rules
item blowup
Default Administrative Credentials
applying rules
applying rules
item blowup
Improper Access Control to /benefits
applying rules
applying rules
item blowup
CSRF in /profile
applying rules
applying rules
item blowup
Weak Password Policy
Internal Server Error: /product/1/import_scan_results
Traceback (most recent call last):
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/dojo/product/views.py", line 413, in import_scan_results_prod
    return import_scan_results(request, pid=pid)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/dojo/engagement/views.py", line 548, in import_scan_results
    item.save(dedupe_option=False, false_history=True)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/dojo/models.py", line 1361, in save
    super(Finding, self).save(*args, **kwargs)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1334, in execute_sql
    for sql, params in self.as_sql():
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1278, in as_sql
    for obj in self.query.objs
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1278, in <listcomp>
    for obj in self.query.objs
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1277, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1218, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 789, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 784, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/dr3dd/gsoc/local/django-DefectDojo/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1819, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

```

**Additional context** (optional)

**Comment by Maffooch** [comment]
@dr3dd589 I totally did this. I apologize for creating extra work for you!
