### ISSUE TITLE
Error 500 on getting slack member

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1504]
**Bug description**
I enabled slack global notification, and upon importing a new report, I got a 500 error:

```
uwsgi_1         | Starting new HTTPS connection (1): slack.com:443
uwsgi_1         | https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 109
uwsgi_1         | Internal Server Error: /engagement/30/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 607, in import_scan_results
uwsgi_1         |     url=reverse('view_test', args=(t.id, )))
uwsgi_1         |   File "./dojo/utils.py", line 1620, in create_notification
uwsgi_1         |     user.usercontactinfo.slack_username)
uwsgi_1         |   File "./dojo/utils.py", line 1479, in get_slack_user_id
uwsgi_1         |     for member in users["members"]:
uwsgi_1         | KeyError: 'members'
```

**Comment by madchap** [comment]
I was wondering if this could be related to the fact I have Google SAML enabled, and therefore a few users there.

**Comment by aymeric-lagier** [comment]
I have the same issue without Google SAML enabled

**Comment by dfirpaul** [comment]
same issue here standard authentication and okta.
