### ISSUE TITLE
Generating a report with notes causes 500 server error

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1554]
**Bug description**
Only when wanting to a report with "Notes" "Yes". If notes are not to be included in the report, then it works fine.

```
uwsgi_1         | [pid: 1|app: 0|req: 29204/29204] 172.18.64.94 () {54 vars in 3252 bytes} [Thu Sep 12 14:51:46 2019] GET /test/58/report?title=&cve=&steps_to_reproduce=&severity_justification=&active=&verified=&false_p=&duplicate=&duplicate_finding=&out_of_scope=&under_review=unknown&review_requested_by=&under_defect_review=unknown&defect_review_requested_by=&is_Mitigated=unknown&mitigated=&mitigated_by=&last_reviewed_by=&line_number=&sourcefilepath=&sourcefile=&param=&payload=&hash_code=&line=&file_path=&static_finding=unknown&dynamic_finding=unknown&created=&scanner_confidence=&test__engagement__risk_acceptance= => generated 1029527 bytes in 2229 msecs (HTTP/1.1 200) 5 headers in 272 bytes (4 switches on core 0)
uwsgi_1         | [pid: 1|app: 0|req: 29205/29205] 172.18.64.94 () {52 vars in 2139 bytes} [Thu Sep 12 14:51:49 2019] GET /alerts/count => generated 12 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
uwsgi_1         | [pid: 1|app: 0|req: 29206/29206] 172.18.64.153 () {40 vars in 533 bytes} [Thu Sep 12 14:51:49 2019] GET / => generated 0 bytes in 9 msecs (HTTP/1.1 302) 5 headers in 149 bytes (1 switches on core 0)
uwsgi_1         | Internal Server Error: /test/58/report
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/reports/views.py", line 363, in test_report
uwsgi_1         |     return generate_report(request, test)
uwsgi_1         |   File "./dojo/reports/views.py", line 850, in generate_report
uwsgi_1         |     'host': "",
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
uwsgi_1         |     content = loader.render_to_string(template_name, context, request, using=using)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
uwsgi_1         |     return template.render(context, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
uwsgi_1         |     return self.template.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 171, in render
uwsgi_1         |     return self._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
uwsgi_1         |     return compiled_parent._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
uwsgi_1         |     result = block.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 309, in render
uwsgi_1         |     return nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 511, in render
uwsgi_1         |     values = {key: val.resolve(context) for key, val in self.extra_context.items()}
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 511, in <dictcomp>
uwsgi_1         |     values = {key: val.resolve(context) for key, val in self.extra_context.items()}
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 698, in resolve
uwsgi_1         |     new_obj = func(obj, *arg_vals)
uwsgi_1         |   File "./dojo/templatetags/get_note_status.py", line 7, in get_public_notes
uwsgi_1         |     return notes.filter(private=False)
uwsgi_1         | AttributeError: 'str' object has no attribute 'filter'
```

@Maffooch you seem to have written that little piece of code, do you have any idea maybe? Thanks.

fyi @Wadeck

**Comment by Maffooch** [comment]
Sounds good. Madchap had the opposite results when he replied to the PR itself. Not sure what the deal is. For my testing, I had added a tag to each of the severities and tweaked until findings were in their respective homes. Got any other ideas for test cases?

**Comment by madchap** [comment]
Yes @Maffooch I was a bit too quick in jumping the gun, sorry about that. I had only tried at engagement level. :-( Generating the report directly from the test still fails with that same error indeed. 

FWIW, I also tried generating a report out of a test that has no note associated with any findings, yet it fails with the same error.

**Comment by madchap** [comment]
So I think I had been confused with my local instance and our "main" instance.

I ended up moving our main instance to full "dev" mode and not "release" mode, as this is more a PITA than anything else at this stage and was very error prone also when applying patches and such.

I fully confirm now that it is fixed. I will let @Wadeck double-check, but this time around I am actually sitting at a desk while doing this.

**Comment by Wadeck** [comment]
@madchap @Maffooch double check done, it works for Product, Engagement and Test, perfectly fine, thank you for the quick bug fix!

**Comment by madchap** [comment]
Closing this, thanks!
