### ISSUE TITLE
Server Error (500) : On Accepted Finding Menu

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1576]
**Bug description**
Server Error (500) : On Accepted Finding Menu

**Steps to reproduce**
1. Login to DefectDojo
2. Navigate to Findings
3. Click on Accepted Findings

**Expected behavior**
It should display list of findings that are Accepted.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: CentOS 7
 - DefectDojo version: master branch

**Console logs** (optional)
Internal Server Error: /finding/accepted
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/finding/views.py", line 158, in accepted_findings
    findings = AcceptedFingingSuperFilter(request.GET, queryset=findings)
  File "./dojo/filters.py", line 523, in __init__
    for finding in self.queryset.distinct()
  File "./dojo/filters.py", line 524, in <genexpr>
    if finding.cwe > 0 and finding.cwe not in cwe)
TypeError: unorderable types: NoneType() > int()
[pid: 1|app: 0|req: 5124/5124] 10.88.1.152 () {44 vars in 933 bytes} [Wed Oct  2 09:51:53 2019] GET /finding/accepted => generated 27 bytes in 62 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)

**Comment by madchap** [comment]
Please try on the dev branch, and let us know if this happens there too. Cheers.
