### ISSUE TITLE
Getting 500 Server Error in JIRA webhook when jira is closed.

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1600]
Getting 500 Server Error in JIRA webhook when jira is closed.

For reference please refer the below log :

Internal Server Error: /webhook/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "./dojo/jira_link/views.py", line 36, in webhook
    parsed = json.loads(request.body)
  File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[pid: 1|app: 0|req: 15037/15037] 10.10.74.63 () {40 vars in 682 bytes} [Wed Oct 16 02:53:26 2019] POST /webhook/?user_id=djpoc&user_key=djpoc => generated 27 bytes in 59 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)

Due to this Findings are not getting closed when we close the JIRA.

**Comment by frannovo** [comment]
Hi @bilalk88 ,
are you using docker images to deploy DefectDojo? 
I have face similar issue creating comments from jira. The function json.load only accepts a str in python3.5 (https://docs.python.org/3.5/library/json.html#json.loads). With versions 3.6 or 3.7  it accepts a str, bytes or bytearray (https://docs.python.org/3.6/library/json.html#json.loads).

I have created a PR to fix this issue: https://github.com/DefectDojo/django-DefectDojo/pull/1662.

**Comment by bilalk88** [comment]
@frannovo: Yes. I'm using docker-compose based DefectDojo.

Thanks for the update. I will check this fix and update you.
