### ISSUE TITLE
FindingImageAccessToken exception

### ISSUE THREAD

**Issue by Apipia** [DefectDojo/django-DefectDojo#1633]
**Bug description**
Not sure if this is just my setup or not. 
While creating an html report for a test, to obfuscate the /media/ directory, a call is made to /finding/image/<token>. The code that receives this request is in /finding/views.py line 1358.
`def downloading_finding_pic(request,token):`

This is failing with an exception and the image will not load in the report. The exception error message is 
`dojo.models.FindingImageAccessToken.DoesNotExist: FindingImageAccessToken matching query does not exist.`

**Steps to reproduce**
1. Create a test, like a Pen Test 
2. Create a finding.
3. In the finding page, click the hamburger drop down and click "manage images" and upload an image. 
4. Go back to the test, click the hamburger drop down again and click "Report"
5. Make sure "Finding Images" is set to yes and generate a report.
6. Notice that the picture is broken. Open up the developer controls in the browser and look at the network tab, refresh if necessary. Notice the 403 error on /finding/image/<token>.

**Expected behavior**
The image should load on html report.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [X] setup/setup.bash

**Environment information**
 - Operating System: Ubuntu 16.04
 - DefectDojo Commit Message: 8deafd1: Added readme to services information [2019-10-29 12:49:07 -0700]

**Screenshots**
![image](https://user-images.githubusercontent.com/17787069/68235111-7fd0d000-ffb7-11e9-8a3d-62d5bd156318.png)

**Console logs** (optional)
```Downloading finding pic: e241278d-6926-4625-9dcb-c1e2b2d318c6
Unable to download finding pic
FindingImageAccessToken matching query does not exist.
Traceback (most recent call last):
  File "./dojo/finding/views.py", line 1363, in download_finding_pic
    access_token = FindingImageAccessToken.objects.get(token=token)
  File "/opt/dojo/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/dojo/lib/python3.5/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
dojo.models.FindingImageAccessToken.DoesNotExist: FindingImageAccessToken matching query does not exist.
```

**Comment by Apipia** [comment]
Issue no longer exists, has been replaced by #1674
