### ISSUE TITLE
Server error 500 with imported Burp Scanner results without "Base64-encode  requests and responses" checked

### ISSUE THREAD

**Issue by takaharuogasa** [DefectDojo/django-DefectDojo#1634]
**Bug description**
When opening each findings under engagements exported from Burp. Certain items respond with Server Error (500). This error occurs with items imported from Burp scan without "Base64-encode  requests and responses" checked when export from the Burp.

**Steps to reproduce**
1. Export Burp scan result without "Base64-encode  requests and responses" checked
2. Import the scan result at the add new engagement on defectdojo
3. Show each findings

**Expected behavior**
Finding detail are displayed

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Console logs** (optional)
Internal Server Error: /finding/1
Traceback (most recent call last):
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/dojo/django-DefectDojo/dojo/finding/views.py", line 330, in view_finding
    'next_finding': next_finding
  File "/opt/dojo/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/opt/dojo/django-DefectDojo/dojo/models.py", line 1721, in get_request
    return str(base64.b64decode(self.burpRequestBase64), errors='ignore')
  File "/opt/dojo/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
[05/Nov/2019 17:12:24] "GET /finding/1 HTTP/1.1" 500 27

**Comment by adracea** [comment]
Hello @takaharuogasa the idea is that burp suite itself does base64 encoding by default when exporting to XML . Most the the times the data if not base64 encoded can break the xml format and invalidate it .

**Comment by takaharuogasa** [comment]
@adracea Yes, I understand this is not a bug. My intention was to put information if someone has same issue. In my case, I somehow put the base64 check off sometime before and took for a while to figure out. Thanks!

**Comment by mtesauro** [comment]
@takaharuogasa Thanks for submitting the issue and getting it documented and find-able via a Google Search.  I'll look for places where it makes sense to ad a note about selecting to Base63 encode when exporting from Burp so other's wont' get tripped up on the need to check that box.

I'm closing this and will add notes where it make sense - probably the Sample-Files repo and Read the Docs.
