### ISSUE TITLE
Node Security Platform Scan import scan generates 500

### ISSUE THREAD

**Issue by cristiano-corrado** [DefectDojo/django-DefectDojo#1737]
**Bug description**
Uploading a report both from API and UI generates a 500 in the application

**Steps to reproduce**

1. Run the tool
```
$ nodejsscan -d projectdir -o nodejssecurity-report.json
```
2. upload the report through interface or API /api/v2/import-scan/ 

response :
```
HTTP/1.1 500 Internal Server Error
Server: nginx/1.17.2
Date: Mon, 06 Jan 2020 09:43:00 GMT
Content-Type: text/html
Content-Length: 27
Connection: close
X-Frame-Options: SAMEORIGIN

<h1>Server Error (500)</h1>
```
The docker-compose logs -f error output : 

```
nginx_1         | 2020/01/06 10:21:48 [warn] 10#10: *11 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.19.0.1, server: , request: "POST /product/521/import_scan_results HTTP/1.1", host: "localhost:8081", referrer: "http://localhost:8081/product/521/import_scan_results"
uwsgi_1         | Internal Server Error: /product/521/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/product/views.py", line 413, in import_scan_results_prod
uwsgi_1         |     return import_scan_results(request, pid=pid)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 523, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 110, in import_parser_factory
uwsgi_1         |     parser = NspParser(file, test)
uwsgi_1         |   File "./dojo/tools/nsp/parser.py", line 12, in __init__
uwsgi_1         |     self.items = [data for data in self.get_items(tree, test)]
uwsgi_1         |   File "./dojo/tools/nsp/parser.py", line 32, in get_items
uwsgi_1         |     item = get_item(node, test)
uwsgi_1         |   File "./dojo/tools/nsp/parser.py", line 43, in get_item
uwsgi_1         |     if item_node['cvss_score'] <= 3.9:
uwsgi_1         | TypeError: string indices must be integers
uwsgi_1         | [pid: 1|app: 0|req: 6/6] 172.19.0.1 () {50 vars in 1289 bytes} [Mon Jan  6 10:21:48 2020] POST /product/521/import_scan_results => generated 27 bytes in 180 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)

```
**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: mac but running defect dojo with docker-compose
 - DefectDojo Commit Message: d8cd7607: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Sample scan files** (optional)
any output from nodejsscan

**Screenshots** (optional)
![Screenshot 2020-01-06 at 10 33 52](https://user-images.githubusercontent.com/3243602/71812797-09605500-3070-11ea-959b-ec7096e64041.png)
![Screenshot 2020-01-06 at 10 33 43](https://user-images.githubusercontent.com/3243602/71812802-0bc2af00-3070-11ea-89f1-ed374e2f7105.png)

**Console logs** (optional)
console logs attached above

**Comment by Maffooch** [comment]
Hello @urand0m after a bit of research, the nodejsscan and node security platform scan produce very different results. I will begin working on a parser for nodejsscan.

**Comment by urand0m** [comment]
Hi @Maffooch thanks for the support. When ready more then happy to retest.

**Comment by Maffooch** [comment]
Hey @urand0m new parser is ready at #1745. It's a bit sparse, but there is only so much that can be pulled from those reports.

**Comment by urand0m** [comment]
Hey @Maffooch  great thanks. I will test it now. I'd be happy to help to develop other parsers/plugins how can I contribute? I fixed phpcs and hadolint but CI fails.
