### ISSUE TITLE
Safety Import Scan Error 500

### ISSUE THREAD

**Issue by Dorfus1988** [DefectDojo/django-DefectDojo#1754]
**Bug description**
When i am trying to import a safety scan result (JSON), it fails with status code 500

**Steps to reproduce**
git clone --branche master https://github.com/DefectDojo/django-DefectDojo && cd django-DefectDojo
docker-compose build
docker-compose up
Import a Safety Scan in an engagement 

**Expected behavior**
The scan result should be processed

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Windows 10]
 - DefectDojo version: Master Branch DefectDojo 
Commit Message: d8cd7607: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Console logs** (optional)
uwsgi_1         | Internal Server Error: /engagement/4/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 523, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 158, in import_parser_factory
uwsgi_1         |     parser = SafetyParser(file, test)
uwsgi_1         |   File "./dojo/tools/safety/parser.py", line 10, in __init__
uwsgi_1         |     response = urllib.request.urlopen(url)
uwsgi_1         | NameError: name 'urllib' is not defined

**Comment by Dorfus1988** [comment]
I have tested the dev branch:
1f48dea9: Bump coverage from 5.0.2 to 5.0.4 (#2073) [2020-03-17 08:30:12 +0100]

Now there is a different issue:
nginx_1         | 172.19.0.1 - - [17/Mar/2020:09:51:46 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://localhost:8080/engagement/2/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
uwsgi_1         | sequence item 0: expected str instance, NoneType found
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 552, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 186, in import_parser_factory
uwsgi_1         |     parser = SafetyParser(file, test)
uwsgi_1         |   File "./dojo/tools/safety/parser.py", line 17, in __init__
uwsgi_1         |     self.items = [data for data in self.get_items(tree, test, safety_db)]
uwsgi_1         |   File "./dojo/tools/safety/parser.py", line 39, in get_items
uwsgi_1         |     item = get_item(node, test, safety_db)
uwsgi_1         |   File "./dojo/tools/safety/parser.py", line 47, in get_item
uwsgi_1         |     cve = ''.join(a['cve'] for a in safety_db[item_node['package']] if a['id'] == 'pyup.io-' + item_node['id'])
uwsgi_1         | TypeError: sequence item 0: expected str instance, NoneType found
uwsgi_1         | Error in parser: sequence item 0: expected str instance, NoneType found
uwsgi_1         | [pid: 19|app: 0|req: 17/25] 172.19.0.1 () {60 vars in 1338 bytes} [Tue Mar 17 09:51:51 2020] POST /engagement/2/import_scan_results => generated 0 bytes in 530 msecs (HTTP/1.1 302) 8 headers in 468 bytes (1 switches on core 0)
nginx_1         | 172.19.0.1 - - [17/Mar/2020:09:51:52 +0000] "POST /engagement/2/import_scan_results HTTP/1.1" 302 0 "http://localhost:8080/engagement/2/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
