### ISSUE TITLE
error 500 when importing nessus CSV

### ISSUE THREAD

**Issue by dfirpaul** [DefectDojo/django-DefectDojo#1762]
**Bug description**
We are using nessus, when we import a nessus csv scan result, its giving us Server Error (500)

**Steps to reproduce**
1. Go to 'Engagement then findings'
2. Click on 'import scan results '
3. select nessus for scan type
4. upload the csv file

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
Ubuntu 18.04.3
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]
d8cd7607: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.
[sample.csv.zip](https://github.com/DefectDojo/django-DefectDojo/files/4078583/sample.csv.zip)

**Console logs** (optional)
; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36" "-"
uwsgi_1_6e468e6ea976 | [pid: 1|app: 0|req: 321/321] 192.168.149.1 () {52 vars in 1796 bytes} [Fri Jan 17 14:10:17 2020] POST /product/1/import_scan_results => generated 27 bytes in 136 msecs (HTTP/1.1 500) 5 headers in 159 bytes (1 switches on core 0)
celeryworker_1_58cf7dd83c47 | [2020-01-17 14:10:26,914: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[80b19c71-08d5-4a9f-ab1d-ed57ab62f943]
celeryworker_1_58cf7dd83c47 | [2020-01-17 14:10:26,914: INFO/MainProcess] dojo.tasks.async_dupe_delete[80b19c71-08d5-4a9f-ab1d-ed57ab62f943]: delete excess duplicates
celeryworker_1_58cf7dd83c47 | [2020-01-17 14:10:26,920: ERROR/MainProcess] Task dojo.tasks.async_dupe_delete[80b19c71-08d5-4a9f-ab1d-ed57ab62f943] raised unexpected: ValueError('Cannot use None as a query value',)
celeryworker_1_58cf7dd83c47 | Traceback (most recent call last):
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1_58cf7dd83c47 |     R = retval = fun(*args, **kwargs)
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
celeryworker_1_58cf7dd83c47 |     return self.run(*args, **kwargs)
celeryworker_1_58cf7dd83c47 |   File "/app/dojo/tasks.py", line 288, in async_dupe_delete
celeryworker_1_58cf7dd83c47 |     .filter(num_dupes__gt=dupe_max)
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 892, in filter
celeryworker_1_58cf7dd83c47 |     return self._filter_or_exclude(False, *args, **kwargs)
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
celeryworker_1_58cf7dd83c47 |     clone.query.add_q(Q(*args, **kwargs))
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1290, in add_q
celeryworker_1_58cf7dd83c47 |     clause, _ = self._add_q(q_object, self.used_aliases)
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
celeryworker_1_58cf7dd83c47 |     split_subq=split_subq, simple_col=simple_col,
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1207, in build_filter
celeryworker_1_58cf7dd83c47 |     condition = self.build_lookup(lookups, reffed_expression, value)
celeryworker_1_58cf7dd83c47 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1121, in build_lookup
celeryworker_1_58cf7dd83c47 |     raise ValueError("Cannot use None as a query value")
celeryworker_1_58cf7dd83c47 | ValueError: Cannot use None as a query value

**Comment by ycrumeyrolle** [comment]
Hi, I have the same issue. 
After importing findings from another parser, the celery worker failed and killed the web server. 

There is 2 issues:
- The celery worker kill the web server 
- The celery worker fail

The workaround is to disable the "Delete duplicate" in the Configuration => System settings.

Here is my logs:
```
[2020-03-19 14:54:28,603: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[7d59f67a-38e3-4566-9750-0907dabc414c]  
[2020-03-19 14:54:28,604: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fd307430b70> (args:('dojo.tasks.async_dupe_delete', '7d59f67a-38e3-4566-9750-0907dabc414c', {'retries': 0, 'shadow': None, 'eta': None, 'kwargs': {}, 'id': '7d59f67a-38e3-4566-9750-0907dabc414c', 'args': [datetime.timedelta(0, 60)], 'origin': 'gen1@*******-defectdojo-866bc549db-8btnw', 'hostname': 'celery@*******-defectdojo-866bc549db-8btnw', 'lang': 'py', 'delivery_info': {'priority': 0, 'exchange': '', 'redelivered': False, 'routing_key': 'celery'}, 'root_id': '7d59f67a-38e3-4566-9750-0907dabc414c', 'group': None, 'task': 'dojo.tasks.async_dupe_delete', 'kwargsrepr': '{}', 'parent_id': None, 'correlation_id': '7d59f67a-38e3-4566-9750-0907dabc414c', 'timelimit': [None, None], 'reply_to': '039573b5-1735-31be-8307-e94a2342eec1', 'expires': None, 'argsrepr': '[datetime.timedelta(0, 60)]'}, b'\x80\x02]q\x00cdatetime\ntimedelta\nq\x01K\x00K<K\x00\x87q\x02Rq\x03a}q\x04}q\x05(X\t\x00\x00\x00callbacksq\x06NX\x05\x00\x00\x00chordq\x07NX\x08\x00\x00\x00errbacksq\x08NX\x05\x00\x00\x00chainq\tNu\x87q\n.',... kwargs:{})
[2020-03-19 14:54:28,604: DEBUG/MainProcess] Task accepted: dojo.tasks.async_dupe_delete[7d59f67a-38e3-4566-9750-0907dabc414c] pid:1
[2020-03-19 14:54:28,604: INFO/MainProcess] dojo.tasks.async_dupe_delete[7d59f67a-38e3-4566-9750-0907dabc414c]: delete excess duplicates
[2020-03-19 14:54:28,699: ERROR/MainProcess] Task dojo.tasks.async_dupe_delete[7d59f67a-38e3-4566-9750-0907dabc414c] raised unexpected: ValueError('Cannot use None as a query value',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/dojo/tasks.py", line 301, in async_dupe_delete
    .filter(num_dupes__gt=dupe_max)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1207, in build_filter
    condition = self.build_lookup(lookups, reffed_expression, value)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1121, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
```

**Comment by barbich** [comment]
same for me with Master and Dev branch.
On the other hand the native .nessus format does work

**Comment by madchap** [comment]
On one of the latest `dev`, I actually get an error way earlier than that, like it can't process the opening of the file properly.

```
uwsgi_1         | 2020-04-07T14:37:05.600962862Z Traceback (most recent call last):
uwsgi_1         | 2020-04-07T14:37:05.600969745Z   File "./dojo/engagement/views.py", line 565, in import_scan_results
uwsgi_1         | 2020-04-07T14:37:05.600975330Z     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         | 2020-04-07T14:37:05.600980378Z   File "./dojo/tools/factory.py", line 94, in import_parser_factory
uwsgi_1         | 2020-04-07T14:37:05.600985262Z     parser = NessusCSVParser(file, test)
uwsgi_1         | 2020-04-07T14:37:05.600990927Z   File "./dojo/tools/nessus/parser.py", line 26, in __init__
uwsgi_1         | 2020-04-07T14:37:05.600996410Z     content = open(filename.temporary_file_path(), "rb").read().replace("\r", "\n")
uwsgi_1         | 2020-04-07T14:37:05.601001318Z TypeError: a bytes-like object is required, not 'str'
```

**Comment by xens** [comment]
Same error here still present on the latest ```dev``` commit.

```
  2 uwsgi_1         | a bytes-like object is required, not 'str'
  3 uwsgi_1         | Traceback (most recent call last):
  4 uwsgi_1         |   File "./dojo/engagement/views.py", line 584, in import_scan_results
  5 uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
  6 uwsgi_1         |   File "./dojo/tools/factory.py", line 97, in import_parser_factory
  7 uwsgi_1         |     parser = NessusCSVParser(file, test)
  8 uwsgi_1         |   File "./dojo/tools/nessus/parser.py", line 26, in __init__
  9 uwsgi_1         |     content = open(filename.temporary_file_path(), "rb").read().replace("\r", "\n")
 10 uwsgi_1         | TypeError: a bytes-like object is required, not 'str'
 11 uwsgi_1         | Error in parser: a bytes-like object is required, not 'str'
```
And there's no csv files in the samples folder (https://github.com/DefectDojo/sample-scan-files/tree/master/nessus) so I don't know since how long the CSV parser is broken.

**Comment by xens** [comment]
Fixed in https://github.com/DefectDojo/django-DefectDojo/pull/2283

**Comment by Applebois** [comment]
@dfirpaul  I am trying to reach you, can you send me an email ?
