### ISSUE TITLE
 column dojo_finding.is_Mitigated does not exist

### ISSUE THREAD

**Issue by ndeviprasad** [DefectDojo/django-DefectDojo#1790]
**Bug description**
As soon as a user login to the application with valid credentials application responds with the 500 error response code. This issue has been observed in all the functionality that are associated findings.

**Steps to reproduce**
1. Login with valid user and navigate to dashboard
https://defectdojo/dashboard
2. It results in 500 HTTP response code

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [X ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
- Kubernetes with external postgresql database.

**Console logs** (optional)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/finding/views.py", line 78, in open_findings
    request.GET, queryset=findings, user=request.user, pid=pid)
  File "./dojo/filters.py", line 375, in __init__
    for finding in self.queryset.distinct()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column dojo_finding.is_Mitigated does not exist
LINE 1: ..., "dojo_finding"."defect_review_requested_by_id", "dojo_find...

**Comment by valentijnscholten** [comment]
I think I have seen this also recently in one of my instances. I thought it was my mistake doing something wrong with migrations and/or sqldumps.

**Comment by ndeviprasad** [comment]
@valentijnscholten Please could you let me know how you fixed the issue?

**Comment by valentijnscholten** [comment]
I created the column manually.

**Comment by ndeviprasad** [comment]
I tried to create columns but the sql connectivity driver that I used has been case insensitive hence even after creating the column it was not resolved. Finally I had to use below steps from 
"Upgrade the database" section of  https://defectdojo.readthedocs.io/en/latest/upgrading.html to fix the issue:
./manage.py makemigrations
./manage.py migrate

Thanks @valentijnscholten  for promptly responding!
