### ISSUE TITLE
Can no longer change the admin password with manage.py

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1828]
```
I have no name!@b333b832f780:/app$ python3 manage.py changepassword
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/management/commands/changepassword.py", line 38, in handle
    username = getpass.getuser()
  File "/usr/local/lib/python3.5/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1001'
```

**Comment by dr3dd589** [comment]
I think this is due to the permission of `/app`  directory is set to root. If you open this container as root by specifying `-u root` then it will run. Same problem happening on uploading image normal user cannot make a directory in this folder that's why it gives permission error for creating image folder.

**Comment by Maffooch** [comment]
I've been doing this for every PR reviewed. A user parameter has to be specified as so 
``` python3 manage.py changepassword [username] ```
Maybe this is a new change since Django 2?
