### ISSUE TITLE
Installation error at Migration defectDojo_engagement_survey

### ISSUE THREAD

**Issue by mahirrudin** [DefectDojo/django-DefectDojo#2093]
**Bug description**
Installation defectdojo error at migration stage.

**Steps to reproduce**
1. Clone release 1.5.4.1 or dev or master
2. Activate virtualenv 
3. Install dependencies using `pip install -r requirements.txt `-->  **success**
4. Settings configuration on settings.py and .env.prod --> **success**
5. Check connection database using `python manage.py check` or  `python manage.py dbshell` --> **success**
6. Execute command `python manage.py makemigrations dojo` --> **error**

```enabling audit logging
Popen(['git', 'version'], cwd=/opt/dojo, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/opt/dojo, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/dojo/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/dojo/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/dojo/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/dojo/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/dojo/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/dojo/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 87, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/opt/dojo/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/dojo/lib/python3.8/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/opt/dojo/lib/python3.8/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/opt/dojo/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/dojo/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/dojo/lib/python3.8/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration defectDojo_engagement_survey.0001_initial dependencies reference nonexistent parent node ('dojo', '0001_initial')
```

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash
- [x] execute manual by following setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04 or Debian 10
 - DefectDojo Commit Message: 

**Additional context** (optional)
Already tried with python 3.5.9, 3.7, or 3.8

**Comment by valentijnscholten** [comment]
Best is to check the Dockerfile.django and nginx to see what is needed, or setup.bash.
You need to copy the files from dojo/db_migrations into dojo/migration

**Comment by mahirrudin** [comment]
> Best is to check the Dockerfile.django and nginx to see what is needed, or setup.bash.
> You need to copy the files from dojo/db_migrations into dojo/migration

nice, this is working now.

`mv dojo/db_migrations dojo/migrations`
