### ISSUE TITLE
Linux.sh line 409 - python3 manage.py collectstatic --noinput [OSError: [Errno 40] Too many levels of symbolic links]

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2161]
**Bug description**

OSError: [Errno 40] Too many levels of symbolic links: '/opt/dojo/django-DefectDojo/components/node_modules/@yarn_components/moment/meteor/moment.js'

Legacy installation using setup.bash
OS: Ubuntu 16.04 and 18.04 (I  tried on both)
Database: MySql.
Error on: Master, 1.5.4 and 1.5.4.1
Issue when running the last command in linux.sh script.

"python3 manage.py collectstatic --noinput"

Error Log:
----
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/dojo/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/dojo/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/dojo/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/dojo/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/dojo/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/opt/dojo/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/opt/dojo/lib/python3.5/site-packages/django/contrib/staticfiles/finders.py", line 131, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/opt/dojo/lib/python3.5/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files
    yield from get_files(storage, ignore_patterns, dir)
  File "/opt/dojo/lib/python3.5/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files
    yield from get_files(storage, ignore_patterns, dir)
  File "/opt/dojo/lib/python3.5/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
    directories, files = storage.listdir(location)
  File "/opt/dojo/lib/python3.5/site-packages/django/core/files/storage.py", line 316, in listdir
    if entry.is_dir():
OSError: [Errno 40] Too many levels of symbolic links: '/opt/dojo/django-DefectDojo/components/node_modules/@yarn_components/moment/meteor/moment.js'

**Steps to reproduce**
1. Run ./setup.bash
2. Wait for the last statement to execute and see that error.
3. I change the Nodejs version in (config-vars.sh) from 6 to 10. (due to OS warnings) (Last line in this file)
4. When executing the last statement from the linux.sh script I see error

**Comment by dayal18** [comment]
Solved: I removed the symbolic link using rm command at this directory:
'/opt/dojo/django-DefectDojo/components/node_modules/@yarn_components/moment/meteor/moment.js'
