### ISSUE TITLE
Static File Missing - Server Startup

### ISSUE THREAD

**Issue by Michael-Aguilera** [DefectDojo/django-DefectDojo#2209]
I have gone through the setup.bash from the 'dev' branch installation process and have attempted to start the server which then outputs this error which throws an error 500 web error:

```
python3 manage.py runserver

enabling audit logging
patching TagDescriptor
enabling audit logging
patching TagDescriptor
Watching for file changes with StatReloader
Performing system checks...

Popen(['git', 'version'], cwd=/opt/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/opt/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
System check identified no issues (0 silenced).
April 17, 2020 - 07:16:58
Django version 2.2.12, using settings 'dojo.settings.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/usr/local/lib/python3.6/dist-packages/whitenoise/base.py:116: UserWarning: No directory at: /opt/django-DefectDojo/static/
  warnings.warn(u"No directory at: {}".format(root))
[17/Apr/2020 07:17:05] "GET / HTTP/1.1" 302 0
Internal Server Error: /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "/opt/django-DefectDojo/dojo/context_processors.py", line 17, in bind_system_settings
    return {'system_settings': System_Settings.objects.get()}
  File "/opt/django-DefectDojo/dojo/models.py", line 109, in get
    return cache.get_or_set(self.CACHE_KEY, lambda: self.get_from_super(*args, **kwargs), timeout=30)
  File "/usr/local/lib/python3.6/dist-packages/django/core/cache/backends/base.py", line 167, in get_or_set
    default = default()
  File "/opt/django-DefectDojo/dojo/models.py", line 109, in <lambda>
    return cache.get_or_set(self.CACHE_KEY, lambda: self.get_from_super(*args, **kwargs), timeout=30)
  File "/opt/django-DefectDojo/dojo/models.py", line 102, in get_from_super
    return super(SystemSettingsManager, self).get(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
dojo.models.System_Settings.DoesNotExist: System_Settings matching query does not exist.
[17/Apr/2020 07:17:07] "GET /login?next=/ HTTP/1.1" 500 27
[17/Apr/2020 07:17:07] "GET /favicon.ico HTTP/1.1" 302 0
```

**Comment by Michael-Aguilera** [comment]
Steps to mitigate:
Store repository at /opt/django-DefectDojo

run /opt/django-DefectDojo/setup/setup.bash (this will create a new file located at /opt/dojo)

once setup is completed (I used default option '1'), copy /opt/django-DefectDojo to /opt/dojo/django-DefectDojo.

I removed the MySQL database and reran the setup.bash and that seemed to fix everything for me.
