### ISSUE TITLE
Creating finding via APIv2 requires to set up "duplicate" flag by creator instead of using system deduplication

### ISSUE THREAD

**Issue by AlexanderTyutin** [DefectDojo/django-DefectDojo#2222]
When I'm creating finding via APIv2 and not setting the field "duplicate", the server returns error 500.

Logs:

```
Internal Server Error: /api/v2/findings/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "./dojo/api_v2/serializers.py", line 462, in validate
    if ((data['active'] or data['verified']) and data['duplicate']):
KeyError: 'duplicate'
```

So, using APIv2 to create findings requires user to decide is the finding duplicate or not before actual finding creation. And system-wide deduplication can't be used in this case.

**Comment by valentijnscholten** [comment]
Just set it to false, the system will set it to true if it detects a duplicate later. Sure the code can be improved, but the idea is that findings are import using import or reimport.
Have you tried using the generic csv importer?

**Comment by AlexanderTyutin** [comment]
Didn't try. Am I right that you are speaking about this?

![image](https://user-images.githubusercontent.com/49285004/79780283-5678e600-8344-11ea-9e17-13e27a9ee223.png)

Are there any requirements for columns (count, order, format, etc)?

**Comment by valentijnscholten** [comment]
yes, or via apiv2.
