### ISSUE TITLE
Error While Setup.bash in latest dev build

### ISSUE THREAD

**Issue by zfirered** [DefectDojo/django-DefectDojo#2232]
Finished setup but when try to run manage.py come this error

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/xchop3r16/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/xchop3r16/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/xchop3r16/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/xchop3r16/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/xchop3r16/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xchop3r16/Documents/django-DefectDojo-dev/dojo/settings/settings.py", line 5, in <module>
    import environ
  File "/home/xchop3r16/.local/lib/python3.6/site-packages/environ.py", line 114
    raise ValueError, "No frame marked with %s." % fname
                    ^
SyntaxError: invalid syntax

![image](https://user-images.githubusercontent.com/17750324/79879552-0b7cd280-8419-11ea-9358-94a4050f3baa.png)

**Comment by 37b** [comment]
@valentijnscholten  posted this in Slack which helped me https://stackoverflow.com/questions/40226817/syntax-error-django1-10-1-when-doing-py-3-5-manage-py-runserver
