### ISSUE TITLE
JIRA issues get created twice

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2257]
**Bug description**
FYI @Apipia 

On a production system with no changes, and after updating to the latest `dev` today, my JIRAs get created twice.

We can see in the trace at the bottom that `Trying to create a new JIRA issue` appears twice.

The most blatant log is when it tries to create the second jira and the unique key constraint fails on the DB:

```
celeryworker_1  | [2020-04-24 09:52:09,709: ERROR/MainProcess] Task add_issue_task[71fe9c12-0d1d-4ad4-8d4f-61dc9c7a6dce] raised unexpected: IntegrityError(1062, "Duplicate entry '62002' for key 'finding_id'")
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celeryworker_1  |     return self.cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django_prometheus/db/common.py", line 68, in execute
celeryworker_1  |     return super(CursorWrapper, self).execute(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
celeryworker_1  |     return self.cursor.execute(query, args)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
celeryworker_1  |     res = self._query(query)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 315, in _query
celeryworker_1  |     db.query(q)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 239, in query
celeryworker_1  |     _mysql.connection.query(self, query)
celeryworker_1  | MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '62002' for key 'finding_id'")
celeryworker_1  | 
celeryworker_1  | The above exception was the direct cause of the following exception:
celeryworker_1  | 
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 269, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
celeryworker_1  |   File "/app/dojo/utils.py", line 1379, in add_issue
celeryworker_1  |     j_issue.save()
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
celeryworker_1  |     force_update=force_update, update_fields=update_fields)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
celeryworker_1  |     force_update, using, update_fields,
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
celeryworker_1  |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
celeryworker_1  |     using=using, raw=raw)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
celeryworker_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
celeryworker_1  |     return query.get_compiler(using=using).execute_sql(return_id)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
celeryworker_1  |     cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
celeryworker_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
celeryworker_1  |     return executor(sql, params, many, context)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celeryworker_1  |     return self.cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
celeryworker_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celeryworker_1  |     return self.cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django_prometheus/db/common.py", line 68, in execute
celeryworker_1  |     return super(CursorWrapper, self).execute(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
celeryworker_1  |     return self.cursor.execute(query, args)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
celeryworker_1  |     res = self._query(query)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 315, in _query
celeryworker_1  |     db.query(q)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 239, in query
celeryworker_1  |     _mysql.connection.query(self, query)
celeryworker_1  | django.db.utils.IntegrityError: (1062, "Duplicate entry '62002' for key 'finding_id'")
``` 

**Steps to reproduce**
1. Product is setup for JIRA. No checkboxes tick (issues are manually pushed)
2. Go to a finding and edit it
3. Click the "push to jira" button to create the issue in JIRA
4. 2 issues get created in JIRA, but the first one is the one that sticks, given the stacktrace above.

**Expected behavior**
Only one issue gets created.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]

`064908cf: Merge remote-tracking branch 'refs/remotes/origin/dev' into dev [2020-04-24 08:06:22 +0000]`

Raw output from my `docker-compose logs` during the problem:

```
celeryworker_1  | Trying to create a new JIRA issue
uwsgi_1         | applying rules
uwsgi_1         | [pid: 18|app: 0|req: 1811/2252] 172.18.64.94 () {64 vars in 1980 bytes} [Fri Apr 24 09:52:00 2020] POST /finding/62002/edit => generated 0 bytes in 162 msecs (HTTP/1.1 302) 8 headers in 404 bytes (1 switches on core 1)
nginx_1         | 172.18.64.94 - - [24/Apr/2020:09:52:00 +0000] "POST /finding/62002/edit HTTP/1.1" 302 0 "https://defectdojo.cloudbees.com/finding/62002/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36" "-"
uwsgi_1         | [pid: 18|app: 0|req: 1813/2253] 172.18.64.94 () {54 vars in 1767 bytes} [Fri Apr 24 09:52:01 2020] GET /alerts/count => generated 14 bytes in 35 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
nginx_1         | 172.18.64.94 - - [24/Apr/2020:09:52:01 +0000] "GET /alerts/count HTTP/1.1" 200 14 "https://defectdojo.cloudbees.com/finding/62002/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36" "-"
uwsgi_1         | Successfully imported extension module "markdown.extensions.nl2br".
uwsgi_1         | Successfully loaded extension "markdown.extensions.nl2br.Nl2BrExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.sane_lists".
uwsgi_1         | Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.codehilite".
uwsgi_1         | Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.fenced_code".
uwsgi_1         | Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.toc".
uwsgi_1         | Successfully loaded extension "markdown.extensions.toc.TocExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.tables".
uwsgi_1         | Successfully loaded extension "markdown.extensions.tables.TableExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.nl2br".
uwsgi_1         | Successfully loaded extension "markdown.extensions.nl2br.Nl2BrExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.sane_lists".
uwsgi_1         | Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.codehilite".
uwsgi_1         | Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.fenced_code".
uwsgi_1         | Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.toc".
uwsgi_1         | Successfully loaded extension "markdown.extensions.toc.TocExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.tables".
uwsgi_1         | Successfully loaded extension "markdown.extensions.tables.TableExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.nl2br".
uwsgi_1         | Successfully loaded extension "markdown.extensions.nl2br.Nl2BrExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.sane_lists".
uwsgi_1         | Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.codehilite".
uwsgi_1         | Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.fenced_code".
uwsgi_1         | Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.toc".
uwsgi_1         | Successfully loaded extension "markdown.extensions.toc.TocExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.tables".
uwsgi_1         | Successfully loaded extension "markdown.extensions.tables.TableExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.nl2br".
uwsgi_1         | Successfully loaded extension "markdown.extensions.nl2br.Nl2BrExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.sane_lists".
uwsgi_1         | Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.codehilite".
uwsgi_1         | Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.fenced_code".
uwsgi_1         | Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.toc".
uwsgi_1         | Successfully loaded extension "markdown.extensions.toc.TocExtension".
uwsgi_1         | Successfully imported extension module "markdown.extensions.tables".
uwsgi_1         | Successfully loaded extension "markdown.extensions.tables.TableExtension".
uwsgi_1         | Popen(['git', 'cat-file', '--batch-check'], cwd=/app, universal_newlines=False, shell=None, istream=<valid stream>)
uwsgi_1         | [pid: 18|app: 0|req: 1813/2254] 172.18.64.94 () {58 vars in 1949 bytes} [Fri Apr 24 09:52:00 2020] GET /finding/62002 => generated 74571 bytes in 1521 msecs (HTTP/1.1 200) 8 headers in 453 bytes (1 switches on core 0)
nginx_1         | 172.18.64.94 - - [24/Apr/2020:09:52:02 +0000] "GET /finding/62002 HTTP/1.1" 200 74571 "https://defectdojo.cloudbees.com/finding/62002/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36" "-"
uwsgi_1         | [pid: 18|app: 0|req: 1814/2255] 172.18.64.94 () {54 vars in 1619 bytes} [Fri Apr 24 09:52:05 2020] GET /alerts/count => generated 14 bytes in 18 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
nginx_1         | 172.18.64.94 - - [24/Apr/2020:09:52:05 +0000] "GET /alerts/count HTTP/1.1" 200 14 "https://defectdojo.cloudbees.com/finding/62002" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36" "-"
nginx_1         | 172.18.64.157 - - [24/Apr/2020:09:52:05 +0000] "GET / HTTP/1.1" 302 0 "-" "Datadog Agent/0.0.0" "-"
uwsgi_1         | [pid: 15|app: 0|req: 442/2256] 172.18.64.157 () {40 vars in 533 bytes} [Fri Apr 24 09:52:05 2020] GET / => generated 0 bytes in 2 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 1)
celeryworker_1  | [2020-04-24 09:52:07,840: INFO/MainProcess] Task add_issue_task[4133ed17-3289-44ee-9507-e67361fd41f8] succeeded in 7.508165678940713s: None
celeryworker_1  | [2020-04-24 09:52:07,844: INFO/MainProcess] Received task: async_dedupe[1a03fd55-8c2b-46c9-8ff7-27a7799d76bb]  
celeryworker_1  | [2020-04-24 09:52:07,934: INFO/MainProcess] Task async_dedupe[1a03fd55-8c2b-46c9-8ff7-27a7799d76bb] succeeded in 0.08920459891669452s: None
celeryworker_1  | [2020-04-24 09:52:07,938: INFO/MainProcess] Received task: add_issue_task[71fe9c12-0d1d-4ad4-8d4f-61dc9c7a6dce]  
celeryworker_1  | [2020-04-24 09:52:07,939: INFO/MainProcess] add_issue_task[71fe9c12-0d1d-4ad4-8d4f-61dc9c7a6dce]: add issue task
celeryworker_1  | Trying to create a new JIRA issue
uwsgi_1         | [pid: 15|app: 0|req: 443/2257] 172.18.64.94 () {54 vars in 1628 bytes} [Fri Apr 24 09:52:08 2020] GET /alerts/count => generated 14 bytes in 37 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
nginx_1         | 172.18.64.94 - - [24/Apr/2020:09:52:08 +0000] "GET /alerts/count HTTP/1.1" 200 14 "https://defectdojo.cloudbees.com/product/19/engagements" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36" "-"
celeryworker_1  | [2020-04-24 09:52:09,709: ERROR/MainProcess] Task add_issue_task[71fe9c12-0d1d-4ad4-8d4f-61dc9c7a6dce] raised unexpected: IntegrityError(1062, "Duplicate entry '62002' for key 'finding_id'")
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celeryworker_1  |     return self.cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django_prometheus/db/common.py", line 68, in execute
celeryworker_1  |     return super(CursorWrapper, self).execute(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
celeryworker_1  |     return self.cursor.execute(query, args)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
celeryworker_1  |     res = self._query(query)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 315, in _query
celeryworker_1  |     db.query(q)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 239, in query
celeryworker_1  |     _mysql.connection.query(self, query)
celeryworker_1  | MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '62002' for key 'finding_id'")
celeryworker_1  | 
celeryworker_1  | The above exception was the direct cause of the following exception:
celeryworker_1  | 
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 269, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
celeryworker_1  |   File "/app/dojo/utils.py", line 1379, in add_issue
celeryworker_1  |     j_issue.save()
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
celeryworker_1  |     force_update=force_update, update_fields=update_fields)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
celeryworker_1  |     force_update, using, update_fields,
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
celeryworker_1  |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
celeryworker_1  |     using=using, raw=raw)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
celeryworker_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
celeryworker_1  |     return query.get_compiler(using=using).execute_sql(return_id)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
celeryworker_1  |     cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
celeryworker_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
celeryworker_1  |     return executor(sql, params, many, context)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celeryworker_1  |     return self.cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
celeryworker_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celeryworker_1  |     return self.cursor.execute(sql, params)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django_prometheus/db/common.py", line 68, in execute
celeryworker_1  |     return super(CursorWrapper, self).execute(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
celeryworker_1  |     return self.cursor.execute(query, args)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
celeryworker_1  |     res = self._query(query)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 315, in _query
celeryworker_1  |     db.query(q)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 239, in query
celeryworker_1  |     _mysql.connection.query(self, query)
celeryworker_1  | django.db.utils.IntegrityError: (1062, "Duplicate entry '62002' for key 'finding_id'")
```

**Comment by madchap** [comment]
And along the way got another one, weird. Surely unrelated.

```
0-5bb1-4e90-88c6-d5429c054cf4] raised unexpected: TypeError("Can't convert 'NoneType' object to str implicitly",)
celeryworker_1  | 2020-04-24T10:28:46.789614525Z Traceback (most recent call last):
celeryworker_1  | 2020-04-24T10:28:46.789618441Z   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  | 2020-04-24T10:28:46.789621840Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2020-04-24T10:28:46.789624693Z   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  | 2020-04-24T10:28:46.789627685Z     return self.run(*args, **kwargs)
celeryworker_1  | 2020-04-24T10:28:46.789630404Z   File "/app/dojo/tasks.py", line 269, in add_issue_task
celeryworker_1  | 2020-04-24T10:28:46.789633695Z     add_issue(find, push_to_jira)
celeryworker_1  | 2020-04-24T10:28:46.789640900Z   File "/app/dojo/utils.py", line 1372, in add_issue
celeryworker_1  | 2020-04-24T10:28:46.789646471Z     jira_conf.finding_text),
celeryworker_1  | 2020-04-24T10:28:46.789651504Z   File "/app/dojo/utils.py", line 1288, in jira_long_description
celeryworker_1  | 2020-04-24T10:28:46.789654437Z     find_id) + "\n\n" + jira_conf_finding_text
```

**Comment by madchap** [comment]
So, it happens a first time at

https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/finding/views.py#L1135

then right after that at

https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/models.py#L1861

**Comment by madchap** [comment]
Unsure what to do here @Apipia .

Maybe until we decide to fully clean the implementation of "issue tracker", we should just remove the models.py if statement and let is be in the views.py. I will create a PR in that sense to apply immediately on my prod instance.
