### ISSUE TITLE
GitHub integration failures

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2335]
**Bug description**

fyi @mestrade

```
celeryworker_1  | [2020-05-05 13:32:12,547: INFO/MainProcess] Received task: add_external_issue_task[f59186cc-f6d3-4dcb-a20d-16fe6c0c3db8]                                    
celeryworker_1  | [2020-05-05 13:32:12,550: INFO/MainProcess] add_external_issue_task[f59186cc-f6d3-4dcb-a20d-16fe6c0c3db8]: add external issue task                          
celeryworker_1  | adding external issue with provider: github                          
celeryworker_1  | [2020-05-05 13:32:12,573: ERROR/MainProcess] Task add_external_issue_task[f59186cc-f6d3-4dcb-a20d-16fe6c0c3db8] raised unexpected: AttributeError("'GITHUB_PKey' object has no attribute 'conf'",)
celeryworker_1  | Traceback (most recent call last):                                   
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task                                                                
celeryworker_1  |     R = retval = fun(*args, **kwargs)                                
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__                                                        
celeryworker_1  |     return self.run(*args, **kwargs)                                 
celeryworker_1  |   File "/app/dojo/tasks.py", line 245, in add_external_issue_task                                                                                           
celeryworker_1  |     add_external_issue(find, external_issue_provider)                
celeryworker_1  |   File "/app/dojo/utils.py", line 1304, in add_external_issue                                                                                               
celeryworker_1  |     add_external_issue_github(find, prod, eng)                       
celeryworker_1  |   File "/app/dojo/github.py", line 88, in add_external_issue_github                                                                                         
celeryworker_1  |     github_conf = github_pkey.conf                                   
celeryworker_1  | AttributeError: 'GITHUB_PKey' object has no attribute 'conf'  
```

**Steps to reproduce**
1. Enable Github in system settings
2. Not even sure if you need to configure anything, but many errors would pop out.

**Comment by madchap** [comment]
Needs to be fixed for 1.6.0 GA
