### ISSUE TITLE
Notifications stacktrace after import

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2370]
**Bug description**
Clean local dev instance, using my import script at https://github.com/madchap/dojo-helpers/blob/master/import_initial_data.py , I am getting this after the import finishes.

Using the `admin` user with no profile modifications and notifications settings are the default out-of-the-box.

```
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | alert
celeryworker_1  | [2020-05-16 12:15:58,672: INFO/MainProcess] Received task: send_alert_notification[fe8198e2-6915-411e-b981-45efdbf800ef]  
celeryworker_1  | [2020-05-16 12:15:58,677: INFO/MainProcess] Task send_alert_notification[fe8198e2-6915-411e-b981-45efdbf800ef] succeeded in 0.004426948959007859s: None
uwsgi_1         | Internal Server Error: /api/v2/import-scan/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1         |     return view_func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/viewsets.py", line 114, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 505, in dispatch
uwsgi_1         |     response = self.handle_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 465, in handle_exception
uwsgi_1         |     self.raise_uncaught_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
uwsgi_1         |     raise exc
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 502, in dispatch
uwsgi_1         |     response = handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 19, in create
uwsgi_1         |     self.perform_create(serializer)
uwsgi_1         |   File "./dojo/api_v2/views.py", line 669, in perform_create
uwsgi_1         |     serializer.save(push_to_jira=push_to_jira)
uwsgi_1         |   File "./dojo/api_v2/serializers.py", line 749, in save
uwsgi_1         |     url=reverse('view_test', args=(test.id,)))
uwsgi_1         |   File "./dojo/notifications/helper.py", line 20, in create_notification
uwsgi_1         |     process_notifications(event, system_notifications, *args, **kwargs)
uwsgi_1         |   File "./dojo/notifications/helper.py", line 88, in process_notifications
nginx_1         | 172.30.0.1 - - [16/May/2020:12:15:58 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 500 23588 "-" "python-requests/2.23.0" "-"
uwsgi_1         |     sync = 'initiator' in kwargs and kwargs['initiator'].usercontactinfo and kwargs['initiator'].usercontactinfo.block_execution
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
uwsgi_1         |     self.related.get_accessor_name()
uwsgi_1         | django.contrib.auth.models.User.usercontactinfo.RelatedObjectDoesNotExist: User has no usercontactinfo.
uwsgi_1         | Internal Server Error: /api/v2/import-scan/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1         |     return view_func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/viewsets.py", line 114, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 505, in dispatch
uwsgi_1         |     response = self.handle_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 465, in handle_exception
uwsgi_1         |     self.raise_uncaught_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
uwsgi_1         |     raise exc
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 502, in dispatch
uwsgi_1         |     response = handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 19, in create
uwsgi_1         |     self.perform_create(serializer)
uwsgi_1         |   File "./dojo/api_v2/views.py", line 669, in perform_create
uwsgi_1         |     serializer.save(push_to_jira=push_to_jira)
uwsgi_1         |   File "./dojo/api_v2/serializers.py", line 749, in save
uwsgi_1         |     url=reverse('view_test', args=(test.id,)))
uwsgi_1         |   File "./dojo/notifications/helper.py", line 20, in create_notification
uwsgi_1         |     process_notifications(event, system_notifications, *args, **kwargs)
uwsgi_1         |   File "./dojo/notifications/helper.py", line 88, in process_notifications
uwsgi_1         |     sync = 'initiator' in kwargs and kwargs['initiator'].usercontactinfo and kwargs['initiator'].usercontactinfo.block_execution
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
uwsgi_1         |     self.related.get_accessor_name()
uwsgi_1         | django.contrib.auth.models.User.usercontactinfo.RelatedObjectDoesNotExist: User has no usercontactinfo.
```

fyi @valentijnscholten

**Comment by valentijnscholten** [comment]
Looks like somebody is creating users outside the official DD interface ;-)

As you can see in the code I tried to cater for this situation and I thought I tested this.
But I guess I'll never get used to this python/django concept of using exceptions for flow control. Look at how ugly the code gets! Anyway, I left some debug logging in place.

#2373

**Comment by madchap** [comment]
No, not even in that instance! It was a naked dev... Normally.

**Comment by valentijnscholten** [comment]
Clean as in no data at all, just the admin user created by the initializer?

**Comment by madchap** [comment]
Yes, then running my import script. I can try again Monday if you want, may not have the chance before then.

**Comment by madchap** [comment]
Or maybe did I have the google social stuff done configured? But I was using the admin user.

**Comment by madchap** [comment]
![image](https://user-images.githubusercontent.com/5468769/82129971-51824780-97c7-11ea-9c92-d7962bd30f26.png)

**Comment by valentijnscholten** [comment]
It's already fixed in the pr
