### ISSUE TITLE
Apply finding template raises javascript / 404 error

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2371]
When JIRA is enabled, the integration test for applying a template to a finding is failing with a javascript error:

```
Clicking on the template 
{'timestamp': 1589619218090, 'level': 'SEVERE', 'message': 'http://localhost:8080/static/bootstrap/dist/js/bootstrap.js 1800 Failed to load resource: the server responded with a status of 404 (Not Found)', 'source': 'network'}
There was a SEVERE javascript error in the console, please check all steps fromt the current test to see where it happens
Currently there is no way to find out at which url the error happened.
FAIL
======================================================================
FAIL: test_apply_template_to_a_finding (__main__.FindingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/Finding_unit_test.py", line 229, in test_apply_template_to_a_finding
    self.assertNoConsoleErrors()
  File "/home/travis/build/DefectDojo/django-DefectDojo/tests/base_test_class.py", line 208, in assertNoConsoleErrors
    self.assertNotEqual(entry['level'], 'SEVERE')
AssertionError: 'SEVERE' == 'SEVERE'
```

Bootstrap is trying to load a resources, but the server returns a 404 I haven't dived into it yet, but it doesn't happen on my own instance. Maybe if I used the same data as the integration tests test data.

For now we only run this specific integration test with JIRA turned off to not block any progress on the dev branch.

**Comment by valentijnscholten** [comment]
solved by #2403
