### ISSUE TITLE
Surveys migration script - DEV branch

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2417]
**Bug description**
When running the command "python3 manage.py migrate_surveys", it says table not found.

**Steps to reproduce**
1. Go to 'DEV branch'
2. Click on 'Click on questionnaires, then a message will pop-up saying to run the migration command'
3. Go to Server 'run python3 manage.py migrate_surveys'

**Expected behavior**
The migration script should complete and show as successfully completed.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo Commit Message: (DEV)  Commit ID: 414e10fd8b7aa51a27edfdce8a02ad3a512fe45c

**Console logs** (optional)

---------------------------------------------------
(dojo) root@ip-x-x-x-x:/opt/dojo/django-DefectDojo# python3 manage.py migrate_surveys
enabling audit logging
patching TagDescriptor
Popen(['git', 'version'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'dojodb.defectDojo_engagement_survey_question' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/dojo/django-DefectDojo/dojo/management/commands/migrate_surveys.py", line 52, in handle
    cursor.execute(str(copy_string))
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'dojodb.defectDojo_engagement_survey_question' doesn't exist")
-----------------------------------------------------------

**Comment by valentijnscholten** [comment]
I think you should run the normal django migrations first: `manage.py migrate`. You may first have to manually copy the files from `dojo/db_migrations` into `dojo/migrations`

**Comment by dayal18** [comment]
I did a fresh installation I guess the migrate.py is part of setup.bash, anyways I'll give it a shot again today and make sure to copy the db_migrations to migrations. Will update you.

**Comment by dayal18** [comment]
Same thing, fresh installation --
Dev branch (this doesn't have the **dojo/migrations** folder) I copied the **dojo/db_migrations to dojo/migrations**.
I run the makemigrations, and here is the output:


(dojo) root@ip-10-40-133-49:/opt/dojo/django-DefectDojo# python3 manage.py makemigrations
_enabling audit logging
patching TagDescriptor
Popen(['git', 'version'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
No changes detected_

(dojo) root@ip-10-40-133-49:/opt/dojo/django-DefectDojo# python3 manage.py migrate_surveys
_enabling audit logging
patching TagDescriptor
Popen(['git', 'version'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'dojodb.defectDojo_engagement_survey_question' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/dojo/django-DefectDojo/dojo/management/commands/migrate_surveys.py", line 52, in handle
    cursor.execute(str(copy_string))
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/dojo/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'dojodb.defectDojo_engagement_survey_question' doesn't exist")_

**Comment by fabaff** [comment]
This issue seems still be present.

As suggested:

```
$ docker exec -it django-defectdojo_uwsgi_1 ./manage.py migrate
[08/Dec/2021 10:59:55] INFO [dojo.models:3623] enabling audit logging
Operations to perform:
  Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, django_celery_results, sessions, sites, social_django, tagging, watson
Running migrations:
  No migrations to apply.
```
Then

```bash
$ docker exec -it django-defectdojo_uwsgi_1 ./manage.py migrate_surveys
[08/Dec/2021 11:00:08] INFO [dojo.models:3623] enabling audit logging
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'defectdojo.defectDojo_engagement_survey_question' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/dojo/management/commands/migrate_surveys.py", line 52, in handle
    cursor.execute(str(copy_string))
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'defectdojo.defectDojo_engagement_survey_question' doesn't exist")
```

**Comment by valentijnscholten** [comment]
@adayrodri you're issue seems different, can you create a new one?
