### ISSUE TITLE
Exception during slack notification

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2432]
**Bug description**
```
celeryworker_1  | During handling of the above exception, another exception occurred:
celeryworker_1  | 
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 385, in send_alert_notification_task
celeryworker_1  |     send_alert_notification(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 221, in send_alert_notification
celeryworker_1  |     description=create_notification_message(event, user, 'alert', *args, **kwargs),
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 75, in create_notification_message
celeryworker_1  |     create_description(event)
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 59, in create_description
celeryworker_1  |     kwargs["description"] = "Product " + kwargs['title'] + " has been created successfully."
celeryworker_1  | KeyError: 'title'
celeryworker_1  | [2020-05-28 08:30:07,389: INFO/MainProcess] Received task: send_alert_notification[613cf480-3730-43fa-ad82-5023021f9427]  
celeryworker_1  | notifications/product_added.tpl
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 72, in create_notification_message
celeryworker_1  |     notification = render_to_string(template, kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
celeryworker_1  |     template = get_template(template_name, using=using)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 19, in get_template
celeryworker_1  |     raise TemplateDoesNotExist(template_name, chain=chain)
celeryworker_1  | django.template.exceptions.TemplateDoesNotExist: notifications/product_added.tpl
celeryworker_1  | [2020-05-28 08:30:07,393: ERROR/MainProcess] Task send_alert_notification[613cf480-3730-43fa-ad82-5023021f9427] raised unexpected: KeyError('title',)
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 72, in create_notification_message
celeryworker_1  |     notification = render_to_string(template, kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
celeryworker_1  |     template = get_template(template_name, using=using)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 19, in get_template
celeryworker_1  |     raise TemplateDoesNotExist(template_name, chain=chain)
celeryworker_1  | django.template.exceptions.TemplateDoesNotExist: notifications/product_added.tpl
```

```
celeryworker_1  | 
celeryworker_1  | During handling of the above exception, another exception occurred:
celeryworker_1  | 
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 385, in send_alert_notification_task
celeryworker_1  |     send_alert_notification(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 221, in send_alert_notification
celeryworker_1  |     description=create_notification_message(event, user, 'alert', *args, **kwargs),
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 75, in create_notification_message
celeryworker_1  |     create_description(event)
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 59, in create_description
celeryworker_1  |     kwargs["description"] = "Product " + kwargs['title'] + " has been created successfully."
celeryworker_1  | KeyError: 'title'

```

**Comment by valentijnscholten** [comment]
I think this is solved by #2412 by passing *args and *kwargs to create_description

**Comment by madchap** [comment]
> I think this is solved by #2412 by passing *args and *kwargs to create_description.

It does not, just applied the PR, same outcome.

**Comment by valentijnscholten** [comment]
Do you have the stacktrace? Helps if I have the exact line numbers. You are creating the product via the UI?

**Comment by madchap** [comment]
Stacktrace at https://gist.github.com/64a2b9644a8db071d928d0458fa034d2

I am creating the product via the UI.

**Comment by madchap** [comment]
Updated my prod to `dev` and included the PR manually.

I get this:

```
Received task: send_slack_notification[0385d777-da0c-4ebc-8088-73d3fcb6126b]  
celeryworker_1  | 'members'
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 135, in send_slack_notification
celeryworker_1  |     user.usercontactinfo.slack_username)
celeryworker_1  |   File "/app/dojo/utils.py", line 1791, in get_slack_user_id
celeryworker_1  |     for member in users["members"]:
celeryworker_1  | KeyError: 'members'
```

Have not looked yet.

**Comment by valentijnscholten** [comment]
That code hasn't been changed in 2 years. It only gets triggered if a users slack handle hasn't been put in their profile yet, so might be a work around to put them in manually.

**Comment by madchap** [comment]
Got it.

Working on an enhancement PR for slack, including doc..

**Comment by madchap** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/2486
