### ISSUE TITLE
Questionnaire/Survey Delete - Server Error 500 - Master branch

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2446]
**Bug description**
When trying to delete an existing survey/questionnaire getting Server Error 500.
My existing questionnaire has a Text box, a question on radio button, and a question with multiple choices.

**Steps to reproduce**
1. Go to 'Questionnaire / Survey, create new if required'
2. Click on 'Select the questionnaire and select the delete questionnaire'
3. See error 'Server Error 500'

**Expected behavior**
The questionnaire should get deleted.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo Commit Message: Master Branch

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/43857391/83318051-ebe68000-a1f6-11ea-84d0-fab36fbf3692.png)

**Console logs** (optional)
Popen(['git', 'cat-file', '--batch-check'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=<valid stream>)
[pid: 13401|app: 0|req: 16/92] 10.44.0.31 () {54 vars in 1069 bytes} [Fri May 29 22:42:27 2020] GET /survey/10/edit => generated 25343 bytes in 32 msecs (HTTP/1.1 200) 8 headers in 514 bytes (1 switches on core 0)
Internal Server Error: /survey/10/delete
Traceback (most recent call last):
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/defectDojo_engagement_survey/views.py", line 289, in delete_survey
    collector.collect([survey])
  File "/opt/dojo/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 181, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/deletion.py", line 16, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/opt/dojo/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 181, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/deletion.py", line 16, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/opt/dojo/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 181, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/deletion.py", line 220, in collect
    sub_objs = self.related_objects(related, batch)
  File "/opt/dojo/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 186, in related_objects
    qs = super().related_objects(related, objs)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/deletion.py", line 236, in related_objects
    **{"%s__in" % related.field.name: objs}
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1224, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1087, in check_related_objects
    self.check_query_object_type(v, opts, field)
  File "/opt/dojo/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1067, in check_query_object_type
    (value, opts.object_name))
ValueError: Cannot query "TextAnswer object (5)": Must be "ChoiceAnswer" instance.
[pid: 13409|app: 0|req: 9/93] 10.44.0.31 () {54 vars in 1081 bytes} [Fri May 29 22:42:29 2020] GET /survey/10/delete => generated 27 bytes in 98 msecs (HTTP/1.1 500) 6 headers in 192 bytes (1 switches on core 0)
Popen(['git', 'cat-file', '--batch-check'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=<valid stream>)

**Comment by dayal18** [comment]
I wen to admin dashboard and have deleted all the questions, choices, answers, and engagements from there. I have to delete each question at a time to resolve this issue.

**Comment by dayal18** [comment]
Fixed in later versions.
