### ISSUE TITLE
[k8s] Celery worker is crashing

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#2520]
I had to rebuild my docker images, and after that I'm not able run celery worker properly, it gives me:

I was using Dockerfile. django to produce image, is there something that i've missed:

`Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 419, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 309, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 393, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 81, in run
    self.start_scheduler()
  File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 92, in start_scheduler
    platforms.create_pidlock(self.pidfile)
  File "/usr/local/lib/python3.5/site-packages/celery/platforms.py", line 258, in create_pidlock
    pidlock = _create_pidlock(pidfile)
  File "/usr/local/lib/python3.5/site-packages/celery/platforms.py", line 268, in _create_pidlock
    pidlock.acquire()
  File "/usr/local/lib/python3.5/site-packages/celery/platforms.py", line 151, in acquire
    reraise(LockFailed, LockFailed(str(exc)), sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/celery/platforms.py", line 149, in acquire
    self.write_pid()
  File "/usr/local/lib/python3.5/site-packages/celery/platforms.py", line 216, in write_pid
    pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
celery.platforms.LockFailed: [Errno 13] Permission denied: '/run/celery-beat.pid'
`

**Comment by dsever** [comment]
Looks like Project Kaniko has some issues and doesn't respect defined permissions, so i rebuild images on standard docker and everything seem ok
