### ISSUE TITLE
Burp suite scan report that contains huge requests or responses cannot be imported.

### ISSUE THREAD

**Issue by manjukju** [DefectDojo/django-DefectDojo#2524]
**Bug description**
I tried importing a scan report generated using Burp Suite Professional into Defect Dojo.
This failed and an error message "Server Error (500)" was displayed.
A few of the responses (base64-encoded) in the report that I was trying to import were as big as 12654800 bytes.

**Steps to reproduce**
1. Select issues in Burp Suite and export them to an XML report, Base64-encoding the requests and responses.
2. Go to an Engagement and select "Import Scan Results".
3. Select scan type "Burp Scan", specify the Burp scan XML report.
4. Click "Upload File" to import the report.

**Expected behavior**
Burp scan report should be imported successfully.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: SUSE Linux Enterprise Server 15
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]
d8cd7607: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.
Internal Server Error: /engagement/36/import_scan_results

Traceback (most recent call last):
  File "./dojo/tools/burp/parser.py", line 63, in parse_xml
    tree = etree.parse(xml_file, etree.XMLParser(resolve_entities=False))
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1861, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1881, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1776, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "/app/BurpScan.xml", line 747
lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 747, column 9988391

**Additional context** (optional)

Console logs had a traceback with the following exception.
lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 747, column 9988391

So, I modified the file https://github.com/DefectDojo/django-DefectDojo/blob/5c561d70286d09bc6a84448e71cc8ebf7547d9e2/dojo/tools/burp/parser.py#L63 to create a parser with huge_tree=True.

tree = etree.parse(xml_file, etree.XMLParser(resolve_entities=False, huge_tree=True))

I tried importing the scan report again with this change in place.
But, the import failed with a different exception:

Internal Server Error: /engagement/42/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args) 
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

**Comment by ixnet** [comment]
Hi guys!
Could you please fix that, I have a small project's scan and even it cannot be imported due to this bug.
The fix it's not that hard to do I assume. **https://stackoverflow.com/questions/14163429/python-and-django-operationalerror-2006-mysql-server-has-gone-away**
Thanks

**Comment by ixnet** [comment]
Eventually, I fixed that issue by adding those lines to the my.cnf file:

```
[mysqld]
max_allowed_packet=16M
```

**Comment by ninp0** [comment]
@ixnet 

How'd you go about editing my.cnf in the docker container?

**Comment by ninp0** [comment]
fwiw, since there's no editor in the mysql docker container, I had to run:

```
$ mysql_container=$(docker ps -a | grep defectdojo | grep mysql | awk '{print $NF}')
$ docker exec -it $mysql_container /bin/sh
# echo 'max_allowed_packet=16M' >> /etc/my.cnf
# systemctl restart mysqld
```
