### ISSUE TITLE
500 error when uploading Qualys VM XML

### ISSUE THREAD

**Issue by immewnity** [DefectDojo/django-DefectDojo#2540]
**Bug description**
When importing a Qualys report XML, a "Server Error (500)" is thrown immediately upon clicking Import.

**Steps to reproduce**
1. Go to the Import Scan Results page from a product (e.g. /product/2/import_scan_results)
2. Select "Qualys Scan"
3. Choose the XML file
4. Click Import
5. See error

**Expected behavior**
Data would be pulled in, similar to how Qualys WAS data successfully imports.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: `5c561d70: fix version numbers missed in 1.6.1 (#2498) [2020-06-07 09:51:01 +0200]`

**Console logs** (optional)
```
strptime() argument 1 must be str, not None
Traceback (most recent call last):
  File "/opt/dojo/django-DefectDojo/dojo/engagement/views.py", line 583, in import_scan_results
    parser = import_parser_factory(file, t, active, verified)
  File "/opt/dojo/django-DefectDojo/dojo/tools/factory.py", line 144, in import_parser_factory
    parser = QualysParser(file, test)
  File "/opt/dojo/django-DefectDojo/dojo/tools/qualys/parser.py", line 269, in __init__
    self.items = qualys_parser(file)
  File "/opt/dojo/django-DefectDojo/dojo/tools/qualys/parser.py", line 238, in qualys_parser
    master_list += issue_r(issue, d)
  File "/opt/dojo/django-DefectDojo/dojo/tools/qualys/parser.py", line 137, in issue_r
    _temp['mitigation_date'] = datetime.datetime.strptime(vuln_details.findtext('LAST_FIXED'), "%Y-%m-%dT%H:%M:%SZ").date()
TypeError: strptime() argument 1 must be str, not None
Error in parser: strptime() argument 1 must be str, not None
Internal Server Error: /product/2/import_scan_results
Traceback (most recent call last):
  File "/opt/dojo/django-DefectDojo/dojo/engagement/views.py", line 583, in import_scan_results
    parser = import_parser_factory(file, t, active, verified)
  File "/opt/dojo/django-DefectDojo/dojo/tools/factory.py", line 144, in import_parser_factory
    parser = QualysParser(file, test)
  File "/opt/dojo/django-DefectDojo/dojo/tools/qualys/parser.py", line 269, in __init__
    self.items = qualys_parser(file)
  File "/opt/dojo/django-DefectDojo/dojo/tools/qualys/parser.py", line 238, in qualys_parser
    master_list += issue_r(issue, d)
  File "/opt/dojo/django-DefectDojo/dojo/tools/qualys/parser.py", line 137, in issue_r
    _temp['mitigation_date'] = datetime.datetime.strptime(vuln_details.findtext('LAST_FIXED'), "%Y-%m-%dT%H:%M:%SZ").date()
TypeError: strptime() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/dojo/django-DefectDojo/dojo/product/views.py", line 475, in import_scan_results_prod
    return import_scan_results(request, pid=pid)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/dojo/django-DefectDojo/dojo/engagement/views.py", line 592, in import_scan_results
    return HttpResponseRedirect(reverse('import_scan_results', args=(eid,)))
  File "/usr/local/lib/python3.6/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'import_scan_results' with arguments '(None,)' not found. 1 pattern(s)tried: ['engagement/(?P<eid>\\d+)/import_scan_results$']
```

**Additional context** (optional)
This is using an XML file from Qualys VM's reporting function, as we noticed an XML directly from scan data would pull in 0 findings.

**Comment by devGregA** [comment]
@immewnity would you please provide a sample scan for verification?
