### ISSUE TITLE
add_epic jira config exception in celery worker 

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2577]
When editing an engagement, and possibly in other places, the celery task fails with an exception around JIRA config being not present. At least we need to make this code work if the jira config is not there (skip adding epic), but the question arises why add_epic is called at all if there is no jira config.

```
Running: Engagement integration tests
launching browser for:  ProductTest
starting chromedriver with options:  {'_binary_location': '', '_arguments': ['--headless', '--no-sandbox', '--disable-gpu', '--window-size=1280,1024'], '_extensions': [], '_caps': {'version': '', 'acceptInsecureCerts': True, 'browserName': 'chrome', 'platform': 'ANY'}, '_experimental_options': {}, '_extension_files': [], '_debugger_address': None} {'version': '', 'browserName': 'chrome', 'platform': 'ANY', 'goog:loggingPrefs': {'browser': 'ALL'}}
test_create_product (Product_unit_test.ProductTest) ... ×
Product added successfully.
ok
test_add_new_engagement (__main__.EngagementTest) ... ×
Engagement added successfully.
ok
test_edit_created_new_engagement (__main__.EngagementTest) ... ×
Engagement updated successfully.
ok
test_close_new_engagement (__main__.EngagementTest) ... ×
Engagement closed successfully.
ok
test_delete_new_closed_engagement (__main__.EngagementTest) ... ×
Engagement and relationships removed.
ok
test_new_ci_cd_engagement (__main__.EngagementTest) ... ×
Engagement added successfully.
ok
test_delete_product (Product_unit_test.ProductTest) ... ×
Product and relationships removed.
ok
----------------------------------------------------------------------
Ran 7 tests in 39.575s
OK
tearDownDriver:  BaseTestCase
closing browser
Grepping celery logs for errors:
celeryworker_1_fcf4021b1fb1 | [2020-06-17 21:27:19,394: ERROR/MainProcess] Task add_epic_task[20becd79-e7ad-4904-8a43-f780e6e1777a] raised unexpected: DoesNotExist('JIRA_PKey matching query does not exist.',)
celeryworker_1_fcf4021b1fb1 | Traceback (most recent call last):
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1_fcf4021b1fb1 |     R = retval = fun(*args, **kwargs)
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1_fcf4021b1fb1 |     return self.run(*args, **kwargs)
celeryworker_1_fcf4021b1fb1 |   File "/app/dojo/tasks.py", line 280, in add_epic_task
celeryworker_1_fcf4021b1fb1 |     add_epic(eng, push_to_jira)
celeryworker_1_fcf4021b1fb1 |   File "/app/dojo/utils.py", line 1564, in add_epic
celeryworker_1_fcf4021b1fb1 |     jpkey = JIRA_PKey.objects.get(product=prod)
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
celeryworker_1_fcf4021b1fb1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
--
celeryworker_1_fcf4021b1fb1 | [2020-06-17 21:27:40,500: ERROR/MainProcess] Task add_epic_task[45d93599-b5f5-41d4-b749-c8c791a853ce] raised unexpected: DoesNotExist('JIRA_PKey matching query does not exist.',)
celeryworker_1_fcf4021b1fb1 | Traceback (most recent call last):
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1_fcf4021b1fb1 |     R = retval = fun(*args, **kwargs)
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1_fcf4021b1fb1 |     return self.run(*args, **kwargs)
celeryworker_1_fcf4021b1fb1 |   File "/app/dojo/tasks.py", line 280, in add_epic_task
celeryworker_1_fcf4021b1fb1 |     add_epic(eng, push_to_jira)
celeryworker_1_fcf4021b1fb1 |   File "/app/dojo/utils.py", line 1564, in add_epic
celeryworker_1_fcf4021b1fb1 |     jpkey = JIRA_PKey.objects.get(product=prod)
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
celeryworker_1_fcf4021b1fb1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celeryworker_1_fcf4021b1fb1 |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
```

**Comment by valentijnscholten** [comment]
example travis job where this happens: https://travis-ci.org/github/DefectDojo/django-DefectDojo/jobs/699469080
