### ISSUE TITLE
Bug in dev: Importerror jsonline

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#2590]
**Bug description**
initalizer is not working

**Steps to reproduce**
* git clone <>
* git checkout dev
* cp dojo/settings/settings.dist.py dojo/settings/settings.py
* docker/setEnv.sh dev
* docker-compose pull
* docker-compose up

in master it works
```
initializer_1   | patching TagDescriptor
initializer_1   | Traceback (most recent call last):
initializer_1   |   File "manage.py", line 11, in <module>
initializer_1   |     execute_from_command_line(sys.argv)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
initializer_1   |     utility.execute()
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
initializer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
initializer_1   |     self.execute(*args, **cmd_options)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 361, in execute
initializer_1   |     self.check()
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
initializer_1   |     include_deployment_checks=include_deployment_checks,
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
initializer_1   |     issues.extend(super()._run_checks(**kwargs))
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 377, in _run_checks
initializer_1   |     return checks.run_checks(**kwargs)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
initializer_1   |     new_errors = check(app_configs=app_configs)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
initializer_1   |     all_namespaces = _load_all_namespaces(resolver)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
initializer_1   |     url_patterns = getattr(resolver, 'url_patterns', [])
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
initializer_1   |     res = instance.__dict__[self.name] = self.func(instance)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 584, in url_patterns
initializer_1   |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
initializer_1   |     res = instance.__dict__[self.name] = self.func(instance)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
initializer_1   |     return import_module(self.urlconf_name)
initializer_1   |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
initializer_1   |     return _bootstrap._gcd_import(name[level:], package, level)
initializer_1   |   File "<frozen importlib._bootstrap>", line 985, in _gcd_import
initializer_1   |   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
initializer_1   |   File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
initializer_1   |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
initializer_1   |   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
initializer_1   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
initializer_1   |   File "/app/dojo/urls.py", line 16, in <module>
initializer_1   |     from dojo.api import UserResource, ProductResource, EngagementResource, \
initializer_1   |   File "/app/dojo/api.py", line 32, in <module>
initializer_1   |     from dojo.tools.factory import import_parser_factory
initializer_1   |   File "/app/dojo/tools/factory.py", line 82, in <module>
initializer_1   |     from dojo.tools.yarn_audit.parser import YarnAuditParser
initializer_1   |   File "/app/dojo/tools/yarn_audit/parser.py", line 1, in <module>
initializer_1   |     import jsonlines
initializer_1   | ImportError: No module named 'jsonlines'
initializer_1   | Admin user: admin
initializer_1   | enabling audit logging
initializer_1   | ERROR 1146 (42S02) at line 1: Table 'defectdojo.auth_user' doesn't exist

```

**Expected behavior**
Init.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]
23974484: Slack fixes and enhancements (#2486) [2020-06-19 20:00:15 +0200]

**Comment by valentijnscholten** [comment]
Did you completely rebuild your images, i.e. with `docker-compose build --no-cache`?
This error means `pip install -r requirements.txt` wasn't executed with the newest `requirements.txt`.

**Comment by valentijnscholten** [comment]
Could be that the images that were pushed to docker hub as part of 1.6.5 are not working @madchap ?
@wurstbrot if you want to run dev you need to build the images. Just pulling will give you only the latest release from docker hub which is 1.6.5

**Comment by wurstbrot** [comment]
Update docker readme https://github.com/DefectDojo/django-DefectDojo/pull/2595

Had also issues setting dev mode. 

However, it is solved for me, thank you.
