### ISSUE TITLE
Import AppSpider VulnerabilitySummary.xml Server Error (500)

### ISSUE THREAD

**Issue by mappesona** [DefectDojo/django-DefectDojo#2654]
**Bug Description**
Get an Server Error (500) when trying to import AppSpider VulnerabilitySummary.xml report

**Step to Reproduce**

1. Go to 'Findings'
2. Click on 'Import Scan Results'
3. Select Scan Type 'AppSpider Scan'
4. Upload a file
5. Press on 'Import'
6. See error

**Expected behavior**
I would expect the scan results to be imported into the project as findings.

**Deployment method (select with an X)**

- [ ] Kubernetes
- [x]  Docker
- [ ]  setup.bash / legacy-setup.bash

**Environment information**
Operating System: Ubuntu 18.04 with Docker
Branch: Stable & Dev

**Sample scan files (optional)**

[VulnerabilitiesSummary.zip](https://github.com/DefectDojo/django-DefectDojo/files/4882062/VulnerabilitiesSummary.zip)

Console logs (optional)

> uwsgi_1         | Internal Server Error: /product/1/import_scan_results
> uwsgi_1         | Traceback (most recent call last):
> uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
> uwsgi_1         |     response = get_response(request)
> uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
> uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
> uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
> uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
> uwsgi_1         |     return view_func(request, *args, **kwargs)
> uwsgi_1         |   File "./dojo/product/views.py", line 475, in import_scan_results_prod
> uwsgi_1         |     return import_scan_results(request, pid=pid)
> uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
> uwsgi_1         |     return view_func(request, *args, **kwargs)
> uwsgi_1         |   File "./dojo/engagement/views.py", line 643, in import_scan_results
> uwsgi_1         |     burpResponseBase64=base64.b64encode(req_resp["resp"].encode("utf-8")),
> uwsgi_1         | AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by mappesona** [comment]
This issue is resolved after doing pull request.
![Uploading DD.PNG…]()
