### ISSUE TITLE
push to jira: sla calculation fails for findings import in engagements created on the same day

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2695]
```
Traceback (most recent call last):
  File "/home/valentijn/venv_dd/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/valentijn/venv_dd/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/valentijn/venv_dd/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/valentijn/venv_dd/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/c/Data/django-DefectDojo/dojo/engagement/views.py", line 694, in import_scan_results
    item.save(false_history=True, push_to_jira=push_to_jira)
  File "/c/Data/django-DefectDojo/dojo/models.py", line 1963, in save
    add_issue(self, True)
  File "/c/Data/django-DefectDojo/dojo/utils.py", line 1404, in add_issue
    duedate = find.sla_deadline().strftime('%Y-%m-%d')
  File "/c/Data/django-DefectDojo/dojo/models.py", line 1775, in sla_deadline
    return self.date + relativedelta(days=self.sla_days_remaining())
  File "/c/Data/django-DefectDojo/dojo/models.py", line 1765, in sla_days_remaining
    sla_calculation = sla_age - self.age
  File "/c/Data/django-DefectDojo/dojo/models.py", line 1755, in age
    diff = get_current_date() - self.date
```

```
    @property
    def age(self):
        if self.mitigated:
            diff = self.mitigated.date() - self.date
        else:
            diff = get_current_date() - self.date
        days = diff.days
        return days if days > 0 else 0

    def sla_days_remaining(self):
        sla_calculation = None
        severity = self.severity
        from dojo.utils import get_system_setting
        sla_age = get_system_setting('sla_' + self.severity.lower())
        if sla_age and self.active:
            sla_calculation = sla_age - self.age
        elif sla_age and self.mitigated:
            age = self.age
            if age < sla_age:
                sla_calculation = 0
            else:
                sla_calculation = sla_age - age
        return sla_calculation
```
 
looks like somewhere the finding.date field is set to be a datetime instead of a date.

could be in the import_scan_results:

```
                    item.test = t
                    if item.date == timezone.now().date():
                        item.date = t.target_start
```

target_start is a datetime

**Comment by valentijnscholten** [comment]
found 5 more places where this happened. wasn't a problem before because django converts it to a date after serializaing to the database. but now we are performing calculations with the date field before serialization and/or while the finding is still in memory .

**Comment by valentijnscholten** [comment]
Fixed
