### ISSUE TITLE
JIRA "next-gen" project: creation issue

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2703]
**Bug description**
So it seems that so-called Next-Gen JIRA projects are different... when wanting to push a jira issue from dojo to such a project, I got

```
celeryworker_1  | [2020-07-21 10:23:12,040: ERROR/ForkPoolWorker-44] Task add_issue_task[f51792c7-7886-436f-993e-66d9b4468159] raised unexpected: IndexError('list index out of range',)
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 268, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
celeryworker_1  |   File "/app/dojo/utils.py", line 1398, in add_issue
celeryworker_1  |     if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']:
celeryworker_1  | IndexError: list index out of range
```

**Comment by madchap** [comment]
Closing, will not try to validate now. Turns out next-gen projects within the instance don't even share issue types, so... no time to test that.

**Comment by valentijnscholten** [comment]
We could do a simple check when someone creates/saves a JIRA config to make sure we can retrieve the metadata. Wouldn't be to much work and makes it clear early on that it won't work.
