### ISSUE TITLE
Cannot dump data anymore

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2821]
**Bug description**
1. Load up a new docker-compose, add a product and import some anchore scan findings.
2. Then try to dump the data

```
docker exec -ti madchap_ddojo_uwsgi_1 bash -c 'python manage.py dumpdata --indent=4 -e sessions -e admin --natural-foreign --natural-primary -e contenttypes -e auth.permission -v2' > ~/Downloads/datadump_orm_dump_small.json
```

```
CommandError: Unable to serialize database: ContentType 18 for <class 'dojo.models.BurpRawRequestResponse'> #3 does not point to a subclass!
}Exception ignored in: <generator object cursor_iter at 0x7f811cf3cba0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1555, in cursor_iter
    cursor.close()
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 83, in close
    while self.nextset():
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 137, in nextset
    nr = db.next_result()
MySQLdb._exceptions.OperationalError: (2006, '')
```

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
`[2020-08-31 16:06:15 +0200] 24d9f212: view finding: duplicate & similar finding improvements and fixes (#2748) [ (HEAD -> dev, upstream/dev)]`

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by madchap** [comment]
With `--traceback`

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/dumpdata.py", line 186, in handle
    object_count=object_count,
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py", line 114, in serialize
    self.handle_m2m_field(obj, field)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/python.py", line 72, in handle_m2m_field
    m2m_value(related) for related in getattr(obj, field.name).iterator()
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/python.py", line 72, in <listcomp>
    m2m_value(related) for related in getattr(obj, field.name).iterator()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 341, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.6/site-packages/polymorphic/query.py", line 66, in _polymorphic_iterator
    real_results = self.queryset._get_real_instances(base_result_objects)
  File "/usr/local/lib/python3.6/site-packages/polymorphic/query.py", line 377, in _get_real_instances
    real_concrete_class = base_object.get_real_instance_class()
  File "/usr/local/lib/python3.6/site-packages/polymorphic/models.py", line 137, in get_real_instance_class
    self.polymorphic_ctype_id, model, self.pk
polymorphic.models.PolymorphicTypeInvalid: ContentType 18 for <class 'dojo.models.BurpRawRequestResponse'> #3 does not point to a subclass!
Exception ignored in: <generator object cursor_iter at 0x7f64fb01d6d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1555, in cursor_iter
    cursor.close()
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 83, in close
    while self.nextset():
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 137, in nextset
    nr = db.next_result()
MySQLdb._exceptions.OperationalError: (2006, '')

```

**Comment by madchap** [comment]
OK, somehow, I cannot reproduce this on my other computer. So I must be messing something up somewhere. Always my fault! ;-)
