### ISSUE TITLE
AttributeError: type object 'Context' has no attribute 'description'

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2950]
In the unit tests logs I see can exception around the `description` field in notification templates. Not sure if it is a problem or not, but I remember some earlier issues around this field and how it was around in kwargs and sometimes being missing. So we need to check if notifications are still getting the right templates rendered.
```
uwsgi_1         | Exception while resolving variable 'description' in template 'notifications/scan_added.tpl'.
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
uwsgi_1         |     current = current[bit]
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
uwsgi_1         |     raise KeyError(key)
uwsgi_1         | KeyError: 'description'
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
uwsgi_1         |     if isinstance(current, BaseContext) and getattr(type(current), bit):
uwsgi_1         | AttributeError: type object 'Context' has no attribute 'description'
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
uwsgi_1         |     current = current[int(bit)]
uwsgi_1         | ValueError: invalid literal for int() with base 10: 'description'
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
uwsgi_1         |     (bit, current))  # missing attribute
uwsgi_1         | django.template.base.VariableDoesNotExist: Failed lookup for key [description] in [{'True': True, 'False': False, 'None': None}, {'initiator': <User: admin>, 'title': 'Created 4 findings for Security How-to: 1st Quarter Engagement: ZAP Scan', 'findings_new': [<Finding: Web Browser XSS Protection Not Enabled>, <Finding: X-Content-Type-Options Header Missing>, <Finding: X-Frame-Options Header Not Set>, <Finding: Directory Browsing>], 'findings_mitigated': [], 'finding_count': 4, 'test': <Test: ZAP Scan>, 'engagement': <Engagement: Engagement: 1st Quarter Engagement (Apr 12, 2018)>, 'product': <Product: Security How-to>, 'url': '/test/16', 'type': 'alert', 'user': None}]
```

**Comment by valentijnscholten** [comment]
Not seeing this anymore, closing. A new issue can be opened if error reoccurs.
