### ISSUE TITLE
api-token-auth rest endpoint is broken

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3042]
When trying to obtain the API token through a curl command

```
curl -X POST -H "X-CSRFToken: kBEd08DFa907moWGFPCLWj1R9nxUKOFJOkWJYeka2Wuba3lOZBm6SDLahNf0kbzu" -H 'content-type: application/json' http://localhost:8080/api/v2/api-token-auth/ -d '{"username": admin, "password": "9pfwZG7N2t3WyGRifhXpY0"}'
```

it returns
```
{"detail":"JSON parse error - Expecting value: line 1 column 14 (char 13)"
```

the following error occurs:

```
<uwsgi_1         | TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?
uwsgi_1         | 'default' on schema for PrimaryKeyRelatedField(allow_null=True, default=[], read_only=True) will not be set because to_representation raised an exception
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
uwsgi_1         |     default = field_value_to_representation(field, default)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
uwsgi_1         |     value = field.to_representation(value)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/rest_framework/relations.py", line 265, in to_representation
uwsgi_1         |     return value.pk
uwsgi_1         | AttributeError: 'list' object has no attribute 'pk'
uwsgi_1         | 'default' on schema for PrimaryKeyRelatedField(allow_null=True, default=[], queryset=<QuerySet []>) will not be set because to_representation raised an exception
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
uwsgi_1         |     default = field_value_to_representation(field, default)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
uwsgi_1         |     value = field.to_representation(value)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/rest_framework/relations.py", line 265, in to_representation
uwsgi_1         |     return value.pk
uwsgi_1         | AttributeError: 'list' object has no attribute 'pk'
```

**Comment by valentijnscholten** [comment]
since when is this? Didn't even know this was possible. I think the whole idea of the API token was that you prevent users from using their passwords in scripts.

**Comment by valentijnscholten** [comment]
can you check if you revert https://github.com/DefectDojo/django-DefectDojo/pull/3025 or downgrade DRF a bit

**Comment by valentijnscholten** [comment]
on my side i get more info in the stacktrace:
```
ProductViewSet.getqueryset
'default' on schema for PrimaryKeyRelatedField(allow_null=True, default=[], queryset=<QuerySet [<Notes: created JIRA issue https://jira.com/ISEC-499 for finding>, <Notes: unlinked JIRA issue https://jira.com/ILUKIVR-144 from finding>, <Notes: linked JIRA issue https://jira.com/ISEC-454 to finding>, <Notes: unlinked JIRA issue https://jira.com/ISEC-498 from finding>, <Notes: created JIRA issue https://jira.com/ISEC-498 for finding>, <Notes: unlinked JIRA issue https://jira.com/ISEC-454 from finding>, <Notes: created JIRA issue https://jira.com/ISEC-497 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-496 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-495 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-494 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-493 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-492 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-491 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-490 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-489 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-488 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-487 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-486 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-485 for finding>, <Notes: created JIRA issue https://jira.com/ISEC-484 for finding>, '...(remaining elements truncated)...']>) will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/valentijn/venv/lib/python3.8/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/valentijn/venv/lib/python3.8/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/relations.py", line 265, in to_representation
    return value.pk
AttributeError: 'list' object has no attribute 'pk'
```

**Comment by valentijnscholten** [comment]
already happens on 1d79cead0eaa63c509fc124dc196504674ce0be8, so not related to recent PRs and shouldn't block us to do a release from dev tomorrow.

**Comment by madchap** [comment]
Silly me. Forgot double quotes around `admin` useranem.
