### ISSUE TITLE
view all endpoints: Q is not defined error

### ISSUE THREAD

**Issue by Seppl2202** [DefectDojo/django-DefectDojo#3167]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
When viewing Endpoints of a Product and not having a staff role, there is a HTTP 500:

```
Internal Server Error: /endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/endpoint/views.py", line 78, in all_endpoints
    Q(product__authorized_users__in=[request.user]) |
NameError: name 'Q' is not defined
[pid: 23|app: 0|req: 951/1545] 172.23.0.1 () {62 vars in 1654 bytes} [Wed Nov  4 10:48:54 2020] GET /endpoint?product=1 => generated 27 bytes in 76 msecs (HTTP/1.0 500) 6 headers in 192 bytes (1 switches on core 1)
```

**Steps to reproduce**
1. Go to 'Product'
2. Click on 'Endpoints -> View Endpoints'
3. Get the Docker Logs of the Container

**Expected behavior**
Endpoints should be visible, even with no staff role assigned.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Console logs** (optional)
```
Internal Server Error: /endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/endpoint/views.py", line 78, in all_endpoints
    Q(product__authorized_users__in=[request.user]) |
NameError: name 'Q' is not defined
[pid: 23|app: 0|req: 951/1545] 172.23.0.1 () {62 vars in 1654 bytes} [Wed Nov  4 10:48:54 2020] GET /endpoint?product=1 => generated 27 bytes in 76 msecs (HTTP/1.0 500) 6 headers in 192 bytes (1 switches on core 1)
```

**Additional context** (optional)
It seems like an import is missing in /dojo/endpoint/view.py

There is no import statement `from django.db.models import Q`

```
def all_endpoints(request):
    endpoints = Endpoint.objects.all()
    show_uri = get_system_setting('display_endpoint_uri')
    # are they authorized
    if request.user.is_staff:
        pass
    else:
        endpoints = Endpoint.objects.filter(
            Q(product__authorized_users__in=[request.user]) |
            Q(product__prod_type__authorized_users__in=[request.user])
        )
        if not endpoints:
            raise PermissionDenied
```

According to the code, as a staff, the `Q` calls are not reached. That is why it works as a staff.

**Comment by Seppl2202** [comment]
I have added the import statement and it works in our instance. I will create a PR

**Comment by madchap** [comment]
Should be fixed now. Closing. Let me know if not the case.
