### ISSUE TITLE
jira: list index out of range stacktrace 500 when jira user has no permission

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3240]
When the jira user used by Defect Dojo has no permissions on the configured JIRA project, or the project doesn't exist in JIRA, a stacktrace occurs in Defect Dojo:

```
celeryworker_1  | [2020-07-21 10:23:12,040: ERROR/ForkPoolWorker-44] Task add_issue_task[f51792c7-7886-436f-993e-66d9b4468159] raised unexpected: IndexError('list index out of range',)
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 268, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
celeryworker_1  |   File "/app/dojo/utils.py", line 1398, in add_issue
celeryworker_1  |     if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']:
celeryworker_1  | IndexError: list index out of range
```

Can't find all the github issues related to this, but #2703 is one of them.
#2747

**Comment by valentijnscholten** [comment]
fixed in dev, so 1.10.0
