### ISSUE TITLE
Entering a tag over 25 chars causes a 500 error

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3258]
When adding an engagement with a long tag, pgSQL backend.

```
ERROR:django.request:Internal Server Error: /product/31/new_engagement
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tagging.models.Tag.DoesNotExist: Tag matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(25)
```

**Comment by valentijnscholten** [comment]
It has to do with this setting: 
![image](https://user-images.githubusercontent.com/4426050/99079876-cee51400-25c0-11eb-8ef6-8fa1767f3249.png)

**Comment by valentijnscholten** [comment]
@madchap can you confirm it's no longer a problem since 1.11.0 with `django-tagulous` (max length = 255 by default).
