### ISSUE TITLE
MySQL Container Drops Connections in Nessus Scan Import Process

### ISSUE THREAD

**Issue by sempervictus** [DefectDojo/django-DefectDojo#3405]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
When importing Nessus scans (medium->large), the mysql service "goes away" per uwsgi container's parlance, with the mysql container logs showing
```
[Note] Aborted connection 74 to db: 'defectdojo' user: 'defectdojo' host: '172.18.0.6' (Got a packet bigger than 'max_allowed_packet' bytes)
```

**Steps to reproduce**
1. Generate nessus report with lots of findings and targets, this is sort of hit-or-miss
2. Import the scan
3. Wait to get a 500 error on the page
4. `docker logs defect-dojo_uwsgi_1` will throw something akin to:
```
ERROR:django.request:Internal Server Error: /engagement/1/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/engagement/views.py", line 627, in import_scan_results
    item.save(dedupe_option=False, false_history=True)
  File "./dojo/models.py", line 2130, in save
    super(Finding, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 782, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 911, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
```

**Expected behavior**
All nessus scans import correctly

**Deployment method** *(select with an `X`)*
- Docker

**Environment information**
 - Operating System: Arch
 - DefectDojo Commit Message: `[2020-12-01 18:28:54 +0100] 6bcdb77e: Merge pull request #3395 from DefectDojo/dependabot/add-v2-config-file [ (HEAD -> deploy, origin/master, origin/HEAD, master)]`

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)
The consistently failing scan is a 176MB .nessus file, cant be shared, using `SCAN_FILE_MAX_SIZE = 768` in the local_settings.py file to work around the rather small 100MB restriction.

**Comment by sempervictus** [comment]
Solution-size, its probably fine to just add `'--max_allowed_packet=768M'` to the compose command. That number should probably be a variable somewhere more a bit more user-accessible, as should the scan file size limit.

**Comment by valentijnscholten** [comment]
we have seen this error before, but always managed to convince people to not import such massive scan reports :-) 
can you test your suggestion to see if it works. and if dojo survives such a large report? might need bigger timeouts here or there as well.

**Comment by ixnet** [comment]
Could you guys fix that please 👍🏽

**Comment by ixnet** [comment]
https://serverfault.com/questions/407612/error-2006-mysql-server-has-gone-away

**Comment by ixnet** [comment]
Eventually, I fixed that issue by adding those lines to the my.cnf file:

```
[mysqld]
max_allowed_packet=16M
```
