### ISSUE TITLE
Reports broken on related_fields via API v2

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3426]
in `dev` / `1.10.4` an exception occurs when trying to generate a report for an engagement via API_v2:

```
curl -X POST "http://defectdojo-dev:8000/api/v2/engagements/1165/generate_report/" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "X-CSRFToken: 1234" -d "{  \"include_finding_notes\": false,  \"include_finding_images\": false,  \"include_executive_summary\": false,  \"include_table_of_contents\": false}"
```
traceback
```
Internal Server Error: /api/v2/engagements/1165/generate_report/
Traceback (most recent call last):
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/valentijn/dd/dojo/api_v2/views.py", line 167, in generate_report
    return Response(report.data)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/valentijn/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/home/valentijn/dd/dojo/api_v2/serializers.py", line 716, in get_related_fields
    query_params = self.context['request'].query_params
KeyError: 'request'
```

**Comment by valentijnscholten** [comment]
Same for product report, etc.

**Comment by madchap** [comment]
should be fixed then?
