### ISSUE TITLE
product report without product id throws exception

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3446]
affect 1.10.4 (and earlier) (and dev with the report fixes in place)
- goto product overview at /product
- open context menu on right
- click 'product report'
- observe exception

```
ERROR:django.request:Internal Server Error: /product/report
Traceback (most recent call last):
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/valentijn/dd/dojo/reports/views.py", line 362, in product_findings_report
    return generate_report(request, findings)
  File "/home/valentijn/dd/dojo/reports/views.py", line 759, in generate_report
    findings = ReportAuthedFindingFilter(request.GET,
  File "/home/valentijn/dd/dojo/filters.py", line 1359, in __init__
    super(ReportAuthedFindingFilter, self).__init__(*args, **kwargs)
  File "/home/valentijn/dd/dojo/filters.py", line 63, in __init__
    super(DojoFilter, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'user'
```

**Comment by valentijnscholten** [comment]
not sure what it is supposed to do as without a product (id) it can't generate a product report anyway, but in the code it looks like it's ending up in the "Finding Report" section.

**Comment by valentijnscholten** [comment]
fixed
