### ISSUE TITLE
DSoP parser no longer working: Excel xlsx file; not supported

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3455]
As of today the unit tests seem to be failing with the below error. This means also the DSoP parser probably no longer works when somebody builds the django container today or later.

```
uwsgi_1         | ======================================================================
uwsgi_1         | ERROR: test_zero_findings (dojo.unittests.test_dsop_parser.TestDsopParser)
uwsgi_1         | ----------------------------------------------------------------------
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/dojo/unittests/test_dsop_parser.py", line 11, in test_zero_findings
uwsgi_1         |     parser = DsopParser(file, Test())
uwsgi_1         |   File "/app/dojo/tools/dsop/parser.py", line 14, in __init__
uwsgi_1         |     f = pd.ExcelFile(file)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 867, in __init__
uwsgi_1         |     self._reader = self._engines[engine](self._io)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
uwsgi_1         |     super().__init__(filepath_or_buffer)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 351, in __init__
uwsgi_1         |     self.book = self.load_workbook(filepath_or_buffer)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/pandas/io/excel/_xlrd.py", line 35, in load_workbook
uwsgi_1         |     return open_workbook(file_contents=data)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/xlrd/__init__.py", line 170, in open_workbook
uwsgi_1         |     raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
uwsgi_1         | xlrd.biffh.XLRDError: Excel xlsx file; not supported
```

**Comment by valentijnscholten** [comment]
caused by `xlrd` 2.0.0 being released today and not pinned in `requirements.txt`

**Comment by valentijnscholten** [comment]
to fix this, apply the change from https://github.com/DefectDojo/django-DefectDojo/pull/3457 to your local install and rebuild.
or wait for that PR to be release into 1.11.0 or 1.10.5
