### ISSUE TITLE
Error Importing Webinspect XML

### ISSUE THREAD

**Issue by buranbr** [DefectDojo/django-DefectDojo#3470]
When I try to import Webinspect Enterprise version 20.1.0 XML files, i get the following error:
Error in parser: local variable 'cwe' referenced before assignment

I´m running the most recent version of defectdojo on Docker Desktop for Windows, from WSL Ubuntu

[14/Dec/2020 18:19:55] ERROR [dojo:598] local variable 'cwe' referenced before assignment
Traceback (most recent call last):
  File "./dojo/engagement/views.py", line 591, in import_scan_results
    parser = import_parser_factory(file, t, active, verified)
  File "./dojo/tools/factory.py", line 240, in import_parser_factory
    parser = MicrofocusWebinspectXMLParser(file, test)
  File "./dojo/tools/microfocus_webinspect/parser.py", line 85, in __init__
    cwe=cwe,
UnboundLocalError: local variable 'cwe' referenced before assignment
[14/Dec/2020 18:19:55] ERROR [dojo:599] Error in parser: local variable 'cwe' referenced before assignment

[wie-xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/5690802/wie-xml.zip)

**Comment by yilmi** [comment]
Hi @buranbr, You should be able to test the fix from the project's dev branch now, I used your examples but let us know if you find other issues.
Also, as this is part of the dev branch it should land in a future release, you can check the releases notes.

**Comment by madchap** [comment]
Closing, the fix is in release 1.11.0. Please open a new issue if it still arises. Thanks @yilmi for providing a fix!
