### ISSUE TITLE
metrics: exception when browsing to product metrics

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3546]
when browsing directly to a product metrics page, there is no referrer and this generates an exception:

```
Internal Server Error: /product/156/metrics
Traceback (most recent call last):
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/valentijn/dd/dojo/user/helper.py", line 79, in _wrapped
    return view_func(request, lookup_value, *args, **kwargs)
  File "/home/valentijn/dd/dojo/product/views.py", line 408, in view_product_metrics
    view = identify_view(request)
  File "/home/valentijn/dd/dojo/product/views.py", line 206, in identify_view
    if referer.find('type=Endpoint') > -1:
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by valentijnscholten** [comment]
Seems to be caused by multiple levels of 'get earliest finding' and 'get earliest date' and daterangefilter in the productmetricsfindingfilter.
