### ISSUE TITLE
metrics: no findings in product metrics due to swallowed exception

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3547]
on the product metrics there are no findings shown. there is a try-catch that swallows the exception, but the exception is: 

```
Traceback (most recent call last):
  File "/home/valentijn/dd/dojo/product/views.py", line 237, in finding_querys
    start_date = findings_qs.earliest('date').date
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/db/models/query.py", line 646, in earliest
    return self._earliest(*fields, field_name=field_name)
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/db/models/query.py", line 643, in _earliest
    return obj.get()
  File "/home/valentijn/venv/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
dojo.models.Finding.DoesNotExist: Finding matching query does not exist.
```

**Comment by valentijnscholten** [comment]
Seems to be caused by multiple levels of 'get earliest finding' and 'get earliest date' and daterangefilter in the productmetricsfindingfilter.

**Comment by valentijnscholten** [comment]
![image](https://user-images.githubusercontent.com/4426050/103103502-c94c0680-4621-11eb-8811-c49a7840c150.png)

**Comment by valentijnscholten** [comment]
happens when a product has no new findings in the last 30 days. it looks like the code is trying to prevent this from happening, but is failing.
