### ISSUE TITLE
Nessus CSV parser 500 error - , line 84 endpoint.Host += ":" + var

### ISSUE THREAD

**Issue by harishgowdahk** [DefectDojo/django-DefectDojo#3655]
Whevener CSV file is uploaded I am getting 500 error in the browser  and below is the log file 
ches on core 0)
Internal Server Error: /engagement/3/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/engagement/views.py", line 558, in import_scan_results
    parser = import_parser_factory(file, t, active, verified)
  File "./dojo/tools/factory.py", line 87, in import_parser_factory
    parser = NessusCSVParser(file, test)
  File "./dojo/tools/nessus/parser.py", line 84, in __init__
    endpoint.host += ":" + var
AttributeError: 'NoneType' object has no attribute 'Host'
[sample.zip](https://github.com/DefectDojo/django-DefectDojo/files/5836290/sample.zip)

**Comment by harishgowdahk** [comment]
We can fix above error by changing elif heading[i] == "Host": to elif heading[i] == "IP Address":

But after fixing also results are coming empty without any error . Not sure why

**Comment by madchap** [comment]
Can you please provide a sample file to reproduce the problem? Thanks.

**Comment by damiencarol** [comment]
@harishgowdahk  I'm working on your issue I can reproduce it in a unit test. https://github.com/DefectDojo/django-DefectDojo/pull/3710

**Comment by damiencarol** [comment]
funny... the tool doesn't generate valid CVSS v3 vectors...
```
ERROR: test_parse_some_findings_csv (dojo.unittests.test_nessus_parser.TestNessusParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/damien/dd/dojo/unittests/test_nessus_parser.py", line 35, in test_parse_some_findings_csv
    parser = NessusCSVParser(testfile, self.create_test())
  File "/home/damien/dd/dojo/tools/nessus/parser.py", line 12, in __init__
    self.items = self.get_findings(file, test)
  File "/home/damien/dd/dojo/tools/nessus/parser.py", line 91, in get_findings
    find.cvssv3 = CVSS3(row.get('CVSS V3 Vector')).clean_vector()
  File "/home/damien/dd/.venv/lib/python3.9/site-packages/cvss/cvss3.py", line 95, in __init__
    self.parse_vector()
  File "/home/damien/dd/.venv/lib/python3.9/site-packages/cvss/cvss3.py", line 122, in parse_vector
    raise CVSS3MalformedError('Malformed CVSS3 vector "{0}" is missing mandatory prefix '
cvss.exceptions.CVSS3MalformedError: Malformed CVSS3 vector "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N/E:P/RL:O/RC:C" is missing mandatory prefix or uses unsupported CVSS version
```

**Comment by damiencarol** [comment]
@harishgowdahk your issue is fixed in dev.
