### ISSUE TITLE
Nikto parser: Support JSON format

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4096]
**Scanner Name**
Name of the scanner, brief description of the scanner and link.

**Sample File**
Please attach a sample file and the format of the file (xml, json, csv).

According to this page, SecureCodeBox project need Nikto JSON format support 
https://docs.securecodebox.io/docs/hooks/defectdojo
![image](https://user-images.githubusercontent.com/1694940/111897981-520cef80-8a23-11eb-9cec-80424d6f73e6.png)

**Comment by madchap** [comment]
I ran a quick test seeing this, but it seem that

```
uwsgi_1         | [04/May/2021 17:30:05] ERROR [dojo.importers.utils:23] Extra data: line 1 column 89 (char 88)
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "./dojo/tools/nikto/parser.py", line 38, in get_findings
uwsgi_1         |     return self.process_json(filename, test)
uwsgi_1         |   File "./dojo/tools/nikto/parser.py", line 43, in process_json
uwsgi_1         |     data = json.load(file)
uwsgi_1         |   File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
uwsgi_1         |     return loads(fp.read(),
uwsgi_1         |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
uwsgi_1         |     return _default_decoder.decode(s)
uwsgi_1         |   File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
uwsgi_1         |     raise JSONDecodeError("Extra data", s, end)
uwsgi_1         | json.decoder.JSONDecodeError: Extra data: line 1 column 89 (char 88)
uwsgi_1         | [04/May/2021 17:30:05] WARNING [dojo.importers.utils:24] Error in parser: Extra data: line 1 column 89 (char 88)
uwsgi_1         | [04/May/2021 17:30:05] ERROR [dojo.engagement.views:614] Extra data: line 1 column 89 (char 88)
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 599, in import_scan_results
uwsgi_1         |     test, finding_count, closed_finding_count = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 248, in import_scan
uwsgi_1         |     parsed_findings = importer_utils.parse_findings(scan, test, active, verified, scan_type)
uwsgi_1         |   File "./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "./dojo/tools/nikto/parser.py", line 38, in get_findings
uwsgi_1         |     return self.process_json(filename, test)
uwsgi_1         |   File "./dojo/tools/nikto/parser.py", line 43, in process_json
uwsgi_1         |     data = json.load(file)
uwsgi_1         |   File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
uwsgi_1         |     return loads(fp.read(),
uwsgi_1         |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
uwsgi_1         |     return _default_decoder.decode(s)
uwsgi_1         |   File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
uwsgi_1         |     raise JSONDecodeError("Extra data", s, end)
uwsgi_1         | json.decoder.JSONDecodeError: Extra data: line 1 column 89 (char 88)

```

I can take a look at it.

**Comment by madchap** [comment]
I was on an older version of nikto (had their git repo checked out). Just updated to their latest `master`, worked just fine :+1: 

So I guess we're good!

This was an easy one :smiley_cat:
