### ISSUE TITLE
Jira cloud integration

### ISSUE THREAD

**Issue by true-hero** [DefectDojo/django-DefectDojo#4225]
## Bug description
Unable to save Jira config. I am using token to authenticate and it works good on 1.13.0, but on version 1.14.0 it failed with error

```
uwsgi_1         | 	response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'www-authenticate': 'JIRA REST POST, OAuth realm="https%3A%2F%2F<censored>.atlassian.net"', 'cache-control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Thu, 08 Apr 2021 11:29:10 GMT', 'ATL-TraceId': '15abd1adc439007c', 'x-arequestid': '4a79ab9f-7ee4-4d11-96f8-0773aff1cb3c', 'x-aaccountid': '', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'timing-allow-origin': '*', 'x-envoy-upstream-service-time': '38', 'X-Content-Type-Options': 'nosniff', 'micros-issuer': 'micros/edge-authenticator', 'Connection': 'keep-alive', 'set-cookie': 'atlassian.xsrf.token=c1696a7d-832f-45ef-9c1c-f25c98ea3608_4c697bc7b7a44eaf37abb50e35a18111566e6bd6_lin; Path=/; Secure', 'Expect-CT': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy", enforce, max-age=86400'}
uwsgi_1         | 	response text = {"errorMessages":["Ошибка доступа"],"errors":{}}
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/jira_link/helper.py", line 319, in get_jira_connection_raw
uwsgi_1         |     max_retries=0, validate=validate)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/jira/client.py", line 462, in __init__
uwsgi_1         |     user = self.session(auth)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/jira/client.py", line 2446, in session
uwsgi_1         |     r = self._session.post(url, data=json.dumps(authentication_data))
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/jira/resilientsession.py", line 154, in post
uwsgi_1         |     return self.__verb('POST', url, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/jira/resilientsession.py", line 147, in __verb
uwsgi_1         |     raise_on_error(response, verb=verb, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/jira/resilientsession.py", line 57, in raise_on_error
uwsgi_1         |     r.status_code, error, r.url, request=request, response=r, **kwargs)
uwsgi_1         | jira.exceptions.JIRAError: JiraError HTTP 401 url: https://<censored>.atlassian.net/rest/auth/1/session
uwsgi_1         | 	text: Ошибка доступа
uwsgi_1         |
uwsgi_1         | 	response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'www-authenticate': 'JIRA REST POST, OAuth realm="https%3A%2F%2F<censored>.atlassian.net"', 'cache-control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Thu, 08 Apr 2021 11:29:10 GMT', 'ATL-TraceId': '15abd1adc439007c', 'x-arequestid': '4a79ab9f-7ee4-4d11-96f8-0773aff1cb3c', 'x-aaccountid': '5fb3b1e04a09640069cd8add', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'timing-allow-origin': '*', 'x-envoy-upstream-service-time': '38', 'X-Content-Type-Options': 'nosniff', 'micros-issuer': 'micros/edge-authenticator', 'Connection': 'keep-alive', 'set-cookie': 'atlassian.xsrf.token=c1696a7d-832f-45ef-9c1c-f25c98ea3608_4c697bc7b7a44eaf37abb50e35a18111566e6bd6_lin; Path=/; Secure', 'Expect-CT': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy", enforce, max-age=86400'}
uwsgi_1         | 	response text = {"errorMessages":["Ошибка доступа"],"errors":{}}
uwsgi_1         | [08/Apr/2021 11:29:10] ERROR [dojo.jira_link.views:321] jform.errors: <ul class="errorlist"><li>username<ul class="errorlist"><li>Unable to authenticate to JIRA. Please check the URL, username, password, captcha challenge, Network connection. Details in alert on top right. JiraError HTTP 401 url: https://<censored>.atlassian.net/rest/auth/1/session
uwsgi_1         | 	text: Ошибка доступа
uwsgi_1         |
uwsgi_1         | 	response headers = {&#39;Server&#39;: &#39;AtlassianProxy/1.15.8.1&#39;, &#39;www-authenticate&#39;: &#39;JIRA REST POST, OAuth realm=&quot;https%3A%2F%2F<censored>.atlassian.net&quot;&#39;, &#39;cache-control&#39;: &#39;no-cache, no-store, no-transform&#39;, &#39;Content-Type&#39;: &#39;application/json;charset=UTF-8&#39;, &#39;Strict-Transport-Security&#39;: &#39;max-age=315360000; includeSubDomains; preload&#39;, &#39;Date&#39;: &#39;Thu, 08 Apr 2021 11:29:10 GMT&#39;, &#39;ATL-TraceId&#39;: &#39;15abd1adc439007c&#39;, &#39;x-arequestid&#39;: &#39;4a79ab9f-7ee4-4d11-96f8-0773aff1cb3c&#39;, &#39;x-aaccountid&#39;: &#39;5fb3b1e04a09640069cd8add&#39;, &#39;X-XSS-Protection&#39;: &#39;1; mode=block&#39;, &#39;Transfer-Encoding&#39;: &#39;chunked&#39;, &#39;timing-allow-origin&#39;: &#39;*&#39;, &#39;x-envoy-upstream-service-time&#39;: &#39;38&#39;, &#39;X-Content-Type-Options&#39;: &#39;nosniff&#39;, &#39;micros-issuer&#39;: &#39;micros/edge-authenticator&#39;, &#39;Connection&#39;: &#39;keep-alive&#39;, &#39;set-cookie&#39;: &#39;atlassian.xsrf.token=c1696a7d-832f-45ef-9c1c-f25c98ea3608_4c697bc7b7a44eaf37abb50e35a18111566e6bd6_lin; Path=/; Secure&#39;, &#39;Expect-CT&#39;: &#39;report-uri=&quot;https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy&quot;, enforce, max-age=86400&#39;}
uwsgi_1         | 	response text = {&quot;errorMessages&quot;:[&quot;Ошибка доступа&quot;],&quot;errors&quot;:{}}</li></ul></li><li>password<ul class="errorlist"><li>Unable to authenticate to JIRA. Please check the URL, username, password, captcha challenge, Network connection. Details in alert on top right. JiraError HTTP 401 url: https://<censored>.atlassian.net/rest/auth/1/session
uwsgi_1         | 	text: Ошибка доступа
uwsgi_1         |
uwsgi_1         | 	response headers = {&#39;Server&#39;: &#39;AtlassianProxy/1.15.8.1&#39;, &#39;www-authenticate&#39;: &#39;JIRA REST POST, OAuth realm=&quot;https%3A%2F%2F<censored>.atlassian.net&quot;&#39;, &#39;cache-control&#39;: &#39;no-cache, no-store, no-transform&#39;, &#39;Content-Type&#39;: &#39;application/json;charset=UTF-8&#39;, &#39;Strict-Transport-Security&#39;: &#39;max-age=315360000; includeSubDomains; preload&#39;, &#39;Date&#39;: &#39;Thu, 08 Apr 2021 11:29:10 GMT&#39;, &#39;ATL-TraceId&#39;: &#39;15abd1adc439007c&#39;, &#39;x-arequestid&#39;: &#39;4a79ab9f-7ee4-4d11-96f8-0773aff1cb3c&#39;, &#39;x-aaccountid&#39;: &#39;5fb3b1e04a09640069cd8add&#39;, &#39;X-XSS-Protection&#39;: &#39;1; mode=block&#39;, &#39;Transfer-Encoding&#39;: &#39;chunked&#39;, &#39;timing-allow-origin&#39;: &#39;*&#39;, &#39;x-envoy-upstream-service-time&#39;: &#39;38&#39;, &#39;X-Content-Type-Options&#39;: &#39;nosniff&#39;, &#39;micros-issuer&#39;: &#39;micros/edge-authenticator&#39;, &#39;Connection&#39;: &#39;keep-alive&#39;, &#39;set-cookie&#39;: &#39;atlassian.xsrf.token=c1696a7d-832f-45ef-9c1c-f25c98ea3608_4c697bc7b7a44eaf37abb50e35a18111566e6bd6_lin; Path=/; Secure&#39;, &#39;Expect-CT&#39;: &#39;report-uri=&quot;https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy&quot;, enforce, max-age=86400&#39;}
uwsgi_1         | 	response text = {&quot;errorMessages&quot;:[&quot;Ошибка доступа&quot;],&quot;errors&quot;:{}}</li></ul></li></ul>
```

## Steps to reproduce
1. Open Jira config editor
2. Fill the fields and try to save it

## Environment information**
DefectDojo 1.14.0

## Expected behavior
Jira config successfully save.

**Comment by whitespots** [comment]
Approved issue.

**Comment by valentijnscholten** [comment]
In 1.14.0 we added `validate=True` to the call that checks credentials in JIRA. Could be that doesn't work when an api token is supplied in the password field.

**Comment by valentijnscholten** [comment]
Fixed and released in 1.14.1: https://github.com/DefectDojo/django-DefectDojo/releases/tag/1.14.1
Thanks for reporting, can you confirm it works also for you in 1.14.1?
