### ISSUE TITLE
Crash in intializer with Docker container 1.14.1 (investigating)

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4242]
**Bug description**
Try to upgrade to `1.14.1` from `1.12.1` by modifying docker-compose definition file.

**Steps to reproduce**

**Expected behavior**

**Deployment method**
Docker

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'drf_yasg2'
```

**Additional context** (optional)

**Comment by damiencarol** [comment]
had an out-of-date settings file

**Comment by valentijnscholten** [comment]
always try to use `local_settings.py` to customize your instance ;-) it survives upgrades :-)

**Comment by damiencarol** [comment]
yeah. I think it's the time to switch to it!
