### ISSUE TITLE
Mass dedupe bombs out if more than 400K findings

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4276]
**Bug description**
RabbitMQ memory gets filled and basically it OOMs.
CPU is also maxed out, which starves rabbitMQ.

```
{"message": "deduplicating 421000 out of 1229843 models processed ...", "time": "2021-04-14T13:02:23.667482"}
{"message": "deduplicating 422000 out of 1229843 models processed ...", "time": "2021-04-14T13:02:24.602775"}
{"message": "deduplicating 423000 out of 1229843 models processed ...", "time": "2021-04-14T13:02:25.518451"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 533, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 1758, in _basic_publish
    self.connection.drain_events(timeout=0)
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 513, in blocking_read
    frame = self.transport.read_frame()
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 253, in read_frame
    frame_header = read(7, True)
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 459, in _read
    s = recv(n - len(rbuf))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 138, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 554, in _ensured
    reraise_as_library_errors=False,
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 445, in _ensure_connection
    callback, timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 874, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 809, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 149, in _connect
    "failed to resolve broker hostname"))
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/dojo/management/commands/dedupe.py", line 70, in handle
    mass_model_updater(Finding, findings.only('id'), lambda f: do_dedupe_finding_task(f.id), order='desc', log_prefix='deduplicating ')
  File "/app/dojo/utils.py", line 1968, in mass_model_updater
    function(model)
  File "/app/dojo/management/commands/dedupe.py", line 70, in <lambda>
    mass_model_updater(Finding, findings.only('id'), lambda f: do_dedupe_finding_task(f.id), order='desc', log_prefix='deduplicating ')
  File "/app/dojo/decorators.py", line 67, in __wrapper__
    return func(*args, **kwargs)
  File "/app/dojo/decorators.py", line 38, in __wrapper__
    return func.delay(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 566, in _ensured
    errback and errback(exc, 0)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 459, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 554, in _ensured
    reraise_as_library_errors=False,
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 445, in _ensure_connection
    callback, timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 874, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 809, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 149, in _connect
    "failed to resolve broker hostname"))
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
kombu.exceptions.OperationalError: timed out
command terminated with exit code 1
```

**Steps to reproduce**

**Expected behavior**
Dedupe continues to a successful completion.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by madchap** [comment]
Turns out that rabbitmq thinks it's got more memory than the system has, at least when running on my pods.

I set an absolute limit to memory, such as:

```
$ k exec -ti defectdojo-rabbitmq-0 -- bash -c 'rabbitmqctl set_vm_memory_high_watermark absolute 2048MiB'
Setting memory threshold on rabbit@defectdojo-rabbitmq-0.defectdojo-rabbitmq-headless.defectdojo.svc.cluster.local to 2048MiB bytes ...
```

and it seems to churn along. I will check on how this can be configurable, there does not seem to have a envvar available for that setting.
