### ISSUE TITLE
500 when adding manually a finding

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4341]
**Bug description**
```
ERROR:django.request:Internal Server Error: /test/4546/add_findings
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/authorization/authorization_decorators.py", line 39, in _wrapped
    return func(request, *args, **kwargs)
  File "./dojo/test/views.py", line 486, in add_findings
    jform = JIRAFindingForm(push_all=jira_helper.is_push_all_issues(test), prefix='jiraform', jira_project=jira_helper.get_jira_project(test), finding_form=form)
  File "./dojo/forms.py", line 2283, in __init__
    if self.instance.has_jira_group_issue:
AttributeError: 'NoneType' object has no attribute 'has_jira_group_issue'
```

**Steps to reproduce**
Create a finding manually within a test.

**Comment by madchap** [comment]
Apparently fixed a bit later.
