### ISSUE TITLE
migration failing due to 2nd engagement_type removal migration

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4432]
**Bug description**
```
initializer_1   | wait-for-it.sh: mysql:3306 is available after 15 seconds
initializer_1   | Initializing.
initializer_1   | [03/May/2021 09:26:52] INFO [dojo.models:3469] enabling audit logging
initializer_1   | Waiting for database to be reachable 
initializer_1   | Making migrations
initializer_1   | [03/May/2021 09:26:53] INFO [dojo.models:3469] enabling audit logging
initializer_1   | Traceback (most recent call last):
initializer_1   |   File "manage.py", line 11, in <module>
initializer_1   |     execute_from_command_line(sys.argv)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
initializer_1   |     utility.execute()
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
initializer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
initializer_1   |     self.execute(*args, **cmd_options)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
initializer_1   |     output = self.handle(*args, **options)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
initializer_1   |     res = handle_func(*args, **kwargs)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 141, in handle
initializer_1   |     loader.project_state(),
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 324, in project_state
initializer_1   |     return self.graph.make_state(nodes=nodes, at_end=at_end, real_apps=list(self.unmigrated_apps))
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/graph.py", line 315, in make_state
initializer_1   |     project_state = self.nodes[node].mutate_state(project_state, preserve=False)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 87, in mutate_state
initializer_1   |     operation.state_forwards(self.app_label, new_state)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 172, in state_forwards
initializer_1   |     delay = not old_field.is_relation
initializer_1   | AttributeError: 'NoneType' object has no attribute 'is_relation'
```

**Comment by madchap** [comment]
Caused by duplicated migration file. Fixed normally (directly committed).
