### ISSUE TITLE
Setting a duplicate results in 500 when viewing test

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4448]
**Bug description**
Playing with setting and unsetting duplicate in the view_finding, edit_finding views.

I was on a finding which was "inactive, duplicate" (test number 2)
I reset the finding's duplicate status, then becomes active.
In similar finding, I set a duplicate status to some other finding (had only 1 choice in this case, in a different test, same product, same engagement)
I navigate back to the list of findings (view_test number 2),  and got the stacktrace below.
Other tests listing work ok

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
dev

**Console logs** (optional)
```
Template error:
In template /app/dojo/templates/base.html, error at line 0
   '<' not supported between instances of 'NoneType' and 'int'
   1 : {% load navigation_tags %}
   2 : {% load display_tags %}
   3 : {% load authorization_tags %}
   4 : {% load static %}
   5 : <!DOCTYPE html>
   6 : <html lang="en">
   7 : 
   8 : <head>
   9 : 
   10 :     <meta charset="utf-8">


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "./dojo/authorization/authorization_decorators.py", line 39, in _wrapped
    return func(request, *args, **kwargs)
  File "./dojo/test/views.py", line 169, in view_test
    return render(request, 'dojo/view_test.html',
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "./dojo/templatetags/display_tags.py", line 244, in finding_sla
    find_sla = finding.sla_days_remaining()
  File "./dojo/models.py", line 2327, in sla_days_remaining
    return self.sla_days_remaining_internal
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "./dojo/models.py", line 2324, in sla_days_remaining_internal
    return min([find.sla_days_remaining() for find in self.findings.all()])

Exception Type: TypeError at /test/2
Exception Value: '<' not supported between instances of 'NoneType' and 'int'
```

**Additional context** (optional)

**Comment by madchap** [comment]
ah, that's the thing you fixed in https://github.com/DefectDojo/django-DefectDojo/pull/4353 earlier. I will close this with that note.
