### ISSUE TITLE
Survey seems to be broken on dev

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4597]
![image](https://user-images.githubusercontent.com/1694940/120452323-6ad64180-c392-11eb-8365-7e39b4f849c5.png)

**Comment by Maffooch** [comment]
Hi @damiencarol I just installed a fresh dev instance and navigated to `http://localhost:8080/questionnaire` and did not receive any error.
Could you either provide more info about this issue or try to reproduce again?

I have a feeling the import_surveys management command did not run properly. Running that [script](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/management/commands/import_surveys.py) might fix your problem.

**Comment by damiencarol** [comment]
@Maffooch saw something interesting in the logs:

```
initializer_1   | Traceback (most recent call last):
initializer_1   |   File "manage.py", line 11, in <module>
initializer_1   |     execute_from_command_line(sys.argv)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
initializer_1   |     utility.execute()
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
initializer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
initializer_1   |     self.execute(*args, **cmd_options)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
initializer_1   |     output = self.handle(*args, **options)
initializer_1   |   File "/app/dojo/management/commands/import_surveys.py", line 40, in handle
initializer_1   |     with open(path, "wt") as fout:
initializer_1   | PermissionError: [Errno 13] Permission denied: '/app/dojo/fixtures/initial_surveys.json'
initializer_1   | Importing fixtures all at once
initializer_1   | [20/Jun/2021 13:05:18] INFO [dojo.models:3613] enabling audit logging
initializer_1   | Installed 954 object(s) from 12 fixture(s)
initializer_1   | [20/Jun/2021 13:05:23] INFO [dojo.models:3613] enabling audit logging
initializer_1   | Importing extra fixtures
initializer_1   | ls: cannot access 'dojo/fixtures/extra_*.json': No such file or directory
initializer_1   | Installing watson search index
```

**Comment by damiencarol** [comment]
@Maffooch I used a fresh install (`dev`, no modifications)

**Comment by Maffooch** [comment]
Hmm I just tried again as well with a fresh copy of dev.. Not sure what is going on here? Weird thing is that both our installs install 952 fixtures. 
```
initializer_1   | Admin user: admin
initializer_1   | [20/Jun/2021 15:10:41] INFO [dojo.models:3353] enabling audit logging
initializer_1   | JIRA Webhook Secret: 1cb6b1e5-6c20-4302-a424-5316f4550973
initializer_1   | [20/Jun/2021 15:10:43] INFO [dojo.models:3353] enabling audit logging
initializer_1   | Preparing survey fixture
initializer_1   | [20/Jun/2021 15:10:44] INFO [dojo.models:3353] enabling audit logging
initializer_1   | Importing fixtures all at once
initializer_1   | [20/Jun/2021 15:10:48] INFO [dojo.models:3353] enabling audit logging
rabbitmq_1      | 2021-06-20 15:10:52.674 [info] <0.960.0> accepting AMQP connection <0.960.0> (172.20.0.4:54108 -> 172.20.0.2:5672)
rabbitmq_1      | 2021-06-20 15:10:52.678 [info] <0.960.0> connection <0.960.0> (172.20.0.4:54108 -> 172.20.0.2:5672): user 'guest' authenticated and granted access to vhost '/'
celerybeat_1    | [20/Jun/2021 15:10:52] INFO [celery.beat:271] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
celeryworker_1  | [20/Jun/2021 15:10:52] INFO [celery.worker.strategy:157] Received task: dojo.tasks.async_dupe_delete[9d5ae987-21d9-42a7-a23b-93c3c33104d6]  
celeryworker_1  | [20/Jun/2021 15:10:52] INFO [celery.app.trace:125] Task dojo.tasks.async_dupe_delete[9d5ae987-21d9-42a7-a23b-93c3c33104d6] succeeded in 0.006171999993966892s: None
initializer_1   | Installed 952 object(s) from 12 fixture(s)
initializer_1   | [20/Jun/2021 15:10:55] INFO [dojo.models:3353] enabling audit logging
initializer_1   | Importing extra fixtures
initializer_1   | ls: cannot access 'dojo/fixtures/extra_*.json': No such file or directory
initializer_1   | Installing watson search index
initializer_1   | [20/Jun/2021 15:10:56] INFO [dojo.models:3353] enabling audit logging
dev_initializer_1 exited with code 0
```

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/46459665/122679440-7908c800-d1b0-11eb-86a2-8ad9c7c60ee5.png">

**Comment by damiencarol** [comment]
I think `Installed 954 object(s) from 12 fixture(s)` come from:
https://github.com/DefectDojo/django-DefectDojo/blob/4a9a4e46525874e89daa2d677679bbbe1a89494c/docker/entrypoint-initializer.sh#L94-L97

So I guess this part works the some for both of us (so we have the same log messages).

I think I will close this one. It seems that my local branch is maybe corrupt/different.
