### ISSUE TITLE
Jira integration - AttributeError: 'list' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by maskimfr** [DefectDojo/django-DefectDojo#471]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
When trying to export issues to Jira from a Nessus scan, the issue is not created and an error is shown on celery logs.

### Operating System 
Ubuntu 16.04 x64

### Install

- [X] setup.bash
- [ ] docker

### Steps to Reproduce
  1. Create a Jira configuration
  2. Create a product
  3.  Create an engagement, select 'push to Jira" and done
  4. Add a test 
  5.  Create a finding
  6. Check celery logs

### Console Logs (optional)
```
[2018-02-19 09:51:12,445: INFO/ForkPoolWorker-2] add_epic_task[654aa343-ac37-40b3-aa4d-ae072b4fb638]: add epic task
[2018-02-19 09:51:12,484: INFO/ForkPoolWorker-2] Task add_epic_task[654aa343-ac37-40b3-aa4d-ae072b4fb638] succeeded in 0.0476739830337s: None
[2018-02-19 09:59:13,698: INFO/ForkPoolWorker-2] add_issue_task[adb6e238-b7ef-48f6-aca5-ed27bbbd0972]: add issue task
[2018-02-19 09:59:17,586: ERROR/ForkPoolWorker-2] Task add_issue_task[adb6e238-b7ef-48f6-aca5-ed27bbbd0972] raised unexpected: AttributeError("'list' object has no attribute 'iteritems'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/django-DefectDojo/dojo/tasks.py", line 201, in add_issue_task
    add_issue(find, push_to_jira)
  File "/usr/local/django-DefectDojo/dojo/utils.py", line 755, in add_issue
    priority={'name': jira_conf.get_priority(find.severity)})
  File "/usr/local/lib/python2.7/dist-packages/jira/client.py", line 929, in create_issue
    data['fields']['project'] = {'id': self.project(p).id}
  File "/usr/local/lib/python2.7/dist-packages/jira/client.py", line 1706, in project
    return self._find_for_resource(Project, id)
  File "/usr/local/lib/python2.7/dist-packages/jira/client.py", line 2368, in _find_for_resource
    resource.find(id=ids, params=params)
  File "/usr/local/lib/python2.7/dist-packages/jira/resources.py", line 200, in find
    self._load(url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/jira/resources.py", line 324, in _load
    self._parse_raw(j)
  File "/usr/local/lib/python2.7/dist-packages/jira/resources.py", line 330, in _parse_raw
    dict2resource(raw, self, self._options, self._session)
  File "/usr/local/lib/python2.7/dist-packages/jira/resources.py", line 893, in dict2resource
    for i, j in iteritems(raw):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 605, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'
```

**Comment by devGregA** [comment]
@maskimfr are you still having this issue with the new 1.5.2?
