### ISSUE TITLE
Internal Server Error on adding a group: `TypeError: sequence item 0: expected str instance, NoneType found`

### ISSUE THREAD

**Issue by AndreyMZ** [DefectDojo/django-DefectDojo#4786]
### Steps to reproduce
1. Create a new _Finding_ with _Component name_ but without _Component version_.
2. Create a new _Group_ with this finding.

### Actual result
~~~
[08/Jul/2021 11:36:59] ERROR [django.request:230] Internal Server Error: /test/2741
Traceback (most recent call last):
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'Finding_Group' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\GIT\DefectDojo\dojo\authorization\authorization_decorators.py", line 39, in _wrapped
    return func(request, *args, **kwargs)
  File "C:\GIT\DefectDojo\dojo\test\views.py", line 192, in view_test
    'finding_group_by_options': Finding_Group.GROUP_BY_OPTIONS,
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\GIT\DefectDojo\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\GIT\DefectDojo\dojo\models.py", line 2480, in components
    return ','.join([key + ':' + ', '.join(value) for key, value in components.items() if key and value])
  File "C:\GIT\DefectDojo\dojo\models.py", line 2480, in <listcomp>
    return ','.join([key + ':' + ', '.join(value) for key, value in components.items() if key and value])
TypeError: sequence item 0: expected str instance, NoneType found
~~~

### Expected result
No errors.

**Comment by StefanFl** [comment]
PR has been merged
