### ISSUE TITLE
Jira reconciliation exception

### ISSUE THREAD

**Issue by rituraj-gaur** [DefectDojo/django-DefectDojo#4856]
**Expected behavior**
Expected the CSV to be generated as mentioned at https://defectdojo.github.io/django-DefectDojo/integrations/jira/#status-reconciliation

**Deployment method** *(select with an `X`)*
- [X ] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Console logs** (optional)
sudo docker-compose exec uwsgi /bin/bash -c 'python manage.py jira_status_reconciliation -v 3'
[23/Jul/2021 09:40:15] INFO [dojo.models:3613] enabling audit logging
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/dojo/management/commands/jira_status_reconciliation.py", line 231, in handle
    return jira_status_reconciliation(*args, **options)
  File "/app/dojo/management/commands/jira_status_reconciliation.py", line 146, in jira_status_reconciliation
    status_changed = jira_helper.process_resolution_from_jira(find, resolution_id, resolution_name, assignee_name, issue_from_jira.fields.updated) if not dryrun else 'dryrun'
TypeError: process_resolution_from_jira() missing 1 required positional argument: 'jira_issue'

**Additional context** (optional)
1-way jira integration is working fine (as expected) HOWEVER once the issue is updated at JIRA,  does not updates the findings status at  defect dojo. Thus I was trying to use reconciliation module.

**Comment by tonnyhideyori** [comment]
I am facing the same issue

**Comment by damiencarol** [comment]
@tonnyhideyori which version do you use?

**Comment by fuzzah** [comment]
Same issue here.
docker-compose, version 2.13.1 (release)
Stack trace looks the same.

**Comment by celonis-eg** [comment]
Having the same issue as well on 2.16.2 of Dojo. Management script says "3.2.16" for version.
