### ISSUE TITLE
Hitting "Server Error 500" when login with Gitlab + auto import repositories!

### ISSUE THREAD

**Issue by bl4ckbo7** [DefectDojo/django-DefectDojo#4907]
nginx_1         | x.x.x.x:yyyy - - [03/Aug/2021:17:10:19 +0000] "GET /login/gitlab/?next=/ HTTP/1.1" 302 0 "http://x.x.x.x:yyyy/login?next=/" "Mozilla/5.0 (X11; Linux x86_64; rv
:78.0) Gecko/20100101 Firefox/78.0" "-"
uwsgi_1         | [pid: 16|app: 0|req: 1/2] x.x.x.x:yyyy () {44 vars in 1347 bytes} [Tue Aug  3 17:10:17 2021] GET /login/gitlab/?next=/ => generated 0 bytes in 1963 msecs (HTTP/1.1 
302) 11 headers in 799 bytes (1 switches on core 0)
uwsgi_1         | [03/Aug/2021 17:10:20] ERROR [django.request:224] Internal Server Error: /complete/gitlab/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
uwsgi_1         |     return self.get(**kwargs), False
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
uwsgi_1         |     raise self.model.DoesNotExist(
uwsgi_1         | dojo.models.Product_Member.DoesNotExist: Product_Member matching query does not exist.
uwsgi_1         | 
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.OperationalError: (1048, "Column 'role_id' cannot be null")
uwsgi_1         | 
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1         |     return view_func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_django/utils.py", line 49, in wrapper
uwsgi_1         |     return func(request, backend, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_django/views.py", line 31, in complete
uwsgi_1         |     return do_complete(request.backend, _do_login, user=request.user,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/actions.py", line 45, in do_complete
uwsgi_1         |     user = backend.complete(user=user, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 40, in complete
uwsgi_1         |     return self.auth_complete(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 248, in wrapper
uwsgi_1         |     return func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 391, in auth_complete
uwsgi_1         |     return self.do_auth(response['access_token'], response=response,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 248, in wrapper
uwsgi_1         |     return func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 403, in do_auth
uwsgi_1         |     return self.strategy.authenticate(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_django/strategy.py", line 107, in authenticate
uwsgi_1         |     return authenticate(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
uwsgi_1         |     user = backend.authenticate(request, **credentials)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 80, in authenticate
uwsgi_1         |     return self.pipeline(pipeline, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 83, in pipeline
uwsgi_1         |     out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 113, in run_pipeline
uwsgi_1         |     result = func(*args, **out) or {}
uwsgi_1         |   File "/app/./dojo/pipeline.py", line 92, in update_product_access
uwsgi_1         |     product_member, created = Product_Member.objects.get_or_create(product=product, user=user)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
uwsgi_1         |     return self._create_object_from_params(kwargs, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
uwsgi_1         |     obj = self.create(**params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
uwsgi_1         |     obj.save(force_insert=True, using=self.db)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
uwsgi_1         |     self.save_base(using=using, force_insert=force_insert,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
uwsgi_1         |     updated = self._save_table(
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
uwsgi_1         |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
uwsgi_1         |     return manager._insert(
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
uwsgi_1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 78, in execute
uwsgi_1         |     raise IntegrityError(*tuple(e.args))
uwsgi_1         | django.db.utils.IntegrityError: (1048, "Column 'role_id' cannot be null")
uwsgi_1         | ERROR:django.request:Internal Server Error: /complete/gitlab/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
uwsgi_1         |     return self.get(**kwargs), False
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
uwsgi_1         |     raise self.model.DoesNotExist(
uwsgi_1         | dojo.models.Product_Member.DoesNotExist: Product_Member matching query does not exist.
uwsgi_1         | 
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.OperationalError: (1048, "Column 'role_id' cannot be null")
uwsgi_1         | 
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1         |     return view_func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_django/utils.py", line 49, in wrapper
uwsgi_1         |     return func(request, backend, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_django/views.py", line 31, in complete
uwsgi_1         |     return do_complete(request.backend, _do_login, user=request.user,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/actions.py", line 45, in do_complete
uwsgi_1         |     user = backend.complete(user=user, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 40, in complete
uwsgi_1         |     return self.auth_complete(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 248, in wrapper
uwsgi_1         |     return func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 391, in auth_complete
uwsgi_1         |     return self.do_auth(response['access_token'], response=response,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 248, in wrapper
uwsgi_1         |     return func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 403, in do_auth
uwsgi_1         |     return self.strategy.authenticate(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_django/strategy.py", line 107, in authenticate
uwsgi_1         |     return authenticate(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
uwsgi_1         |     user = backend.authenticate(request, **credentials)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 80, in authenticate
uwsgi_1         |     return self.pipeline(pipeline, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 83, in pipeline
uwsgi_1         |     out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 113, in run_pipeline
uwsgi_1         |     result = func(*args, **out) or {}
uwsgi_1         |   File "/app/./dojo/pipeline.py", line 92, in update_product_access
uwsgi_1         |     product_member, created = Product_Member.objects.get_or_create(product=product, user=user)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
uwsgi_1         |     return self._create_object_from_params(kwargs, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
uwsgi_1         |     obj = self.create(**params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
uwsgi_1         |     obj.save(force_insert=True, using=self.db)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
uwsgi_1         |     self.save_base(using=using, force_insert=force_insert,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
uwsgi_1         |     updated = self._save_table(
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
uwsgi_1         |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
uwsgi_1         |     return manager._insert(
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
uwsgi_1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 78, in execute
uwsgi_1         |     raise IntegrityError(*tuple(e.args))
uwsgi_1         | django.db.utils.IntegrityError: (1048, "Column 'role_id' cannot be null")
uwsgi_1         | [pid: 16|app: 0|req: 2/3] x.x.x.x:yyyy () {44 vars in 1540 bytes} [Tue Aug  3 17:10:19 2021] GET /complete/gitlab/?code=c147038c69f3469e1ca57df0540b9eb2ddbed3a31a18
5862c018643baa9db3f3&state=DGhmTFjyESsaoKaSIuxVRGQiru2FPphy => generated 145 bytes in 1845 msecs (HTTP/1.1 500) 7 headers in 217 bytes (1 switches on core 1)
nginx_1         | x.x.x.x:yyyy - - [03/Aug/2021:17:10:21 +0000] "GET /complete/gitlab/?code=c147038c69f3469e1ca57df0540b9eb2ddbed3a31a185862c018643baa9db3f3&state=DGhmTFjyESsaoKaSIux
VRGQiru2FPphy HTTP/1.1" 500 145 "http://x.x.x.x:yyyy/" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"

**Comment by bl4ckbo7** [comment]
OS: Ubuntu 20.04
DefectDojo: 2.0.3 (release)
Python: 3
godojo: 1.1.4

**Comment by bl4ckbo7** [comment]
The error doesn't show up when I set,     

`DD_SOCIAL_AUTH_GITLAB_PROJECT_AUTO_IMPORT = False`

**Comment by bl4ckbo7** [comment]
Sorry, seems to be fixed in latest version DefectDojo 2.1.0. Thanks.
