### ISSUE TITLE
add docs for smtp with (start)tls

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#5112]
https://owasp.slack.com/archives/C2P5BA8MN/p1631796429185200
```
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/./dojo/notifications/helper.py", line 281, in send_mail_notification
uwsgi_1         |     email.send(fail_silently=False)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
uwsgi_1         |     return self.get_connection(fail_silently).send_messages([self])
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
uwsgi_1         |     sent = self._send(message)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
uwsgi_1         |     self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
uwsgi_1         |   File "/usr/local/lib/python3.8/smtplib.py", line 880, in sendmail
uwsgi_1         |     raise SMTPSenderRefused(code, resp, from_addr)
uwsgi_1         | smtplib.SMTPSenderRefused: (530, b'5.7.0 Must issue a STARTTLS command first', 'defectdojo')
```

**Comment by vishnupriyaavp8** [comment]
I am getting 'No authentication method found' in my notification alerts. Is it the same issue? Is there any work around?
