### ISSUE TITLE
OWASP ZAP Report parser error

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#5228]
**Slack us first!**

**Be informative**
API Import of ZAP Report return 500 Error. 

@damiencarol  I know that you are writing new parser for OWASP ZAP. I think you should consider the error that I'm getting now.(DEfect dojo 2.1.0)

**Bug description**
Get 500 error when uploading OWASP ZAP:
```html
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

Error log:
```
uwsgi_1         |   warnings.warn("DateTimeField %s.%s received a naive datetime "
uwsgi_1         | [06/Oct/2021 07:44:06] ERROR [dojo.importers.utils:27] can only concatenate str (not "NoneType") to str
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 25, in get_findings
uwsgi_1         |     return self.get_items(tree, test)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 34, in get_items
uwsgi_1         |     site = Site(node)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 105, in __init__
uwsgi_1         |     self.items.append(Item(alert))
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 165, in __init__
uwsgi_1         |     description_detail += "Parameter: " + node.text
uwsgi_1         | TypeError: can only concatenate str (not "NoneType") to str
uwsgi_1         | [06/Oct/2021 07:44:06] WARNING [dojo.importers.utils:28] Error in parser: can only concatenate str (not "NoneType") to str
uwsgi_1         | [06/Oct/2021 07:44:06] ERROR [django.request:224] Internal Server Error: /api/v2/import-scan/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1         |     return view_func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
uwsgi_1         |     response = self.handle_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
uwsgi_1         |     self.raise_uncaught_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
uwsgi_1         |     raise exc
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
uwsgi_1         |     response = handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
uwsgi_1         |     self.perform_create(serializer)
uwsgi_1         |   File "/app/./dojo/api_v2/views.py", line 1867, in perform_create
uwsgi_1         |     serializer.save(push_to_jira=push_to_jira)
uwsgi_1         |   File "/app/./dojo/api_v2/serializers.py", line 1216, in save
uwsgi_1         |     test, finding_count, closed_finding_count = importer.import_scan(scan, scan_type, engagement, lead, environment,
uwsgi_1         |   File "/app/./dojo/importers/importer/importer.py", line 290, in import_scan
uwsgi_1         |     parsed_findings = importer_utils.parse_findings(scan, test, active, verified, scan_type)
uwsgi_1         |   File "/app/./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 25, in get_findings
uwsgi_1         |     return self.get_items(tree, test)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 34, in get_items
uwsgi_1         |     site = Site(node)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 105, in __init__
uwsgi_1         |     self.items.append(Item(alert))
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 165, in __init__
uwsgi_1         |     description_detail += "Parameter: " + node.text
uwsgi_1         | TypeError: can only concatenate str (not "NoneType") to str
nginx_1         | 172.21.0.1 - - [06/Oct/2021:07:44:06 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 500 145 "http://defect-dojo.local/api/v2/doc/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
uwsgi_1         | ERROR:django.request:Internal Server Error: /api/v2/import-scan/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1         |     return view_func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
uwsgi_1         |     response = self.handle_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
uwsgi_1         |     self.raise_uncaught_exception(exc)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
uwsgi_1         |     raise exc
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
uwsgi_1         |     response = handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
uwsgi_1         |     self.perform_create(serializer)
uwsgi_1         |   File "/app/./dojo/api_v2/views.py", line 1867, in perform_create
uwsgi_1         |     serializer.save(push_to_jira=push_to_jira)
uwsgi_1         |   File "/app/./dojo/api_v2/serializers.py", line 1216, in save
uwsgi_1         |     test, finding_count, closed_finding_count = importer.import_scan(scan, scan_type, engagement, lead, environment,
uwsgi_1         |   File "/app/./dojo/importers/importer/importer.py", line 290, in import_scan
uwsgi_1         |     parsed_findings = importer_utils.parse_findings(scan, test, active, verified, scan_type)
uwsgi_1         |   File "/app/./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 25, in get_findings
uwsgi_1         |     return self.get_items(tree, test)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 34, in get_items
uwsgi_1         |     site = Site(node)
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 105, in __init__
uwsgi_1         |     self.items.append(Item(alert))
uwsgi_1         |   File "/app/./dojo/tools/zap/parser.py", line 165, in __init__
uwsgi_1         |     description_detail += "Parameter: " + node.text
uwsgi_1         | TypeError: can only concatenate str (not "NoneType") to str
```

Sample file into attach

**Steps to reproduce**
1. Go to API
2. Import attached report as ZAP Scan
3. See error

**Expected behavior**
No error for samplefile. 

**Deployment method** *(select with an `X`)*
- [ `X` ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**

[tip_owasp_zap.txt](https://github.com/DefectDojo/django-DefectDojo/files/7292022/tip_owasp_zap.txt)

**Screenshots**

**Additional context** (optional)

**Comment by zakrush** [comment]
Check on v. 2.4.0-dev ( 381c7a3e ) 
It's not reproducible

**Comment by damiencarol** [comment]
it's embarrassing. I can't reproduce the bug on `2.2.1` or in `dev` (2021-10-06)

**Comment by zakrush** [comment]
Yes. I'l close it/
