### ISSUE TITLE
promoting potential findings (stub_finding) - NoAuthorizationImplementedError

### ISSUE THREAD

**Issue by t51** [DefectDojo/django-DefectDojo#5277]
**Bug description**
User Details:
Active, Staff = Ticked
Global Role = Owner

When trying to a 'Potential Finding' within the Test page, the application returns an error.
NoAuthorizationImplementedError at /stub_finding/71/promote
No authorization implemented for class Stub_Finding and permission 1406

Temporary workaround: 
set DD_AUTHORIZATION_STAFF_OVERRIDE=True
OR 
set user as SUPERUSER.

Traceback:
Request Method: GET
Request URL: https://ip/stub_finding/71/promote

Django Version: 3.1.13
Python Version: 3.8.12
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'auditlog',
 'dojo',
 'watson',
 'tagging',
 'imagekit',
 'multiselectfield',
 'rest_framework',
 'rest_framework.authtoken',
 'dbbackup',
 'django_celery_results',
 'social_django',
 'drf_yasg',
 'drf_spectacular',
 'tagulous')
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'dojo.middleware.DojoSytemSettingsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'watson.middleware.SearchContextMiddleware',
 'auditlog.middleware.AuditlogMiddleware',
 'crum.CurrentRequestUserMiddleware',
 'dojo.request_cache.middleware.RequestCacheMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/./dojo/authorization/authorization_decorators.py", line 31, in _wrapped
    user_has_permission_or_403(request.user, obj, permission)
  File "/app/./dojo/authorization/authorization.py", line 97, in user_has_permission_or_403
    if not user_has_permission(user, obj, permission):
  File "/app/./dojo/authorization/authorization.py", line 92, in user_has_permission
    raise NoAuthorizationImplementedError('No authorization implemented for class {} and permission {}'.

Exception Type: NoAuthorizationImplementedError at /stub_finding/71/promote
Exception Value: No authorization implemented for class Stub_Finding and permission 1406

**Steps to reproduce**
1. Go to 'Product' > 'Engagement' > 'Test'
2. Add 'Add a potential finding...'
3. Click 'Promote To Finding'
4. Should Error

**Expected behavior**
Directed to a Findings page to enter additional details.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose

**Environment information**
 - DefectDojo version 2.3.0

**Comment by t51** [comment]
Thank you
