### ISSUE TITLE
./manage.py collectstatic --noinput error when migrating to 1.2.9

### ISSUE THREAD

**Issue by maskimfr** [DefectDojo/django-DefectDojo#553]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

./manage.py collectstatic crash when migrating to 1.2.9 from 1.2.6.

### Operating System 
Ubuntu 16.04, fully patched

### Install

- [x] setup.bash
- [ ] docker

### Steps to Reproduce
The documentation for migration to 1.2.9 (https://defectdojo.readthedocs.io/en/latest/upgrading.html) states that the following command should be launched, but it crash with an error:
```
./manage.py collectstatic -–noinput
/usr/lib/python2.7/argparse.py:2140: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if option_string == short_option_prefix:
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    options, args = parser.parse_known_args(self.argv[2:])
  File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1774, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/usr/lib/python2.7/argparse.py", line 2082, in _parse_optional
    option_tuples = self._get_option_tuples(arg_string)
  File "/usr/lib/python2.7/argparse.py", line 2144, in _get_option_tuples
    elif option_string.startswith(option_prefix):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```

Moreover, there is an error in the documentation, noinput parameter takes two dash, not one

**Comment by aaronweaver** [comment]
Fixed in dev will push to master shortly.
