### ISSUE TITLE
Internal Server Error - kubernetes

### ISSUE THREAD

**Issue by pgabriel10** [DefectDojo/django-DefectDojo#5725]
Hello,
I always receive error 500 Internal server error when I submit a finding or create a test.

Error ocorrer in https://defectdojo.xpto.com/test/34

The path with error /test/

I installed defect dojo  in Kubernets, bellow you can see the error. 

Any suggestions ?

```
[10/Jan/2022 19:57:53] ERROR [django.request:224] Internal Server Error: /test/34

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)
File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)
File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
db.query(q)
File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
_mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'dojo_system_settings.email_from' in 'field list'")
```

**Comment by dsever** [comment]
Can you check migrations with manage command? I don't think this is k8s specific

**Comment by damiencarol** [comment]
I think @dsever is right. it's a missing column in global settings table (in DB). check the migration log of the initializer container

**Comment by pgabriel10** [comment]
Thanks.

I was execute this command in Django:

`./manage.py migrate`
