### ISSUE TITLE
Issue with Metrics dashboard(/metrics) server error 500

### ISSUE THREAD

**Issue by iamwizard** [DefectDojo/django-DefectDojo#5813]
**Bug description**
There seems to be an issue with /metrics url. When we try to access the metrics dashboard we encounter Server error 500 with the error log shown below.

**Steps to reproduce**
1. Go to '/metrics' or 'metrics?date=5&view=dashboard' 
2. Click on 'Metrics from Side menu on the defectdojo homepage'
3. See error- Server Error (500)
4. Error log-
ERROR:django.request:Internal Server Error: /metrics
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/app-root/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "./dojo/metrics/views.py", line 467, in metrics
    closed_in_period_counts, closed_in_period_details = get_closed_in_period_details([
  File "./dojo/metrics/views.py", line 409, in get_closed_in_period_details
    closed_in_period_counts[obj.severity] += 1
KeyError: 'Information'
[pid: 1|app: 0|req: 5864/6908] serverAddr () {66 vars in 1505 bytes} [Mon Jan 24 09:24:52 2022] GET /metrics?date=5&view=dashboard => generated 145 bytes in 5278 msecs (HTTP/1.1 500) 7 headers in 217 bytes (1 switches on core 0)

**Expected behavior**
Metrics dashboard is expected as displayed on https://demo.defectdojo.org/metrics?date=5&view=dashboard

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]- RHEL 7.9
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]- 2.4.1

**Logs** 
ERROR:django.request:Internal Server Error: /metrics
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/app-root/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "./dojo/metrics/views.py", line 467, in metrics
    closed_in_period_counts, closed_in_period_details = get_closed_in_period_details([
  File "./dojo/metrics/views.py", line 409, in get_closed_in_period_details
    closed_in_period_counts[obj.severity] += 1
KeyError: 'Information'
[pid: 1|app: 0|req: 5864/6908] serverAddr () {66 vars in 1505 bytes} [Mon Jan 24 09:24:52 2022] GET /metrics?date=5&view=dashboard => generated 145 bytes in 5278 msecs (HTTP/1.1 500) 7 headers in 217 bytes (1 switches on core 0)

**Comment by valentijnscholten** [comment]
Looks more like you have a finding with an invalid `severity`. `Information` is not a valid value for `severity`. Can you try and debug where this finding came from (which parser for example)? Also please upgrade to 2.6.2 if possible.

**Comment by iamwizard** [comment]
Thanks @valentijnscholten It worked, there were some findings with Information severity and I have removed them. Also we will try to upgrade Defectdojo to latest version asap.
