### ISSUE TITLE
Native Keycloak SSO `ValueError`

### ISSUE THREAD

**Issue by mikeanth-dev** [DefectDojo/django-DefectDojo#5877]
**Bug description**

Upon configuring the Keycloak client and the DefectDojo helm chart as described in the [doc](https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#keycloak), SSO is not working. Pressing the `Login With Keycloak` button redirects me to a `Server Error (500)`

Keycloak client configuration:

1. Client Settings:

  - `Client ID`: defectdojo
  - `Enabled`: True
  - `Client Protocol`: openid-connect
  - `Access Type`: confidential
  - `Root URL`: https://{ defectdojo url }
  - `Valid Redirect URIs`:
      - https://{ defectdojo url }/*
  - `Admin URL`: https://{ defectdojo url }
  - `Web Origins`: https://{ defectdojo url }/*
  - `Backchannel Logout Session Required`: True

2.  Client Settings -> Fine Grain OpenID Connect Configuration
  - `User Info Signed Response Algorithm`: RS256
  - `Request Object Signature Algorithm`: RS256

3. Scope -> `Full Scope Allowed`: False
4. Mappers:
  - Name: aud
  - Mapper type: Audience
  - Included audience: defectdojo
  - Add ID to token: off
  - Add access to token: on

**Expected behavior**

Login via keycloak should ... well ... log me in

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: Chart 1.6.27

**Logs** 

```
Traceback (most recent call last):
--
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
Thu, Feb 3 2022 2:28:13 pm | response = get_response(request)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
Thu, Feb 3 2022 2:28:13 pm | response = wrapped_callback(request, *callback_args, **callback_kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
Thu, Feb 3 2022 2:28:13 pm | response = view_func(request, *args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Thu, Feb 3 2022 2:28:13 pm | return view_func(*args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_django/utils.py", line 46, in wrapper
Thu, Feb 3 2022 2:28:13 pm | return func(request, backend, *args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_django/views.py", line 31, in complete
Thu, Feb 3 2022 2:28:13 pm | return do_complete(request.backend, _do_login, user=request.user,
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/actions.py", line 45, in do_complete
Thu, Feb 3 2022 2:28:13 pm | user = backend.complete(user=user, *args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 40, in complete
Thu, Feb 3 2022 2:28:13 pm | return self.auth_complete(*args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 247, in wrapper
Thu, Feb 3 2022 2:28:13 pm | return func(*args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 391, in auth_complete
Thu, Feb 3 2022 2:28:13 pm | return self.do_auth(response['access_token'], response=response,
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 247, in wrapper
Thu, Feb 3 2022 2:28:13 pm | return func(*args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 397, in do_auth
Thu, Feb 3 2022 2:28:13 pm | data = self.user_data(access_token, *args, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/social_core/backends/keycloak.py", line 119, in user_data
Thu, Feb 3 2022 2:28:13 pm | return jwt.decode(
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
Thu, Feb 3 2022 2:28:13 pm | decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
Thu, Feb 3 2022 2:28:13 pm | decoded = api_jws.decode_complete(
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/jwt/api_jws.py", line 152, in decode_complete
Thu, Feb 3 2022 2:28:13 pm | self._verify_signature(signing_input, header, signature, key, algorithms)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/jwt/api_jws.py", line 236, in _verify_signature
Thu, Feb 3 2022 2:28:13 pm | key = alg_obj.prepare_key(key)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/jwt/algorithms.py", line 264, in prepare_key
Thu, Feb 3 2022 2:28:13 pm | key = load_pem_public_key(key)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 30, in load_pem_public_key
Thu, Feb 3 2022 2:28:13 pm | return ossl.load_pem_public_key(data)
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 853, in load_pem_public_key
Thu, Feb 3 2022 2:28:13 pm | self._handle_key_loading_error()
Thu, Feb 3 2022 2:28:13 pm | File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1094, in _handle_key_loading_error
Thu, Feb 3 2022 2:28:13 pm | raise ValueError(
Thu, Feb 3 2022 2:28:13 pm | ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
```

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by dsever** [comment]
From the trace it looks like public key loaded into env vars is wrong.  

https://github.com/DefectDojo/django-DefectDojo/pull/5726#discussion_r782148096

**Comment by mikeanth-dev** [comment]
Oh... silly mistake on my part. I updated the `extraConfig` and issues a helm upgrade, but the pods weren't restarted. Manually deleting them to force a restart solved my issue. Thanks

**Comment by dsever** [comment]
Anyway you can enable trackConfig in gel, then all dd containers will be restarted automatically on config change
