### ISSUE TITLE
Reimport break endpoint_status (problem of late deduplication of endpoint_statuses)

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#5943]
**Bug description**

After reimporting one of the reports which contain endpoints, I received HTTP-500. After some time (when deduplication in celery was done), everything was all right. 

**Steps to reproduce**
1. create Product
2. create Eng
3. import Test - [Gitlab DAST](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/gitlab_dast/gitlab_dast_one_vul.json)
4. reimport the same test
5. check the list of endpoints (pop-up bubble when you have the cursor over icon next to finding) - you can see the same endpoint twice
6. open finding - HTTP 500 - "MultipleObjectsReturned at /finding/1 get() returned more than one Endpoint_Status -- it returned 2!"
7. wait a minute (for deduplication in celery)
8. everything is fine

**Expected behavior**

No HTTP 500

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Commit message: `[2022-02-18 09:08:26 +0100] c9c5ae2cb: dc-up.sh: use correct message (#5934) [ (HEAD, upstream/dev)]`

**Logs** 
```python
django-defectdojo-uwsgi-1         | ERROR:django.request:Internal Server Error: /finding/1
django-defectdojo-uwsgi-1         | Traceback (most recent call last):
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
django-defectdojo-uwsgi-1         |     response = get_response(request)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
django-defectdojo-uwsgi-1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-defectdojo-uwsgi-1         |   File "/app/./dojo/authorization/authorization_decorators.py", line 30, in _wrapped
django-defectdojo-uwsgi-1         |     return func(request, *args, **kwargs)
django-defectdojo-uwsgi-1         |   File "/app/./dojo/finding/views.py", line 372, in view_finding
django-defectdojo-uwsgi-1         |     return render(
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
django-defectdojo-uwsgi-1         |     content = loader.render_to_string(template_name, context, request, using=using)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
django-defectdojo-uwsgi-1         |     return template.render(context, request)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
django-defectdojo-uwsgi-1         |     return self.template.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
django-defectdojo-uwsgi-1         |     return self._render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django-defectdojo-uwsgi-1         |     return self.nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
django-defectdojo-uwsgi-1         |     return compiled_parent._render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django-defectdojo-uwsgi-1         |     return self.nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
django-defectdojo-uwsgi-1         |     result = block.nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
django-defectdojo-uwsgi-1         |     return template.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
django-defectdojo-uwsgi-1         |     return self._render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
django-defectdojo-uwsgi-1         |     return self.nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
django-defectdojo-uwsgi-1         |     return nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 519, in render
django-defectdojo-uwsgi-1         |     return self.nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
django-defectdojo-uwsgi-1         |     return nodelist.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
django-defectdojo-uwsgi-1         |     bit = node.render_annotated(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 214, in render
django-defectdojo-uwsgi-1         |     nodelist.append(node.render_annotated(context))
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
django-defectdojo-uwsgi-1         |     return self.render(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
django-defectdojo-uwsgi-1         |     output = self.filter_expression.resolve(context)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 698, in resolve
django-defectdojo-uwsgi-1         |     new_obj = func(obj, *arg_vals)
django-defectdojo-uwsgi-1         |   File "/app/./dojo/templatetags/get_endpoint_status.py", line 25, in endpoint_display_status
django-defectdojo-uwsgi-1         |     status = Endpoint_Status.objects.get(endpoint=endpoint, finding=finding)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
django-defectdojo-uwsgi-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
django-defectdojo-uwsgi-1         |     raise self.model.MultipleObjectsReturned(
django-defectdojo-uwsgi-1         | dojo.models.Endpoint_Status.MultipleObjectsReturned: get() returned more than one Endpoint_Status -- it returned 2!
```

**Sample scan files**

https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/gitlab_dast/gitlab_dast_one_vul.json

**Comment by kiblik** [comment]
Ok, maybe it is not connected to Celery. I did it again and it is not resolving by time.
