### ISSUE TITLE
Getting 500 server error while downloading nessus scan file from defect dojo

### ISSUE THREAD

**Issue by vaisakh007** [DefectDojo/django-DefectDojo#5971]
**Bug description**
I have uploaded nessus scan file to defect dojo through api and uploaded successfully
When i try to download the same file from defect dojo UI, i am getting 500 error response

**Expected behavior**
File must be downloaded

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X ] Kubernetes
- [ ] GoDojo

**Environment information**
 - kubernetes v1.20
 - DefectDojo version v. 2.7.1 ( release mode )

**Logs** 
uwsgi pod logs as below

ERROR:django.request:Internal Server Error: /test/23
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column dojo_system_settings.default_group_email_pattern does not exist
LINE 1: ..., "dojo_system_settings"."default_group_role_id", "dojo_syst...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/app/./dojo/authorization/authorization_decorators.py", line 30, in _wrapped
    return func(request, *args, **kwargs)
  File "/app/./dojo/test/views.py", line 78, in view_test
    system_settings = get_object_or_404(System_Settings, id=1)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column dojo_system_settings.default_group_email_pattern does not exist
LINE 1: ..., "dojo_system_settings"."default_group_role_id", "dojo_syst...
                                                             ^

**Comment by vaisakh007** [comment]
this is indeed issue with initializer pod and issue is fixed
