### ISSUE TITLE
JIRA user needs to be there to get comments from JIRA

### ISSUE THREAD

**Issue by imohammedzen** [DefectDojo/django-DefectDojo#620]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
When you comment on JIRA ticket, webhook is sent to Dojo and as there is no default `JIRA` User it will fail with the following error. 

```
Internal Server Error: /webhook
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/vagrant/dojo/jira_link/views.py", line 72, in webhook
    new_note.author = User.objects.get(username='JIRA')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
```

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 16.04
### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
1.3.0

### Steps to Reproduce
1. Create a Jira configuration
2. Create a product
3. Create an engagement, select 'push to Jira" and done
4. Add a test
5. Create a finding
6. Go to JIRA issue related to an issue 
7. Comment on the Issue

#### Recommendation 1 
In file "dojo/jira_link/views.py", line 72, in webhook
Replace

```
     new_note.author = User.objects.get(username='JIRA')
```

with 

```
     new_note.author, created = User.objects.get_or_create(username='JIRA')
```

#### Recommendation 2 
Add `JIRA` user as part of fixtures

**Comment by coivase** [comment]
Hi @aaronweaver! Was this fixed and if so how? We are implementing Dojo now and are running into bidirectionality issues. Thank you!
