### ISSUE TITLE
checkmarx SAST value too long error

### ISSUE THREAD

**Issue by ptrovatelli** [DefectDojo/django-DefectDojo#6208]
**Bug description**
When trying to import checkmarx report that has many findings aggregated together (185 in my case), it's possible to reach the max lenght of `vuln_id_from_tool` in the database (500 characters)
```
[24/Feb/2022 08:43:57] ERROR [dojo.engagement.views:616] value too long for type character varying(500)
```

**Steps to reproduce**
Import the provided report with the gui or the api using "Checkmarx Scan" parser

Error obtained:
```
An exception error occurred during the report import:(1406, "Data too long for column 'vuln_id_from_tool' at row 1")
```

**Expected behavior**
The report should be imported

**Deployment method** *(select with an `X`)*
- [x ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
v. 2.10.0-dev ( b71c44f3 )

**Logs** 
```
celeryworker_1  | [28/Apr/2022 15:01:44] INFO [celery.app.trace:131] Task dojo.finding.helper.post_process_finding_save[d1c82eea-2aa1-4169-b2ea-f438af425861] succeeded in 0.030939600000010614s: None
uwsgi_1         | [28/Apr/2022 15:01:44] ERROR [dojo.engagement.views:627] (1406, "Data too long for column 'vuln_id_from_tool' at row 1")
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.DataError: (1406, "Data too long for column 'vuln_id_from_tool' at row 1")
uwsgi_1         |
uwsgi_1         | The above exception was the direct cause of the following exception:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/./dojo/engagement/views.py", line 612, in import_scan_results
uwsgi_1         |     test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
uwsgi_1         |   File "/app/./dojo/importers/importer/importer.py", line 323, in import_scan
uwsgi_1         |     new_findings = self.process_parsed_findings(test, parsed_findings, scan_type, user, active,
uwsgi_1         |   File "/app/./dojo/decorators.py", line 47, in __wrapper__
uwsgi_1         |     return func(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 188, in __call__
uwsgi_1         |     return self._get_current_object()(*a, **kw)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 392, in __call__
uwsgi_1         |     return self.run(*args, **kwargs)
uwsgi_1         |   File "/app/./dojo/importers/importer/importer.py", line 108, in process_parsed_findings
uwsgi_1         |     item.save(dedupe_option=False)
uwsgi_1         |   File "/app/./dojo/models.py", line 2500, in save
uwsgi_1         |     super(Finding, self).save(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
uwsgi_1         |     self.save_base(using=using, force_insert=force_insert,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
uwsgi_1         |     updated = self._save_table(
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
uwsgi_1         |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
uwsgi_1         |     return manager._insert(
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
uwsgi_1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
uwsgi_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | django.db.utils.DataError: (1406, "Data too long for column 'vuln_id_from_tool' at row 1")
uwsgi_1         | [pid: 56|app: -|req: -/-] 10.10.1.1 (admin) {66 vars in 1549 bytes} [Thu Apr 28 15:01:42 2022] POST /engagement/1/import_scan_results => generated 105920 bytes in 3045 msecs (HTTP/1.1 200) 7 headers in 361 bytes (1 switches on core 0)
nginx_1         | 10.10.1.1 - - [28/Apr/2022:15:01:45 +0000] "POST /engagement/1/import_scan_results HTTP/1.1" 200 105920 "http://localhost:8080/engagement/1/import_scan_results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
```

**Sample scan files**

[many_aggregated_findings.zip](https://github.com/DefectDojo/django-DefectDojo/files/8584589/many_aggregated_findings.zip)

**Additional context** (optional)
The problem is that the vuln_id_from_tool contains many times the same value which is really not very informative:
```
5273,5273,5273,5273,5273,5273,5273...
```

I suggest that we deduplicate this field when aggregating findings. In this case, the value for  vuln_id_from_tool should only be only: 
```
5273
```

I have already done the fix, just need to cherry-pick it and add unit tests. Fixing PR coming asap.

**Comment by StefanFl** [comment]
merged for release 2.10.0
