### ISSUE TITLE
Foreign key dojo_vulnerability_id

### ISSUE THREAD

**Issue by italvi** [DefectDojo/django-DefectDojo#6249]
**Be informative**
After running into some performance issues on our Cluster I wanted to start using the feature to delete duplicates via the system settings, setting the limit to 5. But unfortunately I get the error below and the duplicates will not be deleted. As you can see in the image I still have 73 duplicates per finding (I used an hourly import via DependencyTrack, that's the reason why I have so many duplicates per finding).
![image](https://user-images.githubusercontent.com/58322186/166872385-b1490e7c-9e50-40db-acaf-2496f1323dca.png)

**Problem description**
I receive the error (for logs see below): django.db.utils.IntegrityError: update or delete on table "dojo_finding" violates foreign key constraint "dojo_vulnerability_r_finding_id_c9d59919_fk_dojo_find" on table "dojo_vulnerability_id"
DETAIL:  Key (id)=(33114) is still referenced from table "dojo_vulnerability_id".
My suggestion is that with the new update, where you changed the vulnerability_reference/id I got problems with the consistency of the DB.

**Expected behavior**
Duplicates will be deleted, if there are more than 5.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: 2.10.0

**Logs** 
[04/May/2022 19:56:27] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[1bba5fb0-ebaa-44be-94c9-01b435d34999] received
[04/May/2022 19:56:27] INFO [dojo.tasks:104] delete excess duplicates (max_dupes per finding: 5, max deletes per run: 200)
[04/May/2022 19:56:27] INFO [dojo.specific-loggers.deduplication:105] delete excess duplicates (max_dupes per finding: 5, max deletes per run: 200)
[04/May/2022 19:56:28] ERROR [celery.app.trace:265] Task dojo.tasks.async_dupe_delete[1bba5fb0-ebaa-44be-94c9-01b435d34999] raised unexpected: IntegrityError('update or delete on table "dojo_finding" violates foreign key constraint "dojo_vulnerability_r_finding_id_c9d59919_fk_dojo_find" on table "dojo_vulnerability_id"\nDETAIL:  Key (id)=(33114) is still referenced from table "dojo_vulnerability_id".\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: update or delete on table "dojo_finding" violates foreign key constraint "dojo_vulnerability_r_finding_id_c9d59919_fk_dojo_find" on table "dojo_vulnerability_id"
DETAIL:  Key (id)=(33114) is still referenced from table "dojo_vulnerability_id".
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/dojo/tasks.py", line 130, in async_dupe_delete
    finding.delete()
  File "/app/dojo/models.py", line 2107, in delete
    super().delete(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
    signals.post_delete.send(
  File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: update or delete on table "dojo_finding" violates foreign key constraint "dojo_vulnerability_r_finding_id_c9d59919_fk_dojo_find" on table "dojo_vulnerability_id"
DETAIL:  Key (id)=(33114) is still referenced from table "dojo_vulnerability_id".

**Comment by italvi** [comment]
A downgrade to 2.9.1 did solve the issue. The worker started to delete the duplicates. For testing purpose I once again did the update to 2.10.0 and now the worker does not throw this error and deletes the duplicates, too.
