### ISSUE TITLE
Yarn Audit import fails

### ISSUE THREAD

**Issue by IchGehSteil** [DefectDojo/django-DefectDojo#6538]
**Bug description**
I have created a json yarn audit of my project with the command provided in the [Supported reports documentation](https://defectdojo.github.io/django-DefectDojo/integrations/parsers/#yarn-audit). When trying to import the results to an engagement, the import fails with the following error message: "Expecting property name enclosed in double quotes: line 2 column 1 (char 3)". I made sure the json is valid. 

**Steps to reproduce**
1. Create a Yarn Audit json
2. Create a engagement in DD and add the json to the tests

**Expected behavior**
DD parses the Yarn Audit json file and creates findings. 

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Debian 11
 - DefectDojo version: 2.11

**Logs**
```
uwsgi_1         | DEBUG [dojo.importers.reimporter.reimporter:285] REIMPORT_SCAN: parameters: {'self': <dojo.importers.reimporter.reimporter.DojoDefaultReImporter object at 0x7fd6325eb940>, 'scan': <TemporaryUploadedFile: sample.json (application/json)>, 'scan_type': 'Yarn Audit Scan', 'test': <Test: Yarn Audit Scan>, 'active': True, 'verified': False, 'tags': None, 'minimum_severity': 'Info', 'user': None, 'endpoints_to_add': None, 'scan_date': datetime.datetime(2022, 7, 6, 0, 0, tzinfo=<UTC>), 'version': '', 'branch_tag': '', 'build_id': '', 'commit_hash': '', 'push_to_jira': False, 'close_old_findings': True, 'group_by': '', 'api_scan_configuration': None, 'service': ''}
uwsgi_1         | DEBUG [dojo.importers.reimporter.reimporter:310] REIMPORT_SCAN: Parse findings
uwsgi_1         | ERROR [dojo.test.views:679] Expecting property name enclosed in double quotes: line 2 column 1 (char 3)
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/./dojo/test/views.py", line 671, in re_import_scan_results
uwsgi_1         |     reimporter.reimport_scan(scan, scan_type, test, active=active, verified=verified,
uwsgi_1         |   File "/app/./dojo/importers/reimporter/reimporter.py", line 311, in reimport_scan
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "/app/./dojo/tools/yarn_audit/parser.py", line 22, in get_findings
uwsgi_1         |     return self.get_items(tree, test)
uwsgi_1         |   File "/app/./dojo/tools/yarn_audit/parser.py", line 26, in get_items
uwsgi_1         |     for element in tree:
uwsgi_1         |   File "/app/./dojo/tools/yarn_audit/parser.py", line 21, in <genexpr>
uwsgi_1         |     tree = (json.loads(line) for line in json_output)
uwsgi_1         |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
uwsgi_1         |     return _default_decoder.decode(s)
uwsgi_1         |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
uwsgi_1         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
uwsgi_1         |   File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
uwsgi_1         |     obj, end = self.scan_once(s, idx)
uwsgi_1         | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 3)

```
**Sample scan files**
[sample.zip](https://github.com/DefectDojo/django-DefectDojo/files/9081831/sample.zip)

**Comment by StefanFl** [comment]
Hi @IchGehSteil, have you formatted the json file? Yarn audit writes the results as json lines when you use the `--json` flag (see [jsonlines.org](https://jsonlines.org/)). Our parser expects each results to be in one line.

**Comment by IchGehSteil** [comment]
@StefanFl thanks for the information. I can confirm it works with json-lines. For some reason it came out formatted for my coworker.
