### ISSUE TITLE
AttributeError: module 'dojo.pipeline' has no attribute 'modify_permissions'

### ISSUE THREAD

**Issue by johnathanschmidt** [DefectDojo/django-DefectDojo#6653]
**Bug description**
I upgraded from version 2.12.0 to version 2.13.0 and when trying to login with Azure AD an error occurs `AttributeError: module 'dojo.pipeline' has no attribute 'modify_permissions'`.

I verified that version 2.13.0 actually removed the `modify_permissions` method. [Link](https://github.com/DefectDojo/django-DefectDojo/commit/d54ea52791d7ee33ea0f83a8869b8e8764824e58#diff-756c78208a4432d915ca32889680a6069043af0602d96b4afb9b3a40449b4dfcL66)

I don't know if it would have an impact, but the method remains in the file `dojo/settings/settings.dist.py`. [Link](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L456)

**Steps to reproduce**
1. Go to login page
2. Click on 'login with Azure AD'

**Deployment method**
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Kubernetes
 - DefectDojo version (see footer) or commit message: [2022-08-02 12:08:45 -0500] d54ea5279: Merge pull request #6643 from DefectDojo/release/2.13.0 [ (HEAD, tag: 2.13.0, origin/master, origin/HEAD, master)]

**Logs** 
```bash
[04/Aug/2022 18:38:02] ERROR [django.request:224] Internal Server Error: /complete/azuread-tenant-oauth2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_django/utils.py", line 46, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_django/views.py", line 31, in complete
    return do_complete(request.backend, _do_login, user=request.user,
  File "/usr/local/lib/python3.8/site-packages/social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 401, in auth_complete
    return self.do_auth(response['access_token'], response=response,
  File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 413, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_django/strategy.py", line 105, in authenticate
    return authenticate(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 112, in run_pipeline
    func = module_member(name)
  File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 59, in module_member
    return getattr(module, member)
AttributeError: module 'dojo.pipeline' has no attribute 'modify_permissions'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/18578299/182930782-5af18f4a-3a52-48ea-ab8a-d96d2e5bbb95.png)

**Additional context** (optional)
I'm using an external PostgreSQL database.

**Comment by frost9i** [comment]
Same here.
Assuming block of code was unintentionally removed with: 
https://github.com/DefectDojo/django-DefectDojo/commit/12f49e0adcd25cdffcb246c6655aef320356494f

![image](https://user-images.githubusercontent.com/25299818/183402469-9577a29c-19a8-4e4a-9956-89cbb17ebe05.png)

**Comment by Gby56** [comment]
Is there any patching possible for 2.13.0 ? Just upgraded on my instance...

**Comment by coheigea** [comment]
@StefanFl FYI

**Comment by StefanFl** [comment]
I asked the other maintainers about a hotfix release.

**Comment by Maffooch** [comment]
Release has been made -> https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.13.1

**Comment by johnathanschmidt** [comment]
Login with Azure AD ok, thanks!
