### ISSUE TITLE
JIRA_Issue matching query does not exist.

### ISSUE THREAD

**Issue by nicoleoakley** [DefectDojo/django-DefectDojo#675]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

Internal Server Error: /webhook
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/django-DefectDojo/dojo/jira_link/views.py", line 31, in webhook
    jissue = JIRA_Issue.objects.get(jira_id=jid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: JIRA_Issue matching query does not exist.
[03/Aug/2018 08:59:44] "POST /webhook?user_id=nicole.krantz&user_key=nicole.krantz HTTP/1.1" 500 91974

### Operating System 
Ubuntu 16.04

### DefectDojo Version
1.5.1

###Django Version
1.11.11

### Steps to Reproduce
The error occurs whenever the webhook fires from modifying JIRA

**Comment by aaronweaver** [comment]
@nicoleoakley Just pushed a fix that should address the issue in .1.5.2.

**Comment by nicoleoakley** [comment]
![image](https://user-images.githubusercontent.com/42067600/43727511-2e940bd4-9970-11e8-87cf-7e435cb458fe.png)
The issue is still showing up in celery

**Comment by aaronweaver** [comment]
Did you restart Celery?

**Comment by nicoleoakley** [comment]
yes

**Comment by nicoleoakley** [comment]
In the UI, the following error alerts have started propagating:

JiraError HTTP 400 url: https://jira-sandbox.eng.fireeye.com:8443/rest/api/2/issue
text: project is required

response headers = {'X-AUSERNAME': 'nicole.krantz', 'X-AREQUESTID': '523x372990x1', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'X-Seraph-LoginReason': 'OK', 'Vary': 'User-Agent', 'X-ASESSIONID': '1w3de9z', 'Connection': 'close', 'Cache-Control': 'no-cache, no-store, no-transform', 'Date': 'Mon, 06 Aug 2018 15:43:54 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'X-ASEN': 'SEN-2194419'}	response text = {"errorMessages":[],"errors":{"project":"project is required"}}
--

**Comment by devGregA** [comment]
@nicoleoakley it looks like you may be missing the project key defined at the product level.

**Comment by nicoleoakley** [comment]
I get the following when I call for my jira product configuration
`GET jira_product_configurations/
{}
200
{"meta": {"limit": 20, "next": null, "offset": 0, "previous": null, "total_count": 2}, "objects": [{"component": "Other", "conf": "/api/v1/jira_configurations/1/", "enable_engagement_epic_mapping": true, "id": 1, "product": "/api/v1/products/1/", "project_key": "SEC", "push_all_issues": true, "push_notes": true, "resource_uri": "/api/v1/jira_product_configurations/1/"}, {"component": "", "conf": "/api/v1/jira_configurations/1/", "enable_engagement_epic_mapping": true, "id": 2, "product": "/api/v1/products/2/", "project_key": "SEC", "push_all_issues": true, "push_notes": true, "resource_uri": "/api/v1/jira_product_configurations/2/"}]}
`

**Comment by devGregA** [comment]
@nicoleoakley  you'll want to check the Dojo product in question. There should be some new fields added to the form when edited.

**Comment by nicoleoakley** [comment]
I filed out the fields in the UI, but I'm still getting the following error when I try to push a finding to JIRA:
`[2018-08-07 23:47:10,475: ERROR/ForkPoolWorker-2] Task update_issue_task[340c2ad4-e30c-480c-be72-3d15c1ad9bd1] raised unexpected: DoesNotExist('JIRA_Issue matching query does not exist.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/django-DefectDojo/dojo/tasks.py", line 235, in update_issue_task
    update_issue(find, old_status, push_to_jira)
  File "/opt/django-DefectDojo/dojo/utils.py", line 1066, in update_issue
    j_issue = JIRA_Issue.objects.get(finding=find)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
Exception: JIRA_Issue matching query does not exist.
`

**Comment by alekbc** [comment]
Hi @devGregA , I believe this is just a miss-configuration. I had a similar issue. 
A proper jira project name has to be set in the product settings. I'm still struggling with this but is matter of write the proper settings. I'll come back after I had this running..

**Comment by alekbc** [comment]
@devGregA , @nicoleoakley , I made this work. You just need to create the proper project name in jira product and jira with required fields (in jira) and issue type that makes sens to your defectDojo configuration. The "matching query" issue came out when the project key name was wrong (because it didn't exist in jira). Hope having helped.

**Comment by dougmorato** [comment]
+1 
@aaronweaver 
I know the settings I have configured in the Project and the Jira settings work because the integration DID create a new Epic in Jira when I created the engagement, but editing and clicking 
'Push to Jira" on a finding gives the same  **JIRA_Issue matching query does not exist** detailed below.

Any ideas on how to further troubleshoot / enable a more verbose debug ?


2018-12-07 11:06:28,542: INFO/MainProcess] Received task: add_epic_task[9f21d942-a8d0-4c0a-a5e3-1a6cbd05863f]
[2018-12-07 11:06:28,546: INFO/ForkPoolWorker-1] add_epic_task[9f21d942-a8d0-4c0a-a5e3-1a6cbd05863f]: add epic task
[2018-12-07 11:06:29,996: INFO/ForkPoolWorker-1] Task add_epic_task[9f21d942-a8d0-4c0a-a5e3-1a6cbd05863f] succeeded in 1.45061186401s: None
[2018-12-07 11:07:40,133: INFO/MainProcess] Received task: async_dedupe[4d427e57-09cb-44e1-a05e-762dd52bb4aa]
[2018-12-07 11:07:40,137: INFO/ForkPoolWorker-2] async_dedupe[4d427e57-09cb-44e1-a05e-762dd52bb4aa]: running deduplication
[2018-12-07 11:07:40,161: INFO/ForkPoolWorker-2] Task async_dedupe[4d427e57-09cb-44e1-a05e-762dd52bb4aa] succeeded in 0.024569088011s: None
[2018-12-07 11:07:40,165: INFO/MainProcess] Received task: async_false_history[129e54ad-b165-4ce8-aee1-14d9bc82db61]
[2018-12-07 11:07:40,169: INFO/ForkPoolWorker-3] async_false_history[129e54ad-b165-4ce8-aee1-14d9bc82db61]: running false_history
[2018-12-07 11:07:40,192: INFO/ForkPoolWorker-3] Task async_false_history[129e54ad-b165-4ce8-aee1-14d9bc82db61] succeeded in 0.0232933429943s: None


[2018-12-07 11:10:26,508: INFO/MainProcess] Received task: async_dedupe[08e1f23f-1e03-4322-9f64-3092dbdda993]
[2018-12-07 11:10:26,511: INFO/ForkPoolWorker-1] async_dedupe[08e1f23f-1e03-4322-9f64-3092dbdda993]: running deduplication
[2018-12-07 11:10:26,535: INFO/ForkPoolWorker-1] Task async_dedupe[08e1f23f-1e03-4322-9f64-3092dbdda993] succeeded in 0.0235269670084s: None
[2018-12-07 11:10:26,539: INFO/MainProcess] Received task: async_false_history[0b3eb511-feaa-46dc-8b12-04f7314ec13b]
[2018-12-07 11:10:26,543: INFO/ForkPoolWorker-2] async_false_history[0b3eb511-feaa-46dc-8b12-04f7314ec13b]: running false_history
[2018-12-07 11:10:26,561: INFO/ForkPoolWorker-2] Task async_false_history[0b3eb511-feaa-46dc-8b12-04f7314ec13b] succeeded in 0.0188844390213s: None
[2018-12-07 11:10:26,577: INFO/MainProcess] Received task: update_issue_task[428e11a9-28fd-433f-8bd1-291ce057e6ca]
[2018-12-07 11:10:26,580: INFO/ForkPoolWorker-3] update_issue_task[428e11a9-28fd-433f-8bd1-291ce057e6ca]: add issue task
[2018-12-07 11:10:26,602: ERROR/ForkPoolWorker-3] Task update_issue_task[428e11a9-28fd-433f-8bd1-291ce057e6ca] raised unexpected: DoesNotExist('JIRA_Issue matching query does not exist.',)
Traceback (most recent call last):
  File "/opt/dojo/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/dojo/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/dojo/django-DefectDojo/dojo/tasks.py", line 235, in update_issue_task
    update_issue(find, old_status, push_to_jira)
  File "/opt/dojo/django-DefectDojo/dojo/utils.py", line 1066, in update_issue
    j_issue = JIRA_Issue.objects.get(finding=find)
  File "/opt/dojo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/dojo/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
Exception: JIRA_Issue matching query does not exist.
