### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by franzramadhan** [DefectDojo/django-DefectDojo#6756]
**Be informative**
I tried to reset password for one user. The email address is correct but got `500 server error`.

This does not apply for non-existent email. It will show this page instead

<img width="1440" alt="Screen Shot 2022-08-24 at 11 19 39" src="https://user-images.githubusercontent.com/1482172/186327962-0ebdab3a-e9ce-47cb-bdfd-ce714ab99f07.png">

**Bug description**
```
ERROR [django.request:224] Internal Server Error: /password_reset/                                                                                                                
 Traceback (most recent call last):                                                                                                                                                                       
   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner                                                                                                     
     response = get_response(request)                                                                                                                                                                     
   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response                                                                                                 
     response = wrapped_callback(request, *callback_args, **callback_kwargs)

   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response                                                                                                 
     response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                                                              
   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view                                                                                                           
     return self.dispatch(request, *args, **kwargs)                                                                                                                                                       
   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper                                                                                                         
     return bound_method(*args, **kwargs)                                                                                                                                                                 
   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view                                                                                                   
     response = view_func(request, *args, **kwargs)                                                                                                                                                       
   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/views.py", line 222, in dispatch                                                                                                      
     return super().dispatch(*args, **kwargs)                                                                                                                                                             
   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch                                                                                                       
     return handler(request, *args, **kwargs)                                                                                                                                                             
   File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post                                                                                                          
     return self.form_valid(form)                                                                                                                                                                         
   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/views.py", line 235, in form_valid                                                                                                    
     form.save(**opts)                                                                                                                                                                                    
   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 310, in save                                                                                                          
     self.send_mail(                                                                                                                                                                                      
   File "/app/./dojo/user/views.py", line 579, in send_mail                                                                                                                                               
     super().send_mail(subject_template_name, email_template_name,                                                                                                                                        
   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 260, in send_mail                                                                                                     
     email_message.send()                                                                                                                                                                                 
   File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send                                                                                                           
     return self.get_connection(fail_silently).send_messages([self])                                                                                                                                      
   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages                                                                                            
     new_conn_created = self.open()                                                                                                                                                                       
   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open                                                                                                      
     self.connection = self.connection_class(self.host, self.port, **connection_params)                                                                                                                   
   File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__                                                                                                                                      
     (code, msg) = self.connect(host, port)                                                                                                                                                               
   File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect                                                                                                                                       
     self.sock = self._get_socket(host, port, self.timeout)                                                                                                                                               
   File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket                                                                                                                                   
     return socket.create_connection((host, port), timeout,                                                                                                                                               
   File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection                                                                                                                              
     raise err                                                                                                                                                                                            
   File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection                                                                                                                              
     sock.connect(sa)                                                                                                                                                                                     
 OSError: [Errno 99] Cannot assign requested address
```

**Steps to reproduce**
1. Go to Login page
2. Click on `I forgot my password` 
3. Put user email that does exists

**Expected behavior**
1. Reset password able to send the reset link to the corresponding user(s)

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Comment by franzramadhan** [comment]
Fixed by use partial url encoding for the SES credential.

Details can be seen in this thread - https://owasp.slack.com/archives/C2P5BA8MN/p1661415474100889?thread_ts=1661287811.148759&cid=C2P5BA8MN

Will create PR to update the docs for configuring SMTP using AWS SES SMTP credential
