### ISSUE TITLE
Error when running ./manage.py migrate_cve for 2.13.x upgrade

### ISSUE THREAD

**Issue by 37b** [DefectDojo/django-DefectDojo#6824]
We are trying to upgrade from `2.12` to `2.13.1` and get the error below. Is there some manual cleanup we should run before or are there use cases this migration doesn't account for?

```Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/dojo/management/commands/migrate_cve.py", line 39, in handle
    mass_model_updater(
  File "/app/dojo/utils.py", line 2123, in mass_model_updater
    function(model)
  File "/app/dojo/management/commands/migrate_cve.py", line 42, in <lambda>
    lambda f: create_vulnerability_id(f),
  File "/app/dojo/management/commands/migrate_cve.py", line 17, in create_vulnerability_id
    Vulnerability_Id.objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
dojo.models.MultipleObjectsReturned: get() returned more than one Vulnerability_Id -- it returned more than 20!

**Comment by mtesauro** [comment]
Depends on the deployment method you used for DefectDojo:

(1) docker-compose - the initializer container will run migrations for you on an update.  Looking at the docker logs for that container can help to see if they were run successfully.  Additionally, you can [show migrations](https://docs.djangoproject.com/en/4.0/ref/django-admin/#django-admin-showmigrations) to validate that all the migrations have been applied.

(2) Helm/k8s - I've not really done more than play around with this deploy method and that's been a while.  I recall that Helm also has/uses an initializer container - why yes, [it seems so](https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/values.yaml#L282).

(3) godojo - upgrades are manual for godojo installs.  You'd do the normal Django thing of using manage.py to handle the migrations. godojo assumes you're fairly familiar with Django apps and updating them.

It would probably be better to ask this in OWASP's Slack on #defectdojo - see [here](https://github.com/DefectDojo/django-DefectDojo#community-getting-involved-and-updates) as you'll have a larger audience with more varied experience.
