### ISSUE TITLE
Broken API integration

### ISSUE THREAD

**Issue by kokhanevych-macpaw** [DefectDojo/django-DefectDojo#6889]
In our pipeline, I am trying to get a list of products through the API, but got the error. We are using Python for our scripts. On 2.13.1 version all was fine.

**Steps to reproduce**
1. Install DD Python API packages.
2. Run dd.list_products() command
3. Got the error.

**Expected behavior**
I get list of products through API.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ X] Kubernetes
- [ ] GoDojo

**Environment information**
- Operating System: [debian:buster-slim]
- DefectDojo version: [2.14.3]

**Logs** 
The above exception was the direct cause of the following exception:
Error
2022-09-23 11:53:20.065 EEST{}
Error
2022-09-23 11:53:20.065 EESTTraceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch response = handler(request, *args, **kwargs) File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper return bound_method(*args, **kwargs) File "/app/./dojo/api_v2/prefetch/mixins.py", line 13, in list queryset = self.paginate_queryset(queryset) File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset return self.paginator.paginate_queryset(queryset, self.request, view=self) File "/usr/local/lib/python3.8/site-packages/rest_framework/pagination.py", line 387, in paginate_queryset self.count = self.get_count(queryset) File "/usr/local/lib/python3.8/site-packages/rest_framework/pagination.py", line 525, in get_count return queryset.count() File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 412, in count return self.query.get_count(using=self.db) File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 528, in get_count number = obj.get_aggregation(using, ['__count'])['__count'] File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation result = compiler.execute_sql(SINGLE) File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 71, in execute return super().execute(*args, **kwargs) django.db.utils.ProgrammingError: column dojo_product.sla_configuration_id does not exist
Error
2022-09-23 11:53:20.065 EESTLINE 1: ...pe_id" AS Col8, "dojo_product"."updated" AS Col9, "dojo_prod...
Error
2022-09-23 11:53:20.065 EEST ^
Error
2022-09-23 11:53:20.065 EEST{}
Error
2022-09-23 11:53:20.075 EEST[23/Sep/2022 08:53:20] ERROR [django.request:224] Internal Server Error: /api/v2/products/
Info
2022-09-23 11:53:20.075 EEST10.1.132.135 - - [23/Sep/2022:08:53:20 +0000] "GET /api/v2/products/?limit=200 HTTP/1.1" 500 59

**Comment by valentijnscholten** [comment]
Installing from source might work.
https://github.com/DefectDojo/defectdojo_api#this-api-wrapper-is-no-longer-maintained-it-may-or-may-not-work

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro as this is quite old.
