### ISSUE TITLE
After uploading the image, the front end cannot be displayed

### ISSUE THREAD

**Issue by x24thkk** [DefectDojo/django-DefectDojo#7050]
After uploading the image, the front end cannot be displayed

url path: access_file/8/3/Finding

webpage display : A server error occurred.  Please contact the administrator.

**errors：**
[31/Oct/2022 07:24:34] DEBUG [django.db.backends:123] (0.001) SELECT "dojo_fileupload"."id", "dojo_fileupload"."title", "dojo_fileupload"."file" FROM "dojo_fileupload" WHERE "dojo_fileupload"."id" = 8 LIMIT 21; args=(8,)
/opt/dojo/django-DefectDojo/media
/media/
/opt/dojo/django-DefectDojo/media/uploaded_files/3090056f-70be-48b1-8ff1-7cbff798b00b.png
2
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 279, in write
    assert type(data) is bytes, \
AssertionError: write() argument must be a bytes instance
[31/Oct/2022 07:24:34] ERROR [django.server:161] "GET /access_file/8/3/Finding HTTP/1.1" 500 59

**solv**
edit  /opt/dojo/django-DefectDojo/dojo/view.py

> origin:

 return FileResponse(open(redirect_url))

> edited:

 return FileResponse(open(redirect_url, 'rb'))

**Comment by coheigea** [comment]
Can you submit a pull request along the suggested lines?

**Comment by manuel-sommer** [comment]
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/5d04d490-348e-4426-8638-54d953bf842e)
already fixed in v2.31.0

Can you close this @mtesauro ?
