### ISSUE TITLE
Defect Dojo doesn't support Cyrillic chars

### ISSUE THREAD

**Issue by pagliacci** [DefectDojo/django-DefectDojo#706]
### Issue Type 
- [ ] Bug
- [х] Enhancement

### Description

Seems like Cyrillic chars are not supported in DefectDojo. And the application returns "OperationalError" when Cyrillic chars are entered in any field.

This may occur due to the problems with Python 2.7 and cyrillic chars.

### Operating System 
Ubuntu 16.04

### Install

- [x] setup.bash
- [ ] docker

### Steps to Reproduce

1. Install DefectDojo using setup.bash script
2. Choose MySQL database
3. Run the application
4. Create a product, finding, etc.
5. Enter Cyrillic chars in any field and try to submit the form (Figure 1)
6. OperationalError returns (Figure 2)

### Screenshots (optional)

![Figure 1](https://i.imgur.com/YjimySV.png)
![Figure 2](https://i.imgur.com/e6aKcHC.png)

### Console Logs (optional)

```
Internal Server Error: /product/add
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/django-DefectDojo/dojo/product/views.py", line 445, in new_product
    product = form.save()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (1366, "Incorrect string value: '\\xE8\\x9D\\xA0' for column 'name' at row 1")
```

**Comment by Nilix007** [comment]
This is probably due to MySQL's default character set being `latin1` which only supports some West/Central European languages (not even France for example). You might want to use the character set `utf8mb4` instead which has full UTF-8 support.

**Comment by aaronweaver** [comment]
@pagliacci Let us know if that works for you and we'll update the install script and docs.

**Comment by pagliacci** [comment]
It works.

Firstly I've changed the charset of Database with this command:
`ALTER DATABASE dojo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

Then I've generated queries to change charset of every table:

```
SELECT CONCAT("ALTER TABLE ", TABLE_SCHEMA, '.', TABLE_NAME," CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci") AS ExecuteTheString FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA="dojo"
AND TABLE_TYPE="BASE TABLE";
```

That query generates list of queries. After the execution of all this queries DefectDojo works fine with Cyrillic (and not only) chars.

**Comment by devGregA** [comment]
@pagliacci Will add this to the setup script

**Comment by aaronweaver** [comment]
@pagliacci Thanks for providing that back with those details.

**Comment by pagliacci** [comment]
I found new error while adding new Finding.
Application returns "UnicodeEncodeError", but the Finding was saved successfully.
The problem is with the Cyrillic string again:

**The string that could not be encoded/decoded was: Раскрытие инфо**

The screenshot of the error can be seen below.
![image](https://user-images.githubusercontent.com/7060487/44243102-efea0f00-a1d5-11e8-82e2-31b5d375ec02.png)

```
Internal Server Error: /product/2/ad_hoc_finding
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pagliacci/django-DefectDojo/dojo/product/views.py", line 790, in ad_hoc_finding
    new_finding.save()
  File "/home/pagliacci/django-DefectDojo/dojo/models.py", line 1182, in save
    self.hash_code = self.get_hash_code()
  File "/home/pagliacci/django-DefectDojo/dojo/models.py", line 1049, in get_hash_code
    hash_string = hash_string.decode('utf-8').strip()
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
```

**Comment by devGregA** [comment]
@pagliacci Are you still having issues after this merge?

**Comment by pagliacci** [comment]
@devGregA Yes, now it works fine. Thanks @Nilix007 .
