### ISSUE TITLE
500 error when clicking on system setting from UI.

### ISSUE THREAD

**Issue by spmishra121** [DefectDojo/django-DefectDojo#7145]
I had updated defect dojo with latest release 2.16. Before this I was using 2.XX. Now, If I am clicking on system settings, I am getting 500 error while in previous one, it was working as expected.

Steps: 
Installed DD using docker-compose file.
Login into the application.
Click on Configuration>>System Settings

Output:
Server Error (500)

**Comment by spmishra121** [comment]
Seems that latest release is not stable. Getting 500 error at so many location.
1. At the above location
2.  When you are trying to close findings.

**Comment by coheigea** [comment]
What's the stack trace you see in the logs?

**Comment by spmishra121** [comment]
I am getting below logs only....
uwsgi_1         | [pid: 31|app: -|req: -/-] 172.24.65.224 (admin) {44 vars in 985 bytes} [Wed Nov 16 10:24:01 2022] GET /system_settings => generated 145 bytes in 45 msecs (HTTP/1.1 500) 6 headers in 184 bytes (1 switches on core 0)
nginx_1         | 172.24.65.224 - - [16/Nov/2022:10:24:01 +0000] "GET /system_settings HTTP/1.1" 500 145 "http://defectdojo-dev.devdlt.com:3000/critical_product_metrics" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
nginx_1         | 172.24.86.3 - - [16/Nov/2022:10:24:02 +0000] "GET /alerts/count HTTP/1.1" 200 13 "http://defectdojo-dev.devdlt.com:3000/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 31|app: -|req: -/-] 172.24.86.3 (admin) {44 vars in 828 bytes} [Wed Nov 16 10:24:02 2022] GET /alerts/count => generated 13 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)
nginx_1         | 172.24.86.3 - - [16/Nov/2022:10:24:12 +0000] "GET /alerts/count HTTP/1.1" 200 13 "http://defectdojo-dev.devdlt.com:3000/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: -|req: -/-] 172.24.86.3 (admin) {44 vars in 828 bytes} [Wed Nov 16 10:24:12 2022] GET /alerts/count => generated 13 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)

**Comment by spmishra121** [comment]
docker-compose log while clicking on regulation:
nginx_1         | 172.24.69.12 - - [23/Nov/2022:09:54:57 +0000] "GET /system_settings HTTP/1.1" 500 145 "http://defectdojo-dev.devdlt.com:3000/regulations" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 32|app: -|req: -/-] 172.24.69.12 (admin) {44 vars in 971 bytes} [Wed Nov 23 09:54:57 2022] GET /system_settings => generated 145 bytes in 40 msecs (HTTP/1.1 500) 6 headers in 184 bytes (1 switches on core 0)
nginx_1         | 172.24.69.12 - - [23/Nov/2022:09:55:00 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/product" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: -|req: -/-] 172.24.69.12 (admin) {44 vars in 833 bytes} [Wed Nov 23 09:55:00 2022] GET /alerts/count => generated 14 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:04 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/81/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:04 2022] GET /alerts/count => generated 14 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 0)
celerybeat_1    | [23/Nov/2022 09:55:08] INFO [celery.beat:285] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
celerybeat_1    | [23/Nov/2022 09:55:08] ERROR [celery.beat:289] Message Error: Couldn't apply scheduled task dedupe-delete: Invalid SQLite URL: sqlite://guest:guest@/dojo.celerydb.sqlite
celerybeat_1    | Valid SQLite URL forms are:
celerybeat_1    |  sqlite:///:memory: (or, sqlite://)
celerybeat_1    |  sqlite:///relative/path/to/file.db
celerybeat_1    |  sqlite:////absolute/path/to/file.db
celerybeat_1    | ['  File "/usr/local/bin/celery", line 8, in <module>\n    sys.exit(main())\n', '  File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 15, in main\n    sys.exit(_main())\n', '  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 217, in main\n    return celery(auto_envvar_prefix="CELERY")\n', '  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__\n    return self.main(*args, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main\n    rv = self.invoke(ctx)\n', '  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n', '  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n', '  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke\n    return __callback(*args, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func\n    return f(get_current_context(), *args, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 134, in caller\n    return f(ctx, *args, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/celery/bin/beat.py", line 72, in beat\n    return beat().run()\n', '  File "/usr/local/lib/python3.8/site-packages/celery/apps/beat.py", line 77, in run\n    self.start_scheduler()\n', '  File "/usr/local/lib/python3.8/site-packages/celery/apps/beat.py", line 105, in start_scheduler\n    service.start()\n', '  File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 645, in start\n    interval = self.scheduler.tick()\n', '  File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 357, in tick\n    self.apply_entry(entry, producer=self.producer)\n', '  File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 290, in apply_entry\n    exc, traceback.format_stack(), exc_info=True)\n']
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 404, in apply_async
celerybeat_1    |     return task.apply_async(entry_args, entry_kwargs,
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 575, in apply_async
celerybeat_1    |     return app.send_task(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 788, in send_task
celerybeat_1    |     amqp.send_task_message(P, name, message, **options)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 510, in send_task_message
celerybeat_1    |     ret = producer.publish(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 177, in publish
celerybeat_1    |     return _publish(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 523, in _ensured
celerybeat_1    |     return fun(*args, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 193, in _publish
celerybeat_1    |     [maybe_declare(entity) for entity in declare]
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 193, in <listcomp>
celerybeat_1    |     [maybe_declare(entity) for entity in declare]
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 99, in maybe_declare
celerybeat_1    |     return maybe_declare(entity, self.channel, retry, **retry_policy)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/common.py", line 110, in maybe_declare
celerybeat_1    |     return _maybe_declare(entity, channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/common.py", line 150, in _maybe_declare
celerybeat_1    |     entity.declare(channel=channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 606, in declare
celerybeat_1    |     self._create_queue(nowait=nowait, channel=channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 615, in _create_queue
celerybeat_1    |     self.queue_declare(nowait=nowait, passive=False, channel=channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 643, in queue_declare
celerybeat_1    |     ret = channel.queue_declare(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 522, in queue_declare
celerybeat_1    |     self._new_queue(queue, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 153, in _new_queue
celerybeat_1    |     self._get_or_create(queue)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 132, in _get_or_create
celerybeat_1    |     obj = self.session.query(self.queue_cls) \
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 127, in session
celerybeat_1    |     _, Session = self._open()
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 117, in _open
celerybeat_1    |     engine = self._engine_from_config()
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 106, in _engine_from_config
celerybeat_1    |     return create_engine(conninfo.hostname, **transport_options)
celerybeat_1    |   File "<string>", line 2, in create_engine
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
celerybeat_1    |     return fn(*args, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 564, in create_engine
celerybeat_1    |     (cargs, cparams) = dialect.create_connect_args(u)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 584, in create_connect_args
celerybeat_1    |     raise exc.ArgumentError(
celerybeat_1    | sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite://guest:guest@/dojo.celerydb.sqlite
celerybeat_1    | Valid SQLite URL forms are:
celerybeat_1    |  sqlite:///:memory: (or, sqlite://)
celerybeat_1    |  sqlite:///relative/path/to/file.db
celerybeat_1    |  sqlite:////absolute/path/to/file.db
celerybeat_1    |
celerybeat_1    | During handling of the above exception, another exception occurred:
celerybeat_1    |
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 287, in apply_entry
celerybeat_1    |     result = self.apply_async(entry, producer=producer, advance=False)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 412, in apply_async
celerybeat_1    |     reraise(SchedulingError, SchedulingError(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/exceptions.py", line 108, in reraise
celerybeat_1    |     raise value.with_traceback(tb)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 404, in apply_async
celerybeat_1    |     return task.apply_async(entry_args, entry_kwargs,
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 575, in apply_async
celerybeat_1    |     return app.send_task(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 788, in send_task
celerybeat_1    |     amqp.send_task_message(P, name, message, **options)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 510, in send_task_message
celerybeat_1    |     ret = producer.publish(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 177, in publish
celerybeat_1    |     return _publish(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 523, in _ensured
celerybeat_1    |     return fun(*args, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 193, in _publish
celerybeat_1    |     [maybe_declare(entity) for entity in declare]
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 193, in <listcomp>
celerybeat_1    |     [maybe_declare(entity) for entity in declare]
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 99, in maybe_declare
celerybeat_1    |     return maybe_declare(entity, self.channel, retry, **retry_policy)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/common.py", line 110, in maybe_declare
celerybeat_1    |     return _maybe_declare(entity, channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/common.py", line 150, in _maybe_declare
celerybeat_1    |     entity.declare(channel=channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 606, in declare
celerybeat_1    |     self._create_queue(nowait=nowait, channel=channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 615, in _create_queue
celerybeat_1    |     self.queue_declare(nowait=nowait, passive=False, channel=channel)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 643, in queue_declare
celerybeat_1    |     ret = channel.queue_declare(
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 522, in queue_declare
celerybeat_1    |     self._new_queue(queue, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 153, in _new_queue
celerybeat_1    |     self._get_or_create(queue)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 132, in _get_or_create
celerybeat_1    |     obj = self.session.query(self.queue_cls) \
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 127, in session
celerybeat_1    |     _, Session = self._open()
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 117, in _open
celerybeat_1    |     engine = self._engine_from_config()
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 106, in _engine_from_config
celerybeat_1    |     return create_engine(conninfo.hostname, **transport_options)
celerybeat_1    |   File "<string>", line 2, in create_engine
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
celerybeat_1    |     return fn(*args, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 564, in create_engine
celerybeat_1    |     (cargs, cparams) = dialect.create_connect_args(u)
celerybeat_1    |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 584, in create_connect_args
celerybeat_1    |     raise exc.ArgumentError(
celerybeat_1    | celery.beat.SchedulingError: Couldn't apply scheduled task dedupe-delete: Invalid SQLite URL: sqlite://guest:guest@/dojo.celerydb.sqlite
celerybeat_1    | Valid SQLite URL forms are:
celerybeat_1    |  sqlite:///:memory: (or, sqlite://)
celerybeat_1    |  sqlite:///relative/path/to/file.db
celerybeat_1    |  sqlite:////absolute/path/to/file.db
uwsgi_1         | [pid: 32|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:14 2022] GET /alerts/count => generated 14 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:14 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/81/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 32|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:24 2022] GET /alerts/count => generated 14 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 0)
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:24 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/81/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:34 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/81/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:34 2022] GET /alerts/count => generated 14 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:43 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/80/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 32|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:43 2022] GET /alerts/count => generated 14 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:44 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/81/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
uwsgi_1         | [pid: 32|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:44 2022] GET /alerts/count => generated 14 bytes in 13 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 0)
uwsgi_1         | [pid: 1|app: -|req: -/-] 172.24.86.2 (admin) {44 vars in 839 bytes} [Wed Nov 23 09:55:54 2022] GET /alerts/count => generated 14 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 0)
nginx_1         | 172.24.86.2 - - [23/Nov/2022:09:55:54 +0000] "GET /alerts/count HTTP/1.1" 200 14 "http://defectdojo-dev.devdlt.com:3000/engagement/81/delete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"

**Comment by mtesauro** [comment]
From those logs, it looks like your celery is misconfigured or not working.  I'd validate you're setting the DD_CELERY_[something] environment variables for celery correctly based on:

> celerybeat_1 | celery.beat.SchedulingError: Couldn't apply scheduled task dedupe-delete: Invalid SQLite URL: 
> sqlite://guest:guest@/dojo.celerydb.sqlite
> celerybeat_1 | Valid SQLite URL forms are:
> celerybeat_1 | sqlite:///:memory: (or, sqlite://)
> celerybeat_1 | sqlite:///relative/path/to/file.db
> celerybeat_1 | sqlite:////absolute/path/to/file.db

I'd look at those at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L55 and make sure they match your environment.  With compose, you could be running RabbitMQ or Redis so maybe try something like:

For rabbitmq
DD_CELERY_BROKER_URL="amqp://rabbitmq:5672//"
Or for redis:
DD_CELERY_BROKER_URL="redis://redis:6379/0"

In the key parts of your docker-compose for uwsgi, celery beat, celery worker and initializer e.g. https://github.com/DefectDojo/django-DefectDojo/blob/master/docker-compose.yml#L56

**Comment by spmishra121** [comment]
@mtesauro, Thanks for addressing the issue. But, why is this happening while it was working fine for 2.13 and if I am updating the DD as per latest version all required setting should be placed as per requirement?

**Comment by mtesauro** [comment]
@spmishra121 Quickly glancing over your docker-compose, I don't see DD_CELERY_BROKER_URL anywhere in there.

I've only used DD_CELERY_BROKER_URL so don't have any experience with upgrades and using the user/password versions of the DD_CELERY_X env variables.

FWIW, "URL-izing" connection strings was part of "12 Factoring" DefectDojo years ago - see https://12factor.net/backing-services

**Comment by valentijnscholten** [comment]
We believe this is no longer occurring with newer versions of Defect Dojo.
