### ISSUE TITLE
[JIRA] Creating new express Jira instance throw HTTP 500

### ISSUE THREAD

**Issue by js0cha** [DefectDojo/django-DefectDojo#7241]
**Bug description**
Error when trying to create new express Jira instance. After completion of password(api-key) and email wih valid issue id. We can't create the instance we got server error

**Steps to reproduce**
1. Go to 'Configuration'
2. Click on 'JIRA'
3. Click on ' Add Jira Instance (Express)'
4. Complete needed forms
5. See the error page "Server Error (500)"

**Expected behavior**
Created Jira instance

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Amazon EC2
 - DefectDojo version 2.16.2

**Logs** 
```
[06/Dec/2022 15:25:11] ERROR [django.request:224] Internal Server Error: /jira/express
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'open_status_key' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/./dojo/authorization/authorization_decorators.py", line 63, in _wrapped
    return func(request, *args, **kwargs)
  File "/app/./dojo/jira_link/views.py", line 299, in express_new_jira
    jira_instance.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 78, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'open_status_key' cannot be null")
```

**Comment by coheigea** [comment]
Does it work with the full JIRA configuration? Do you have some custom status categories defined? The code looks for:
```
for node in response['transitions']:
                    if node['to']['statusCategory']['name'] == 'To Do':
                        open_key = open_key or int(node['id'])
                    if node['to']['statusCategory']['name'] == 'Done':
                        close_key = close_key or int(node['id'])
```
