### ISSUE TITLE
Load findings from REST API using relative fields (test__engagement__tags) does not work

### ISSUE THREAD

**Issue by software-testing-professional** [DefectDojo/django-DefectDojo#7250]
**Be informative**
Loading findings via REST API does not work, if related fields like the engagement's tags are used. 
The query results in a http-500. 
According to logs, DefectDojo expects an integer instead of a string. 

**Bug description**
It is not possible to select findings from the REST API, if the filtering includes relative field information. 
Like tags attached to the finding's engagement. 

It seems like DefectDojo is expecting an integer instead of the tag name. 

I did some try and error and passed integer values instead of tag names. 
One of the requests finally returned the expected results. 
This was `test__engagement__tags=10`. 
So `10` is likely the id of the tag name `asfinag`. 

**Steps to reproduce**
Add any tag to an engagement. 
For example `asfinag`.

Execute http-GET: 
https://defectdojo.***.cloud/api/v2/findings?related_fields=true&test__engagement__tags=asfinag

Result: 
```
{
    "message": "Internal server error, check logs for details"
}
```

**Expected behavior**
A list of findings matching the search criteria should be returned. 

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
v. 2.16.2 ( release mode )

**Logs** 
```
[07/Dec/2022 15:02:47] ERROR [dojo.api_v2.exception_handler:32] Field 'id' expected a number but got 'asfinag'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'asfinag'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/drainage.py", line 159, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/app/./dojo/api_v2/prefetch/mixins.py", line 12, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/usr/local/lib/python3.8/site-packages/django_filters/rest_framework/backends.py", line 96, in filter_queryset
    return filterset.qs
  File "/usr/local/lib/python3.8/site-packages/django_filters/filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "/usr/local/lib/python3.8/site-packages/django_filters/filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/usr/local/lib/python3.8/site-packages/django_filters/filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/tagulous/models/tagged.py", line 141, in _filter_or_exclude
    qs = super(TaggedQuerySet, self)._filter_or_exclude(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 59, in get_prep_lookup
    self.rhs = [target_field.get_prep_value(v) for v in self.rhs]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 59, in <listcomp>
    self.rhs = [target_field.get_prep_value(v) for v in self.rhs]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'asfinag'.
```

**Comment by manuel-sommer** [comment]
The PR was merged.  Could you close this issue @mtesauro ?
