### ISSUE TITLE
Fix Microsoft Teams notifications

### ISSUE THREAD

**Issue by edwardtyson** [DefectDojo/django-DefectDojo#7802]
I have an error about "Invalid filter: 'full_url'". 

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04
 - DefectDojo version: 2.20.0

**Logs** 
```
celeryworker_1  | [13/Mar/2023 13:01:03] INFO [celery.worker.strategy:161] Task dojo.notifications.helper.send_msteams_notification[2b263277-84af-4b7c-8d3f-eb8737f8046e] received
celeryworker_1  | [13/Mar/2023 13:01:03] ERROR [dojo.notifications.helper:141] error during rendering of template notifications/msteams/product_added.tpl exception is Invalid filter: 'full_url'
celeryworker_1  | [13/Mar/2023 13:01:03] ERROR [dojo.notifications.helper:262] Invalid filter: 'full_url'
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 253, in send_msteams_notification
celeryworker_1  |     data=create_notification_message(event, None, 'msteams', *args, **kwargs))
celeryworker_1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/app/dojo/notifications/helper.py", line 145, in create_notification_message
celeryworker_1  |     notification_message = render_to_string(f"notifications/{notification_type}/other.tpl", kwargs)
celeryworker_1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
celeryworker_1  |     template = get_template(template_name, using=using)
celeryworker_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
celeryworker_1  |     return engine.get_template(template_name)
celeryworker_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
celeryworker_1  |     return Template(self.engine.get_template(template_name), self)
celeryworker_1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
celeryworker_1  |     template, origin = self.find_template(template_name)
celeryworker_1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
celeryworker_1  |     template = loader.get_template(name, skip=skip)
celeryworker_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
celeryworker_1  |     template = super().get_template(template_name, skip)
celeryworker_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
celeryworker_1  |     return Template(
celeryworker_1  |            ^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
celeryworker_1  |     self.nodelist = self.compile_nodelist()
celeryworker_1  |                     ^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
celeryworker_1  |     return parser.parse()
celeryworker_1  |            ^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
celeryworker_1  |     raise self.error(token, e)
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
celeryworker_1  |     filter_expression = self.compile_filter(token.contents)
celeryworker_1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
celeryworker_1  |     return FilterExpression(token, self)
celeryworker_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
celeryworker_1  |     filter_func = parser.find_filter(filter_name)
celeryworker_1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celeryworker_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
celeryworker_1  |     raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
celeryworker_1  | django.template.exceptions.TemplateSyntaxError: Invalid filter: 'full_url'

```

**Comment by hptho** [comment]
You can view at: https://github.com/DefectDojo/django-DefectDojo/issues/7628 . To fix it.

**Comment by mtesauro** [comment]
Fix in latest release, closing

**Comment by frost9i** [comment]
Slack notifications were fixed, but msteams still arn't working for me

**Comment by edwardtyson** [comment]
I think they forgot. Just add `{% load display_tags %}` into all msteams templates to fix.
