### ISSUE TITLE
SonarQube Error: AttributeError: module 'dojo.risk_acceptance.helper' has no attribute 'remove_finding

### ISSUE THREAD

**Issue by cpena002** [DefectDojo/django-DefectDojo#8096]
**Be informative**. 
After setting up SonarQube scan imports via the API Scan Configuration feature, DefectDojo tries to update the findings every 3 hours via this Celery beat cron job found  [settings.dist.py](https://github.com/DefectDojo/django-DefectDojo/blob/2.18.4/dojo/settings/settings.dist.py) 

```
'update-findings-from-source-issues': {
       'task': 'dojo.tools.tool_issue_updater.update_findings_from_source_issues',
       'schedule': timedelta(hours=3),
   },
```

The cron job above fires up the function found in dojo/tools/tool_issue_updater.py
```
def update_findings_from_source_issues(**kwargs):
   from dojo.tools.sonarqube_api.updater_from_source import \
       SonarQubeApiUpdaterFromSource


   findings = SonarQubeApiUpdaterFromSource().get_findings_to_update()


   for finding in findings:
       SonarQubeApiUpdaterFromSource().update(finding)
```

DefectDojo fetches the SonarQube findings and loops over each of them to update issues as needed.  The _update()_ function is found in [ _dojo/tools/sonarqube_api/updater_from_source.py](https://github.com/DefectDojo/django-DefectDojo/blob/2.18.4/dojo/tools/sonarqube_api/updater_from_source.py)_, line 27.

Within the update function, DefectDojo fetches the issues for the SonarQube finding and based on its status, tries to update it. The issue happens when DefectDojo executes the _self.update_finding_status function_
```
if current_status != "OPEN" and current_finding_status != current_status:
    logger.info("Original SonarQube issue '{}' has changed. Updating DefectDojo finding '{}'...".format(sonarqube_issue, finding))
    self.update_finding_status(finding, current_status)
```

The _update_finding_status_ function tries to execute _ra_helper.remove_finding.from_any_risk_acceptance(finding)_ but _remove_finding_ doesn’t exist.

Based on the function's name, it seems it should be calling `def remove_from_any_risk_acceptance(finding)` found in [_dojo/risk_acceptance/helper.py_](https://github.com/DefectDojo/django-DefectDojo/blob/2.18.4/dojo/risk_acceptance/helper.py)

**Bug description**

In trying to update SonarQube issues, the DefectDojo code tries to execute a function that doesn’t exist. 

The function it tries to call: ```ra_helper.remove_finding.from_any_risk_acceptance(finding)``` doesn't have _remove_finding_. 

Traceback logs:
```
[11/May/2023 04:37:15] INFO [dojo.tools.sonarqube_api.updater_from_source:42] Original SonarQube issue 'AYgCNrB6wKK9jUp7C41I' has changed. Updating DefectDojo finding 'Either Log This Exception and Handle It, or Rethrow It With Some Contextual Information.'...

2023-05-10T21:37:15.480-07:00	--- Logging error ---

2023-05-10T21:37:15.481-07:00	Traceback (most recent call last):

2023-05-10T21:37:15.481-07:00	File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task

2023-05-10T21:37:15.481-07:00	R = retval = fun(*args, **kwargs)

2023-05-10T21:37:15.481-07:00	^^^^^^^^^^^^^^^^^^^^

2023-05-10T21:37:15.481-07:00	File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__

2023-05-10T21:37:15.481-07:00	return self.run(*args, **kwargs)

2023-05-10T21:37:15.481-07:00	^^^^^^^^^^^^^^^^^^^^^^^^^

2023-05-10T21:37:15.481-07:00	File "/app/dojo/tools/tool_issue_updater.py", line 40, in update_findings_from_source_issues

2023-05-10T21:37:15.481-07:00	SonarQubeApiUpdaterFromSource().update(finding)

2023-05-10T21:37:15.481-07:00	File "/app/dojo/tools/sonarqube_api/updater_from_source.py", line 45, in update

2023-05-10T21:37:15.481-07:00	self.update_finding_status(finding, current_status)

2023-05-10T21:37:15.481-07:00	File "/app/dojo/tools/sonarqube_api/updater_from_source.py", line 87, in update_finding_status

2023-05-10T21:37:15.481-07:00	ra_helper.remove_finding.from_any_risk_acceptance(finding)

2023-05-10T21:37:15.481-07:00	^^^^^^^^^^^^^^^^^^^^^^^^

2023-05-10T21:37:15.481-07:00	AttributeError: module 'dojo.risk_acceptance.helper' has no attribute 'remove_finding'
```

**Steps to reproduce**

Pre-Requisites:
1. A SonarQube project exists with issues.  

1. Create an API Scan Configuration for SonarQube.
2. Execute the _update_findings_from_source_issues(**kwargs)_ function (runs every 3 hours).
3. If the issue doesn't exist in the the _dojo_sonarquibe_issue_ database it should add it.
4. Update the issue statu manually to something other than *OPEN*. REOPENED, for instance. 
5. Execute the _update_findings_from_source_issues(**kwargs)_ function once more.
6. You will get this error: ```AttributeError: module 'dojo.risk_acceptance.helper' has no attribute 'remove_finding'```. 

**Expected behavior**

Based on the function's name, it seems it should be calling `def remove_from_any_risk_acceptance(finding)` found in [_dojo/risk_acceptance/helper.py_](https://github.com/DefectDojo/django-DefectDojo/blob/2.18.4/dojo/risk_acceptance/helper.py)

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version (see footer) or commit message: 2.18.4

**Screenshots**

**Additional context** (optional)

**Comment by cpena002** [comment]
Good morning. Just making sure the ticket I opened is accurate. I know you folks are busy, but want to make sure I opened it correctly. Please let me know if any revisions are necessary.
