### ISSUE TITLE
DrHeader Parser: Validation Error if uploading a scan result with 0 findings

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#8281]
**Bug description**
KeyError in case of importing a non active test result

**Steps to reproduce**
Scan a target with DrHeader which is not active and upload the result to DefectDojo using DrHeader parser.

**Expected behavior**
DefectDojo parses the testresult without running into a ValidationError

**Deployment method:** Docker Compose
**Environment information:**  Ubuntu 20.04
**DefectDojo version (see footer) or commit message:**
[2023-06-16 09:58:53 -0500] https://github.com/DefectDojo/django-DefectDojo/commit/8ee0a7da7cd0e46f228c3e2c8a6c115ca469550b: Bump boto3 from 1.26.153 to 1.26.154 (https://github.com/DefectDojo/django-DefectDojo/pull/8266) [ (HEAD -> fix_testssl, origin/dev, dev)]

**Logs**
[20/Jun/2023 03:49:33] ERROR [dojo.engagement.views:703] ['Expecting value: line 1 column 1 (char 0)']
Traceback (most recent call last):
  File "/app/dojo/importers/importer/importer.py", line 309, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/drheader/parser.py", line 18, in get_findings
    data = json.load(filename)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/dojo/engagement/views.py", line 687, in import_scan_results
    test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 312, in import_scan
    raise ValidationError(e)
django.core.exceptions.ValidationError: ['Expecting value: line 1 column 1 (char 0)']

**Sample scan files**
[drheader.zip](https://github.com/DefectDojo/django-DefectDojo/files/11795657/drheader.zip)

**Comment by damiencarol** [comment]
Not sure the pb is from dojo side. DrHeader should not produce empty files. Empty files are not valid JSON files.
