### ISSUE TITLE
Error when i run defectdojo server ' IndentationError: unexpected indent'

### ISSUE THREAD

**Issue by azoumed** [DefectDojo/django-DefectDojo#830]
Hello Everyone ,

First big Thanks for community , i just installed defectdojo in ubuntu server 16.04 ; i'm just setps providing defectdojo repo 'github' , now when i try lanch my server , i find this issues above .
any help !!

root@Defectdojo-V1:/django-DefectDojo# python manage.py runserver
   Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in 
   execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/django-DefectDojo/dojo/settings/settings.py", line 26
    SESSION_COOKIE_SECURE = True
    ^
IndentationError: unexpected indent

**Comment by adracea** [comment]
Well by the looks of that stacktrace you might have a space/tab inserted
randomly into settings.py before the SESSION_COOKIE_SECURE

**Comment by aaronweaver** [comment]
@adracea nailed it just fix the remove the space and it will work.

**Comment by azoumed** [comment]
Thank you all

**Comment by azoumed** [comment]
can you share with me how to configure MySql Database

**Comment by azoumed** [comment]
i have to connect my database "Mysql" with defectdojo , all configuration is correct , so i don't know why nothing happen in my data base , in log file everything is ok
