### ISSUE TITLE
Gitlab Secret Detection report fails to be imported

### ISSUE THREAD

**Issue by cebrat** [DefectDojo/django-DefectDojo#8326]
**Bug description**
Importing a Gitlab Secret Detection report generates an error:  list indices must be integers or slices, not str
In both cases: when imported from a pipeline via an API call and from the GUI

**Steps to reproduce**
Import a Gitlab Secret Detection report

**Expected behavior**
The scan should be imported and the findings added to the engagement

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Kubernetes: 1.26.2
 - DefectDojo version v. 2.23.0 ( release mode )

**Logs** 
`[29/Jun/2023 09:08:22] ERROR [dojo.api_v2.exception_handler:32] list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 2302, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 1674, in save
    test, finding_count, closed_finding_count, test_import = importer.import_scan(scan, scan_type, engagement, lead, environment,
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 307, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/gitlab_secret_detection_report/parser.py", line 28, in get_findings
    date = datetime.strptime(data["scan"]["end_time"], "%Y-%m-%dT%H:%M:%S")`

**Sample scan files**
[myjson.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/11903523/myjson.json.txt)

**Screenshots**
Error in the UI
![image](https://github.com/DefectDojo/django-DefectDojo/assets/10922051/dd6c6403-3b1d-45a5-8643-65ff790700eb)

**Comment by cebrat** [comment]
Sorry, the problem was in the scan file format.
