### ISSUE TITLE
ASYNC_FINDING_IMPORT causes 500 http return because of 'str' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by KarstenSiemer** [DefectDojo/django-DefectDojo#8399]
**Slack us first!**
Slack conversation can be found [here](https://owasp.slack.com/archives/C2P5BA8MN/p1689681935467389)

**Be informative**
Version used is 2.23.1

**Bug description**
Hi! I am trying to import some findings into defectdojo and I am getting a http 500 error from the uwsgi container when  ASYNC_FINDING_IMPORT is set to true.
So my problem is that the date, instead of being parsed as an object, gets passed down as, or gets converted, to string somewhere.
Looking at the stacktrace, only protected types are returned in place and unprotected are converted to strings.
The function is_protected_type(obj) checks if the object obj is an instance of any of the types in the _PROTECTED_TYPES tuple. The _PROTECTED_TYPES tuple includes datetime.datetime, datetime.date, and datetime.time among others.
However, when you pass a date as a string like "2023-07-13", it is not an instance of datetime.date or any other date/time type, it's an instance of str. Therefore, is_protected_type("2023-07-13") returns False.
If you want is_protected_type to return True for date strings in the format "YYYY-MM-DD", you would need to parse the string into a datetime.date object before passing it to is_protected_type. Which is missing from the defectdojo code - so any dates in findings will result in such error, as the string needs to be parsed into the actual type before being passed to is_protected_type().

If ASYNC_FINDING_IMPORT is set to false or removed from the environment it works as expected.

Stacktrace ( also included in the logs in the file below)

```
defectdojo-django-5b7557b679-69d26 uwsgi [18/Jul/2023 12:52:11] ERROR [dojo.api_v2.exception_handler:32] 'str' object has no attribute 'isoformat'
defectdojo-django-5b7557b679-69d26 uwsgi Traceback (most recent call last):
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
defectdojo-django-5b7557b679-69d26 uwsgi     response = handler(request, *args, **kwargs)
defectdojo-django-5b7557b679-69d26 uwsgi                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
defectdojo-django-5b7557b679-69d26 uwsgi     self.perform_create(serializer)
defectdojo-django-5b7557b679-69d26 uwsgi   File "/app/dojo/api_v2/views.py", line 2302, in perform_create
defectdojo-django-5b7557b679-69d26 uwsgi     serializer.save(push_to_jira=push_to_jira)
defectdojo-django-5b7557b679-69d26 uwsgi   File "/app/dojo/api_v2/serializers.py", line 1674, in save
defectdojo-django-5b7557b679-69d26 uwsgi     test, finding_count, closed_finding_count, test_import = importer.import_scan(scan, scan_type, engagement, lead, environment,
defectdojo-django-5b7557b679-69d26 uwsgi                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/app/dojo/importers/importer/importer.py", line 321, in import_scan
defectdojo-django-5b7557b679-69d26 uwsgi     result = self.process_parsed_findings(test, findings_list, scan_type, user, active=active,
defectdojo-django-5b7557b679-69d26 uwsgi              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/app/dojo/decorators.py", line 48, in __wrapper__
defectdojo-django-5b7557b679-69d26 uwsgi     return func(*args, **kwargs)
defectdojo-django-5b7557b679-69d26 uwsgi            ^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 188, in __call__
defectdojo-django-5b7557b679-69d26 uwsgi     return self._get_current_object()(*a, **kw)
defectdojo-django-5b7557b679-69d26 uwsgi            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 392, in __call__
defectdojo-django-5b7557b679-69d26 uwsgi     return self.run(*args, **kwargs)
defectdojo-django-5b7557b679-69d26 uwsgi            ^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/app/dojo/importers/importer/importer.py", line 172, in process_parsed_findings
defectdojo-django-5b7557b679-69d26 uwsgi     return [serializers.serialize('json', [finding, ]) for finding in new_findings]
defectdojo-django-5b7557b679-69d26 uwsgi            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/app/dojo/importers/importer/importer.py", line 172, in <listcomp>
defectdojo-django-5b7557b679-69d26 uwsgi     return [serializers.serialize('json', [finding, ]) for finding in new_findings]
defectdojo-django-5b7557b679-69d26 uwsgi             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/django/core/serializers/__init__.py", line 134, in serialize
defectdojo-django-5b7557b679-69d26 uwsgi     s.serialize(queryset, **options)
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 154, in serialize
defectdojo-django-5b7557b679-69d26 uwsgi     self.handle_field(obj, field)
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/django/core/serializers/python.py", line 49, in handle_field
defectdojo-django-5b7557b679-69d26 uwsgi     self._current[field.name] = self._value_from_field(obj, field)
defectdojo-django-5b7557b679-69d26 uwsgi                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/django/core/serializers/python.py", line 46, in _value_from_field
defectdojo-django-5b7557b679-69d26 uwsgi     return value if is_protected_type(value) else field.value_to_string(obj)
defectdojo-django-5b7557b679-69d26 uwsgi                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 1443, in value_to_string
defectdojo-django-5b7557b679-69d26 uwsgi     return "" if val is None else val.isoformat()
defectdojo-django-5b7557b679-69d26 uwsgi                                   ^^^^^^^^^^^^^
defectdojo-django-5b7557b679-69d26 uwsgi AttributeError: 'str' object has no attribute 'isoformat'
defectdojo-django-5b7557b679-69d26 nginx 10.255.14.93 - - [18/Jul/2023:12:52:11 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 500 59 "-" "curl/7.88.1" "10.255.5.162"
```

**Steps to reproduce**
I have used the following script to post a findings.json to defectdojo. The payload passes a load-balancer, then a nginx reverse-proxy (ingress-nginx) with an activated firewall, then goes into the defectodojo pods nginx and from that to the uwsgi socket.

To use the script, it is required to set valid tokens and insert the fqdn of the defectdojo instance. Additionally, there is a need to have a findings.json in the same directory. Which can be found below ( has to be renamed, since I needed to append .txt to be able to upload here).

[script.sh.txt](https://github.com/DefectDojo/django-DefectDojo/files/12093776/script.sh.txt)

Script output then is:

```
❯ ./script.sh                                                                                                                                                                   ─╯
testing syncier-tools import
HTTP/2 500
```

**Expected behavior**

I expect a "HTTP/2 201" return code whether or not ASYNC_FINDING_IMPORT is true or false.
From reading the source code, I did not understand why the fields are serialised if async import is used.
I also did not understand how exactly `scan_date` is expected to be set or used, as only a few of the parsers include code to set scan_date from the payload.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: EKS Bottlerocket
 - DefectDojo version: 2.23.1

**Logs** 
[log.log](https://github.com/DefectDojo/django-DefectDojo/files/12093736/log.log)

**Sample scan files**
[findings.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/12093760/findings.json.txt)

**Comment by valentijnscholten** [comment]
ASYNC_FINDING_IMPORT has been removed from Defect Dojo.
