### ISSUE TITLE
Reports output just a white page

### ISSUE THREAD

**Issue by ismaelcjr** [DefectDojo/django-DefectDojo#8687]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
We're running the docker version of defectdojo 2.26.0 to store and manage daily vulnerabilities for specific softwares from NVD using the native defectdojo API which goes fine. 

Usage is simple: there's a product ("vulnerability") with an associated Engagement (to indicate the day's vulnerabilities) then we have an API Test for each of the listed software's vulnerabilities as corresponding Findings. 

However, when trying to generate report in http://localhost:8080/reports/builder, it only shows a white page.

**Problem description**
White page when getting Reports using http://localhost:8080/reports/builder. No actionable issue from uwsgi container logs

**Steps to reproduce**
1. Set defectdojo debug mode using command "docker/setEnv.sh debug"
2. Build using ./dc-build.sh 
3. Up defectdojo using "./dc-up-d.sh"
4. Add needed Product / Engagement / API Test / Findings manually or via API in your script
5. Go to http://localhost:8080/reports/builder (add the "Report Name" or vary the other inputs) and click "Run" button

**Expected behavior**
There should be some output or a visible error. However, there's none (only whitepage) and checking on container logs for uwsgi, there isn't any actionable issue/error.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04.6 (docker host machine)
 - DefectDojo version: 2.26.0
 - 
**Logs** 
No logs

**Sample scan files**
N/A

**Screenshots**
Nothing to show really, it's a white page

**Additional context** (optional)
This is the default docker setup and I wonder if I am missing something. Tried following https://github.com/DefectDojo/django-DefectDojo/issues/79 but I don't see any logs that would point me where to investigate.

Maybe you can point me to a very simple setup where report would work?

Thanks for your time.

**Comment by mtesauro** [comment]
From your description, I suspect this might be a browser setting or plugin that is negatively impacting the JS used on the report generator.

Have you looked at the dev tools in the browser to see if there's any useful info there?

BTW, https://github.com/DefectDojo/django-DefectDojo/issues/79 is an ancient bug - that was when DefectDojo used to include a PDF generation library. It's been deprecated for many years since there were issues with that library as well as the fact that almost all browsers will "print to PDF" which solves the PDF-ification of reports.

**Comment by ismaelcjr** [comment]
Thank you for the pointers, @mtesauro. I've disabled all the plugins I have installed but unfortunately, the console log in dev tools is still clean. Nothing relevant too in logs except the access of reports page and error when I force reload http://localhost:8080/reports/custom which is kinda expected.

`` [22/Sep/2023 02:46:32] WARNING [django.request:241] Forbidden (Permission denied): /reports/custom
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/reports/views.py", line 120, in custom_report
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
``

**Comment by draetzegueldener** [comment]
Hello,

sorry to restart this old thread. I just started a new instance of defectdojo with version 2.46.1 and i get the same error. I tried multiple Browser, including fresh installed ones. I don't see anything in the logs. Is there something i am missing?


Regards
Dean

**Comment by valentijnscholten** [comment]
@draetzegueldener Are you able to provide us a scan that we can import to reproduce, or can you reproduce it on the https://demo.defectdojo.org. Did you check all the logs of all the containers? And the console log in the browser dev tools?

**Comment by draetzegueldener** [comment]
Hey, i can reproduce it on the demo instance. i tried multiple OS (Linux and Windows) multiple networks (Corporate and private) and, like i said multiple browsers. I put in a Report Name and click run, then i get a blank page.
Maybe it helps, that i don't see the field to upload an image.

I don't see anything in any logs available, i also added debug setting.

I use default harbor vulnerability reports.

![Image](https://github.com/user-attachments/assets/be74bd03-9d20-4543-aaa5-203ae0837e17)


Thanks for the fast answer.


Regards
Dean

**Comment by mustansirgodhrawala** [comment]
Issue still persists. Please provide a resolution, or a ETA to a fix, if any help is needed in logs or other information please let me know

Thank you

**Comment by valentijnscholten** [comment]
I still haven't seen any steps to reproduce this. When you want to generate a report you need to drag and drop the sections you want  from the top right into the report build on the left.

https://docs.defectdojo.com/en/share_your_findings/pro_reports/using_the_report_builder/

**Comment by mustansirgodhrawala** [comment]
Hey I understood, it's a little confusing at first, because the sections from the right need to dragged into the left, thanks for the clarification.

**Comment by draetzegueldener** [comment]
Hello, when i hover over the Reports Panel, i dont get a submenu, and when i click on it, i still get the same form as in my previous screenshot. I tested it on the demo-instance: https://demo.defectdojo.org/reports/builder

**Comment by valentijnscholten** [comment]
> Hey I understood, it's a little confusing at first, because the sections from the right need to dragged into the left, thanks for the clarification.

Yeah I realized that, so we'll look at adding some validation and feedback when users press the Run button instead of showing a white page,
