### ISSUE TITLE
Simultaneous Nuclei Findings Submission from Multiple Agents Causes Internal Server Error

### ISSUE THREAD

**Issue by ErdemOzgen** [DefectDojo/django-DefectDojo#8882]
**Bug description**
While sending nuclei findings from two different agents to DefectDojo simultaneously, the response received was: {"message":"Internal server error, check logs for details"}.
Tested DefectDojo versions: 2.25.1 and 2.27.3

**Steps to reproduce**
1. Deploy any of version 2.25.1 or 2.27.3 with docker compose
2. Setup 2 agents and check these agents can connect to DefectDojo with no problem. 
3. Send two scan results (it may be same scan files or different) to DefectDojo with **sendNuclei.py** or post request with **curl**. (I provide some code for help you quickly reproduce same error)
4. Run python script on two agent/server in same time (Do not forget add IP of DefectDojo.
```bash
python sendNuclei.py --ip {DEFECTDOJOIP} --port 8080 --product_name test --engagement_name test --filename test.json > testresult.json & cat testresult.json
````
5. See error in console
```json
{"message":"Internal server error, check logs for details"}
```

## Python code for **sendNuclei.py**
```python
import argparse
import sendToDefectDojo

# Define command line arguments
parser = argparse.ArgumentParser(description='Send Nuclei results to Defect Dojo')
parser.add_argument('--ip', type=str, default='10.0.10.173', help='Defect Dojo IP address')
parser.add_argument('--port', type=int, default=8080, help='Defect Dojo port')
parser.add_argument('--product_name', type=str, default='test', help='Product name')
parser.add_argument('--engagement_name', type=str, default='test', help='Engagement name')
parser.add_argument('--filename', type=str, help='Path to the filename')

if __name__ == '__main__':
    args = parser.parse_args()
    res, _ = sendToDefectDojo.sendNucleiResults(ip=args.ip, port=args.port, product_name=args.product_name,
                                               engagement_name=args.engagement_name, filename=args.filename)
    print(res)

```

## Python code for **sendToDefectDojo.py**
```python
import datetime, requests, tempfile, json
import os
import psutil

def is_file_exists(file_path):
  if not os.path.exists(file_path):
    return False
  return True

def is_file_in_use(file_path):
    # Check if the file exists
    if not is_file_exists(file_path):
        return False

    # Check if the file is in use by any process
    for process in psutil.process_iter(attrs=['pid', 'name']):
        try:
            open_files = process.open_files()
            for file_info in open_files:
                if file_info.path == file_path:
                    return True
        except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
            pass

    return False


# Define global variables
authToken ="51af4f7d58f181eb95f7226da5459fadbe516f26" # This value is a static value generated by DefectDojo
headers = {
    'accept': 'application/json',
    'Cookie': 'csrftoken=H9Fk3sm1WTdktRSsTzYVlqn7tUrxWO6O; sessionid=tjkgk5v3wx7ufm87o0nlozpv8hn8rg65', #Session ID is also static, like AuthToken
    'X-CSRFToken': 'UIFNzX9AfAMcMEvYNjYqceAUzT1NZydPrHaXsflr1jPm5ldgwIMbnuNRSDiaLc9t',
    'Authorization': f'Token {authToken}',  # Replace {authToken} with your actual token
}

# Make nuclie file acceptable by DefectDojo
def prepareNucleiFile(filename):    
    # Read the JSON file
    with open(filename, 'r') as json_file:
        json_content = json_file.read()

    # Replace ,,{"template" with "\n{"template" in the JSON content
    modified_json_content = json_content[1:].replace(',{"template":', '\n{"template":')[:-1]

    # Write the modified content back to the new temporary file
    temp_file = tempfile.NamedTemporaryFile(delete=False)
    json_file = open(temp_file.name, 'w')
    json_file.write(modified_json_content)
    json_file.close()

    return temp_file.name
    
#Define function to send Nuclei results
def sendNucleiResults(ip:str, filename:str, product_name:str, engagement_name:str, product_type:str="Research and Development", 
                    environment:str="Production", port:int=8080):
    '''
    It gets Nuclei JSON output, sends it to DefectDojo and returns result (JSON/SUCCESS or TXT/FAIL) and Status Code (INT).
    '''
    
    date = str(datetime.datetime.now().strftime("%Y-%m-%d"))

    # Define the form data
    data = {
        'scan_date': f'{date}',  # Replace with the actual scan date
        'minimum_severity': 'Info',
        'active': 'true',
        'verified': 'true',
        'scan_type': 'Nuclei Scan',
        'product_type_name': f'{product_type}',  # Replace with the actual product type
        'product_name': f'{product_name}',  # Replace with the actual product name
        'engagement_name': f'{engagement_name}',  # Replace with the actual engagement name
        'close_old_findings': 'false',
        'close_old_findings_product_scope': 'false',
        'push_to_jira': 'false',
        'environment': f'{environment}',  # Replace with the actual environment
        'create_finding_groups_for_all_findings': 'true',
    }

    #Control file exists and not in use
    if is_file_in_use(filename):
        return '{"Error":"File error occured!"}', 500
    
    temp_file = prepareNucleiFile(filename)

    # Define the file to upload
    with open(temp_file, 'r', encoding='utf-8') as json_file:
        
        files = {'file': ('file.json', json_file, 'application/json')}

        # Make the POST request
        url = f'http://{ip}:{port}/api/v2/import-scan/'
        response = requests.post(url, headers=headers, data=data, files=files)

        # Send the response
        return response.content.decode('utf-8'), response.status_code

```

**Expected behavior**
I expected the findings from both agents to be processed successfully without any errors.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [ Ubuntu 22.04]
 - DefectDojo version : 2.25.1 and 2.27.3 (both tested both works)
 - DefectDojo version: [2023-10-23 10:18:01 -0500] 584371d8d: Merge pull request #8875 from DefectDojo/release/2.27.3 [ (HEAD -> master, tag: 2.27.3, origin/master, origin/HEAD)]
 - Docker version: 24.0.5
 - Docker-compose version: 1.29.2

**Logs** 
Used `docker-compose logs` :+1: 
```bash
172.20.10.6 - - [24/Oct/2023:10:33:48 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1353 "-" "python-requests/2.31.0" "-"
172.20.10.6 - - [24/Oct/2023:10:34:03 +0000] "GET /alerts/count HTTP/1.1" 200 15 "http://10.0.10.173:8080/product" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/24 10:34:05 [warn] 7#7: *88413 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000912, client: 172.20.10.6, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
2023/10/24 10:34:06 [warn] 7#7: *88414 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000913, client: 10.0.10.158, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
10.0.10.158 - - [24/Oct/2023:10:34:18 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1352 "-" "python-requests/2.25.1" "-"
172.20.10.6 - - [24/Oct/2023:10:34:18 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1350 "-" "python-requests/2.31.0" "-"
2023/10/24 10:34:29 [warn] 7#7: *88417 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000914, client: 172.20.10.6, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
2023/10/24 10:34:30 [warn] 7#7: *88418 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000915, client: 10.0.10.158, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
172.20.10.6 - - [24/Oct/2023:10:34:43 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1350 "-" "python-requests/2.31.0" "-"
10.0.10.158 - - [24/Oct/2023:10:34:43 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1350 "-" "python-requests/2.25.1" "-"
2023/10/24 10:34:49 [warn] 7#7: *88421 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000916, client: 172.20.10.6, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
2023/10/24 10:34:50 [warn] 7#7: *88422 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000917, client: 10.0.10.158, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
10.0.10.158 - - [24/Oct/2023:10:35:02 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1352 "-" "python-requests/2.25.1" "-"
172.20.10.6 - - [24/Oct/2023:10:35:03 +0000] "GET /alerts/count HTTP/1.1" 200 15 "http://10.0.10.173:8080/product" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
172.20.10.6 - - [24/Oct/2023:10:35:04 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 1350 "-" "python-requests/2.31.0" "-"
2023/10/24 10:35:15 [warn] 7#7: *88426 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000918, client: 172.20.10.6, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
2023/10/24 10:35:17 [warn] 7#7: *88428 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000919, client: 10.0.10.158, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "10.0.10.173:8080"
172.20.10.6 - - [24/Oct/2023:10:35:29 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 500 59 "-" "python-requests/2.31.0" "-"
10.0.10.158 - - [24/Oct/2023:10:35:29 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 500 59 "-" "python-requests/2.25.1" "-"
172.20.10.6 - - [24/Oct/2023:10:36:03 +0000] "GET /alerts/count HTTP/1.1" 200 15 "http://10.0.10.173:8080/product" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
172.20.10.6 - - [24/Oct/2023:10:37:03 +0000] "GET /alerts/count HTTP/1.1" 200 15 "http://10.0.10.173:8080/product" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
```
**Sample scan files**
You can use any scan files of nuclei just create results with **-je** parameter.

**Screenshots**

![defectissue](https://github.com/DefectDojo/django-DefectDojo/assets/14043035/aeb2ffe2-b4dd-40f2-9dbd-78f50fd3d102)

**Comment by kiblik** [comment]
You provided logs from `nginx`. Can you provide logs from `uwsgi`/`django` instance?

**Comment by ErdemOzgen** [comment]
Log for uwsgi

```bash
[24/Oct/2023 16:06:59] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:07:11] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 29|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:06:59 2023] POST /api/v2/import-scan/ => generated 1350 bytes in 12255 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 1)
[24/Oct/2023 16:08:32] WARNING [django.request:241] Bad Request: /api/v2/import-scan/
[pid: 29|app: -|req: -/-] 10.0.10.158 (-) {46 vars in 901 bytes} [Tue Oct 24 16:08:32 2023] POST /api/v2/import-scan/ => generated 162 bytes in 52 msecs (HTTP/1.1 400) 9 headers in 343 bytes (1 switches on core 0)
[24/Oct/2023 16:09:40] WARNING [django.request:241] Bad Request: /api/v2/import-scan/
[pid: 29|app: -|req: -/-] 10.0.10.158 (-) {46 vars in 901 bytes} [Tue Oct 24 16:09:40 2023] POST /api/v2/import-scan/ => generated 162 bytes in 50 msecs (HTTP/1.1 400) 9 headers in 343 bytes (1 switches on core 1)
[24/Oct/2023 16:12:11] WARNING [django.request:241] Bad Request: /api/v2/import-scan/
[pid: 29|app: -|req: -/-] 10.0.10.158 (-) {46 vars in 901 bytes} [Tue Oct 24 16:12:11 2023] POST /api/v2/import-scan/ => generated 162 bytes in 57 msecs (HTTP/1.1 400) 9 headers in 343 bytes (1 switches on core 0)
[24/Oct/2023 16:14:01] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:14:04] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:14:13] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 30|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:14:01 2023] POST /api/v2/import-scan/ => generated 1350 bytes in 12604 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 0)
[24/Oct/2023 16:14:16] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 29|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:14:04 2023] POST /api/v2/import-scan/ => generated 1350 bytes in 12396 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 1)
[24/Oct/2023 16:14:26] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:14:29] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:14:38] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 30|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:14:25 2023] POST /api/v2/import-scan/ => generated 1350 bytes in 12782 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 1)
[24/Oct/2023 16:14:41] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 29|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:14:29 2023] POST /api/v2/import-scan/ => generated 1350 bytes in 12376 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 0)
[24/Oct/2023 16:15:48] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:15:49] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:16:00] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 1|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:15:48 2023] POST /api/v2/import-scan/ => generated 1353 bytes in 12596 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 0)
[24/Oct/2023 16:16:02] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[pid: 29|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:15:48 2023] POST /api/v2/import-scan/ => generated 1350 bytes in 13524 msecs (HTTP/1.1 201) 9 headers in 340 bytes (1 switches on core 1)
[24/Oct/2023 16:16:15] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:16:15] INFO [dojo.importers.importer.importer:330] IMPORT_SCAN: Collecting Findings
[24/Oct/2023 16:16:27] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[24/Oct/2023 16:16:28] ERROR [dojo.api_v2.exception_handler:36] insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17795) is not present in table "dojo_finding".
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17795) is not present in table "dojo_finding".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3266, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2219, in save
    ) = importer.import_scan(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 357, in import_scan
    test_import = importer_utils.update_import_history(Test_Import.IMPORT_TYPE, active, verified, tags, minimum_severity,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/utils.py", line 82, in update_import_history
    Test_Import_Finding_Action.objects.bulk_create(test_import_finding_action_list)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 796, in bulk_create
    with transaction.atomic(using=self.db, savepoint=False):
  File "/usr/local/lib/python3.11/site-packages/django/db/transaction.py", line 262, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in commit
    self._commit()
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 305, in _commit
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17795) is not present in table "dojo_finding".

[24/Oct/2023 16:16:28] INFO [dojo.importers.importer.importer:334] IMPORT_SCAN: All Findings Collected
[24/Oct/2023 16:16:28] ERROR [django.request:241] Internal Server Error: /api/v2/import-scan/
[pid: 1|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:16:15 2023] POST /api/v2/import-scan/ => generated 59 bytes in 12972 msecs (HTTP/1.1 500) 9 headers in 352 bytes (1 switches on core 1)
[24/Oct/2023 16:16:28] ERROR [dojo.api_v2.exception_handler:36] insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17811) is not present in table "dojo_finding".
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17811) is not present in table "dojo_finding".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3266, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2219, in save
    ) = importer.import_scan(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 357, in import_scan
    test_import = importer_utils.update_import_history(Test_Import.IMPORT_TYPE, active, verified, tags, minimum_severity,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/utils.py", line 82, in update_import_history
    Test_Import_Finding_Action.objects.bulk_create(test_import_finding_action_list)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 796, in bulk_create
    with transaction.atomic(using=self.db, savepoint=False):
  File "/usr/local/lib/python3.11/site-packages/django/db/transaction.py", line 262, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in commit
    self._commit()
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 305, in _commit
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17811) is not present in table "dojo_finding".

[24/Oct/2023 16:16:28] ERROR [django.request:241] Internal Server Error: /api/v2/import-scan/
[pid: 29|app: -|req: -/-] 172.20.10.6 (-) {46 vars in 905 bytes} [Tue Oct 24 16:16:15 2023] POST /api/v2/import-scan/ => generated 59 bytes in 12435 msecs (HTTP/1.1 500) 9 headers in 352 bytes (1 switches on core 0
```

**Comment by ErdemOzgen** [comment]
The logs I have provided show that there's an integrity issue with the database when trying to insert or update records in the table dojo_test_import_finding_action. Specifically, it seems that dojo trying to reference a finding_id which doesn't exist in the dojo_finding table.

Here are the relevant log lines extracted from above:

```bash
psycopg2.errors.ForeignKeyViolation: insert or update on table "dojo_test_import_finding_action" violates foreign key constraint "dojo_test_import_fin_finding_id_28fe8e2d_fk_dojo_find"
DETAIL:  Key (finding_id)=(17795) is not present in table "dojo_finding".
```
We can start investigate in here.

**Comment by ErdemOzgen** [comment]
DD_ASYNC_FINDING_IMPORT=(bool, True) . I have been set ASYNC_FINDING_IMPORT to True in local_settings.py.

**Comment by stchstepan** [comment]
Hi
Did you manage to solve the problem? We encounter the same errors, but not only with Nuklei. DefectDojo deployed to Kubernetes

**Comment by valentijnscholten** [comment]
The logs seem to indicate an error related to deduplication where duplicate findings are deleted before the import is fully completed. This should be mostly fixed in 2.43.3 that was released today, see similar issue #6217.
Can you let us know your results after updating to 2.43.3 @stchstepan @ErdemOzgen

**Comment by stchstepan** [comment]
@valentijnscholten hello
yes, we will try it and write review
