### ISSUE TITLE
When Jira configuration is added & `Push to Jira` enabled on existing Findings they are not synced to Jira

### ISSUE THREAD

**Issue by chris-vest** [DefectDojo/django-DefectDojo#894]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

1. Engagement `A` exists
2. Findings under Engagement `A` exist
3. Jira integration is configured for DefectDojo
4. Jira integration is configured for Engagement `A`
5. Issue under Engagement `A` is updated with `Push to Jira` enabled

```text
33 | 13/02/201915:28:18.811 +0000 | Exception: JIRA_Issue matching query does not exist.
-- | -- | --
34 | 13/02/201915:28:18.811 +0000 | self.model._meta.object_name
35 | 13/02/201915:28:18.810 +0000 | File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
36 | 13/02/201915:28:18.810 +0000 | File "/opt/django-DefectDojo/dojo/utils.py", line 1066, in update_issue
37 | 13/02/201915:28:18.810 +0000 | File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
38 | 13/02/201915:28:18.810 +0000 | return getattr(self.get_queryset(), name)(*args, **kwargs)
39 | 13/02/201915:28:18.810 +0000 | j_issue = JIRA_Issue.objects.get(finding=find)
40 | 13/02/201915:28:18.809 +0000 | File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
41 | 13/02/201915:28:18.809 +0000 | File "/opt/django-DefectDojo/dojo/tasks.py", line 235, in update_issue_task
42 | 13/02/201915:28:18.809 +0000 | return self.run(*args, **kwargs)
43 | 13/02/201915:28:18.809 +0000 | update_issue(find, old_status, push_to_jira)
44 | 13/02/201915:28:18.808 +0000 | File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
45 | 13/02/201915:28:18.808 +0000 | Traceback (most recent call last):
46 | 13/02/201915:28:18.808 +0000 | R = retval = fun(*args, **kwargs)
```

### Operating System 
Docker

### Install
- [ ] setup.bash
- [x] docker

### DefectDojo Version
1.5.3.1

**Comment by valentijnscholten** [comment]
@chris-vest Could you test this with the dev branch? I'm pretty sure I have tested this case multiple times when working on some PRs and it was working OK.

**Comment by chris-vest** [comment]
@valentijnscholten Sorry, missed your comment, will attempt to rebuild and test again.
