### ISSUE TITLE
Can't delete group

### ISSUE THREAD

**Issue by tsukiazuma** [DefectDojo/django-DefectDojo#9314]
**Bug description**
Can't delete group

**Steps to reproduce**
1. Create new group
2. Add member
3. Delete group -> Error
![image](https://github.com/DefectDojo/django-DefectDojo/assets/75791054/cd20826b-53cd-4b30-a777-dec11c5f061f)

**Deployment method** *(select with an `X`)*
- [X] Docker Compose

**Environment information**
 - Operating System: Red Hat Enterprise Linux version 8.5 (Ootpa)
 - DefectDojo version: v2.29.1
**Logs** 
```
django-defectdojo-master-uwsgi-1  | [11/Jan/2024 08:13:58] INFO [django.request:241] OK: /group/2/delete
django-defectdojo-master-uwsgi-1  | Traceback (most recent call last):
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
django-defectdojo-master-uwsgi-1  |     return self.cursor.execute(sql, params)
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  | psycopg2.errors.UndefinedColumn: column dojo_system_settings.enable_auditlog does not exist
django-defectdojo-master-uwsgi-1  | LINE 1: SELECT "dojo_system_settings"."id", "dojo_system_settings"."...
django-defectdojo-master-uwsgi-1  |                                             ^
django-defectdojo-master-uwsgi-1  |
django-defectdojo-master-uwsgi-1  |
django-defectdojo-master-uwsgi-1  | The above exception was the direct cause of the following exception:
django-defectdojo-master-uwsgi-1  |
django-defectdojo-master-uwsgi-1  | Traceback (most recent call last):
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
django-defectdojo-master-uwsgi-1  |     response = get_response(request)
django-defectdojo-master-uwsgi-1  |                ^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
django-defectdojo-master-uwsgi-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-defectdojo-master-uwsgi-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
django-defectdojo-master-uwsgi-1  |     return self.dispatch(request, *args, **kwargs)
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
django-defectdojo-master-uwsgi-1  |     return handler(request, *args, **kwargs)
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/app/dojo/group/views.py", line 265, in get
django-defectdojo-master-uwsgi-1  |     context = self.get_initial_context(request, group)
django-defectdojo-master-uwsgi-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/app/dojo/group/views.py", line 227, in get_initial_context
django-defectdojo-master-uwsgi-1  |     collector.collect([group])
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 186, in collect
django-defectdojo-master-uwsgi-1  |     return super().collect(objs, source_attr=source_attr, **kwargs)
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/deletion.py", line 343, in collect
django-defectdojo-master-uwsgi-1  |     if sub_objs:
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 408, in __bool__
django-defectdojo-master-uwsgi-1  |     self._fetch_all()
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
django-defectdojo-master-uwsgi-1  |     self._result_cache = list(self._iterable_class(self))
django-defectdojo-master-uwsgi-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
django-defectdojo-master-uwsgi-1  |     results = compiler.execute_sql(
django-defectdojo-master-uwsgi-1  |               ^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
django-defectdojo-master-uwsgi-1  |     cursor.execute(sql, params)
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
django-defectdojo-master-uwsgi-1  |     return self._execute_with_wrappers(
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
django-defectdojo-master-uwsgi-1  |     return executor(sql, params, many, context)
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
django-defectdojo-master-uwsgi-1  |     with self.db.wrap_database_errors:
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
django-defectdojo-master-uwsgi-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
django-defectdojo-master-uwsgi-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
django-defectdojo-master-uwsgi-1  |     return self.cursor.execute(sql, params)
django-defectdojo-master-uwsgi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-master-uwsgi-1  | django.db.utils.ProgrammingError: column dojo_system_settings.enable_auditlog does not exist
django-defectdojo-master-uwsgi-1  | LINE 1: SELECT "dojo_system_settings"."id", "dojo_system_settings"."...
django-defectdojo-master-uwsgi-1  |                                             ^
django-defectdojo-master-uwsgi-1  |
```

**Comment by kiblik** [comment]
Hmmm... this is interesting.
Your issue is not connected only to the management of group but to different components (the mentioned error is just a side-effect).
Based on the logs I see that `enable_auditlog` is missing. This field has been removed in #9002, released in [v2.30.0](https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.30.0)
It looks like you somehow ran `initializer` in version 2.30.0 (or 2.30.1) but `uwsgi` in 2.29.1.
Quite an unusual situation. Usually, if there is some issue, versions are opposite (new `uwsgi`, old `initializer`).

A couple of investigation questions:
- Did you set `DJANGO_VERSION`? If so how?
- Did you run `git pull` (on another git command)?
- Did you run `./dc-build.sh` recently?
- Did you perform any changes in to the code?

**Comment by tsukiazuma** [comment]
Oh, before I tried to upgrate version to v2.30.0 with https://defectdojo.github.io/django-DefectDojo/getting_started/upgrading/
But when success update v2.30.0, I can't authen LDAP - can see it here: https://github.com/DefectDojo/django-DefectDojo/issues/9272
So I remove 2 image: `defectdojo/defectdojo-django:latest, defectdojo/defectdojo-nginx:latest`. Then run: `./dc-build.sh` and `./dc-up-d.sh postgres-redis` to use old version: v2.29.1

**Comment by kiblik** [comment]
A downgrade from `2.30.0` to `2.29.1` would be possible but it is necessary to perform the migration manually.

```bash
python manage.py migrate dojo 0193_remove_system_settings_enable_auditlog
```

**Comment by tsukiazuma** [comment]
Oh, thank you and one more question
Why upgrade v2.29.1 to v2.30.0, authen with LDAP is not work

**Comment by kiblik** [comment]
`docker exec -it django-defectdojo-uwsgi-1 python manage.py migrate dojo 0193_remove_system_settings_enable_auditlog`

**Comment by tsukiazuma** [comment]
Can't find a migration:
```
/usr/local/lib/python3.11/site-packages/coreapi/codecs/download.py:5: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
CommandError: Cannot find a migration matching '0193_remove_system_settings_enable_auditlog' from app 'dojo'.
```
And I don't see it when show migration with:
```
docker exec -it django-defectdojo-master-uwsgi-1 python manage.py showmigrations dojo
/usr/local/lib/python3.11/site-packages/coreapi/codecs/download.py:5: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
dojo
 [X] 0001_squashed_0090_index_duplicate_finding (90 squashed migrations)
 [X] 0091_npm_audit_path_censoring
 [X] 0092_is_mitigated
 [X] 0093_django_tagging_removal
 [X] 0094_remove_system_settings_s_finding_severity_naming
 [X] 0095_remove_old_product_contact_fields
 [X] 0096_grype_name_change
 [X] 0097_engagement_type
 [X] 0098_anchore_vuln_id
 [X] 0099_delete_report
 [X] 0100_dojo_user_for_authv2
 [X] 0101_enable_features
 [X] 0102_dojo_group
 [X] 0103_report_notification
 [X] 0104_endpoint_userinfo_creation
 [X] 0105_endpoint_host_migration
 [X] 0106_role_model
 [X] 0107_global_role
 [X] 0108_blank_fields
 [X] 0109_group_user_role
 [X] 0110_auth_v2_migrate_user_roles
 [X] 0111_group_user_rename
 [X] 0112_group_user_rename_2
 [X] 0113_endpoint_protocol
 [X] 0114_cyclonedx_vuln_uniqu
 [X] 0115_language_types
 [X] 0116_test_type_active
 [X] 0117_usercontactinfo_force_password_reset
 [X] 0118_remove_finding_images
 [X] 0119_default_group_is_staff
 [X] 0120_sonarqube_test_and_clean
 [X] 0121_user_restrict
 [X] 0122_cobaltio_product
 [X] 0123_scan_type
 [X] 0124_sonarqube_api_type_length_change
 [X] 0125_sonarqube_clean
 [X] 0126_finding_publish_date
 [X] 0127_remove_hashes
 [X] 0128_pytz_update
 [X] 0129_finding_deprecated_fields
 [X] 0130_product_api_scan_configuration
 [X] 0131_migrate_sonarcube_cobalt
 [X] 0132_remove_configs_from_test
 [X] 0133_finding_service
 [X] 0134_sonarque_cobaltio_removal
 [X] 0135_email_from
 [X] 0136_default_group_help_text
 [X] 0137_system_settings_enable_endpoint_metadata_import
 [X] 0138_remove_authorized_users
 [X] 0139_google_sheets_rules_framework_enable
 [X] 0140_auth_group
 [X] 0141_enable_user_profile_editable
 [X] 0142_environment_delete
 [X] 0143_objects
 [X] 0144_import_action_untouched
 [X] 0145_system_settings_default_group_email_pattern
 [X] 0146_lead_optional
 [X] 0147_rename_sslyze_parser
 [X] 0148_default_notifications
 [X] 0149_harmonize_user_format
 [X] 0150_dedupe_endpoint_status
 [X] 0151_index_endpoint_status
 [X] 0152_notifications_template
 [X] 0153_migrate_endpoint_mitigated
 [X] 0154_remove_endpoint_mitigated
 [X] 0155_enable_finding_groups
 [X] 0156_migrate_finding_groups_setting
 [X] 0157_vulnerability_reference
 [X] 0158_vulnerability_id
 [X] 0159_remove_broken_endpoint_statuses
 [X] 0160_set_notnull_endpoint_statuses
 [X] 0161_alter_dojo_group_social_provider
 [X] 0162_created_and_updated
 [X] 0163_system_settings_enable_calendar
 [X] 0164_remove_system_settings_staff_user_email_pattern
 [X] 0165_custom_sla
 [X] 0166_copy_sla_from_system_settings
 [X] 0167_system_settings_add_vulnerability_id_to_jira_label
 [X] 0168_alter_system_settings_time_zone
 [X] 0169_planned_remediation_date
 [X] 0170_jira_project_custom_fields
 [X] 0171_jira_labels_per_product_and_engagement
 [X] 0172_optimize_usage_of_endpoint_status
 [X] 0173_alter_risk_acceptance_name
 [X] 0174_jira_project_default_assignee
 [X] 0175_system_settings_enable_notify_sla
 [X] 0176_custom_password_requirements
 [X] 0177_alter_system_settings_time_zone
 [X] 0178_alter_answer_polymorphic_ctype_and_more
 [X] 0179_alter_finding_verified
 [X] 0180_announcement_userannouncement
 [X] 0181_jira_instance_finding_jira_sync
 [X] 0182_alter_jira_instance_default_issue_type
 [X] 0183_system_settings_enable_notify_sla_exponential_backoff_and_more
 [X] 0184_remove_child_rule_parent_rule_delete_fieldrule_and_more
 [X] 0185_product_disable_sla_breach_notifications_and_more
 [X] 0186_system_settings_non_common_password_required
 [X] 0187_nessus_to_tenable
 [X] 0188_product_enable_product_tag_inheritance_and_more
 [X] 0189_finding_effort_and_remediation_for_fixing
 [X] 0190_system_settings_experimental_fp_history
 [X] 0191_alter_notifications_risk_acceptance_expiration
 [X] 0192_notifications_scan_added_empty
```

**Comment by kiblik** [comment]
In my opinion, the best option would be to drop LDAP and move to sth more modern. To not be stacked with the old version of DD.

If it is not an option, can you try following?
- upgrade to 2.30.0
- let finish the initializer (until it is successfully done)
- run downgrade of database (`docker exec -it django-defectdojo-master-uwsgi-1 python manage.py migrate dojo 0193_remove_system_settings_enable_auditlog`). Yes, on 2.30.0
- stop the instance
- downgrade to 2.29.x (there is not that huge difference between these versions)
- start an instance on 2.30.0 and hope, it will work

**Comment by tsukiazuma** [comment]
My goal is to be able to continue using LDAP on the new version.
And I don't clear at:
- downgrade to 2.29.x (there is not that huge difference between these versions)
- start an instance on 2.30.0 and hope, it will work
Please, give more detail information
