### ISSUE TITLE
ERROR [dojo.notifications.helper:300] [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by tsukiazuma** [DefectDojo/django-DefectDojo#9335]
**Problem description**
Can't send email notification to user

**Steps to reproduce**
1. Go to file `postgres-redis.env` in folder `docker/environments/`
2. Add email configure: `DD_EMAIL_URL=smtp://:@x.x.x.x:25`
3. Build and up: `./dc-build.sh` and `./dc-up-d.sh`
4. Add new products on web UI and check send email notification error: [Errno 99] Cannot assign requested address
![image](https://github.com/DefectDojo/django-DefectDojo/assets/75791054/adae14ba-48c3-4551-857a-59f36bc4b12f)

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Red Hat Enterprise Linux release 8.4 (Ootpa)
 - DefectDojo version: v. 2.27.4

**Logs** 
```
django-defectdojo-celeryworker-1  | [16/Jan/2024 09:36:05] INFO [celery.worker.strategy:161] Task dojo.notifications.helper.send_mail_notification[b9fea04f-de01-4f5b-8b0a-2c88ce50a172] received
django-defectdojo-celeryworker-1  | [16/Jan/2024 09:36:05] ERROR [dojo.notifications.helper:300] [Errno 99] Cannot assign requested address
django-defectdojo-celeryworker-1  | Traceback (most recent call last):
django-defectdojo-celeryworker-1  |   File "/app/dojo/notifications/helper.py", line 297, in send_mail_notification
django-defectdojo-celeryworker-1  |     email.send(fail_silently=False)
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send
django-defectdojo-celeryworker-1  |     return self.get_connection(fail_silently).send_messages([self])
django-defectdojo-celeryworker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages
django-defectdojo-celeryworker-1  |     new_conn_created = self.open()
django-defectdojo-celeryworker-1  |                        ^^^^^^^^^^^
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 80, in open
django-defectdojo-celeryworker-1  |     self.connection = self.connection_class(
django-defectdojo-celeryworker-1  |                       ^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
django-defectdojo-celeryworker-1  |     (code, msg) = self.connect(host, port)
django-defectdojo-celeryworker-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/smtplib.py", line 341, in connect
django-defectdojo-celeryworker-1  |     self.sock = self._get_socket(host, port, self.timeout)
django-defectdojo-celeryworker-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/smtplib.py", line 312, in _get_socket
django-defectdojo-celeryworker-1  |     return socket.create_connection((host, port), timeout,
django-defectdojo-celeryworker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
django-defectdojo-celeryworker-1  |     raise exceptions[0]
django-defectdojo-celeryworker-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
django-defectdojo-celeryworker-1  |     sock.connect(sa)
django-defectdojo-celeryworker-1  | OSError: [Errno 99] Cannot assign requested address
```

**Comment by mtesauro** [comment]
First time I've see this happen. Since you're using compose and the underlying OS is reporting that it cannot assign that address, I'm wondering if there's an IP conflict between the range that Docker wants to use for it's 'internal' network and the IP you set for the SMTP service.

**Comment by tsukiazuma** [comment]
I don't understand, so I will show more information:
1. Range Docker: 172.18.0.x:
- django-defectdojo-nginx-1: 172.18.0.8
- django-defectdojo-celeryworker-1: 172.18.0.7
- django-defectdojo-uwsgi-1: 172.18.0.5
- django-defectdojo-celerybeat-1: 172.18.0.6
- django-defectdojo-redis-1: 172.18.0.3
- django-defectdojo-postgres-1: 172.18.0.2
```
Detail information network of django-defectdojo-nginx-1:
"NetworkID": "3da245328cffcf93f24ae4ec7b208d52580c534a61d78d0f608eed724ee6283c",
"EndpointID": "9f8aa0b64529dcf2efb2c50f20925c02aaaa7d9068ffd8ba931db74b475047ff",
"Gateway": "172.18.0.1",
"IPAddress": "172.18.0.8",
"IPPrefixLen": 16,
"IPv6Gateway": "",
"GlobalIPv6Address": "",
"GlobalIPv6PrefixLen": 0,
"MacAddress": "02:42:ac:12:00:08",
"DriverOpts": null
```
2. IP SMTP: 172.26.1.x

**Comment by valentijnscholten** [comment]
Are you still experiencing this problem?
