### ISSUE TITLE
Server 500 Internal Error randomly when reimport finding

### ISSUE THREAD

**Issue by tientmse62290** [DefectDojo/django-DefectDojo#9474]
**Bug description**
I use dd-import (https://github.com/MaibornWolff/dd-import) to import finding include:
- dependency-check XML file
- CycloneDX sbom json file
- semgrep json file

But they cannot run for the whole process, they always throw 500 Internal Server Errors when upload one of them randomly.

**Steps to reproduce**
```
docker run -e "DD_URL=https://defect:8443" -e "DD_API_KEY=xxx" -e "DD_PRODUCT_TYPE_NAME=${CI_PROJECT_NAMESPACE}" -e "DD_PRODUCT_NAME=${CI_PROJECT_NAME}" -e "DD_ENGAGEMENT_NAME=Depscan" -e "DD_TEST_NAME=DepscanCI-${CI_COMMIT_BRANCH}" -e "DD_TEST_TYPE_NAME=CycloneDX Scan" -e "DD_SSL_VERIFY=0" -e "DD_FILE_NAME=sbom-universal.vdr.json" -v $MOUNT_NAME:/builds:rw -w /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/reports docker.xxx.com/qweqq/dd-import:1.0.12 dd-reimport-findings.sh

docker run -e "DD_URL=https://defect:8443" -e "DD_API_KEY=xxx" -e "DD_PRODUCT_TYPE_NAME=${CI_PROJECT_NAMESPACE}" -e "DD_PRODUCT_NAME=${CI_PROJECT_NAME}" -e "DD_ENGAGEMENT_NAME=DependencyCheck" -e "DD_TEST_NAME=DependencyCheckCI-${CI_COMMIT_BRANCH}" -e "DD_TEST_TYPE_NAME=Dependency Check Scan" -e "DD_SSL_VERIFY=0" -e "DD_FILE_NAME=dependency-check-report.xml" -v $MOUNT_NAME:/builds:rw -w /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/reports docker.xxx.com/qweqq/dd-import:1.0.12 dd-reimport-findings.sh

docker run -e "DD_URL=https://defect:8443" -e "DD_API_KEY=xxx" -e "DD_PRODUCT_TYPE_NAME=${CI_PROJECT_NAMESPACE}" -e "DD_PRODUCT_NAME=${CI_PROJECT_NAME}" -e "DD_ENGAGEMENT_NAME=SemgrepScan" -e "DD_TEST_NAME=SemgrepCI-${CI_COMMIT_BRANCH}" -e "DD_TEST_TYPE_NAME=Semgrep JSON Report" -e "DD_SSL_VERIFY=0" -e "DD_FILE_NAME=semgrepScan.json" -e "DD_SSL_VERIFY=0" -v $MOUNT_NAME:/builds:rw -w /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/reports docker.xxx.com/qweqq/dd-import:1.0.12 dd-reimport-findings.sh
```

**Expected behavior**
Output: Scan results imported

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo version: v. 2.30.4 ( release mode )

**Logs** 
```
[pid: 26|app: -|req: -/-] 192.168.67.34 (-) {42 vars in 640 bytes} [Mon Feb  5 06:52:28 2024] GET /api/v2/product_types/?name=apidemo => generated 276 bytes in 181 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 0)
[pid: 1|app: -|req: -/-] 192.168.67.34 (-) {42 vars in 670 bytes} [Mon Feb  5 06:52:28 2024] GET /api/v2/products/?name=frontend&prod_type=3 => generated 823 bytes in 184 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 0)
[pid: 1|app: -|req: -/-] 192.168.67.34 (-) {42 vars in 654 bytes} [Mon Feb  5 06:52:29 2024] GET /api/v2/engagements/?name=Depscan&product=6 => generated 868 bytes in 389 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.34 (-) {42 vars in 712 bytes} [Mon Feb  5 06:52:29 2024] GET /api/v2/tests/?title=DepscanCI-sonarqube%2Fdependency-check&engagement=8 => generated 622 bytes in 330 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 1)
[05/Feb/2024 06:52:30] ERROR [dojo.api_v2.exception_handler:36] 'vector'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3238, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2502, in save
    ) = reimporter.reimport_scan(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 609, in reimport_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/cyclonedx/parser.py", line 364, in get_findings
    return self._get_findings_json(file, test)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/cyclonedx/parser.py", line 444, in _get_findings_json
    raw_vector = rating["vector"]
                 ~~~~~~^^^^^^^^^^
KeyError: 'vector'
[05/Feb/2024 06:52:30] ERROR [django.request:241] Internal Server Error: /api/v2/reimport-scan/

```

**Comment by tientmse62290** [comment]
Retry and now DepscanCI passed but not the dependencycheck
Dependencycheck version 8.0.2

it's so random :(

```
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 640 bytes} [Mon Feb  5 07:50:43 2024] GET /api/v2/product_types/?name=apidemo => generated 276 bytes in 170 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 670 bytes} [Mon Feb  5 07:50:44 2024] GET /api/v2/products/?name=frontend&prod_type=3 => generated 823 bytes in 242 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 0)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 654 bytes} [Mon Feb  5 07:50:44 2024] GET /api/v2/engagements/?name=Depscan&product=6 => generated 868 bytes in 150 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 712 bytes} [Mon Feb  5 07:50:44 2024] GET /api/v2/tests/?title=DepscanCI-sonarqube%2Fdependency-check&engagement=8 => generated 622 bytes in 144 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 0)
[pid: 26|app: -|req: -/-] 192.168.52.99 (ddimport) {52 vars in 856 bytes} [Mon Feb  5 07:50:44 2024] GET /alerts/count => generated 13 bytes in 68 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {44 vars in 743 bytes} [Mon Feb  5 07:50:45 2024] POST /api/v2/reimport-scan/ => generated 4991 bytes in 1955 msecs (HTTP/1.1 201) 8 headers in 241 bytes (1 switches on core 0)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 640 bytes} [Mon Feb  5 07:50:54 2024] GET /api/v2/product_types/?name=apidemo => generated 276 bytes in 100 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 1)
[pid: 1|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 670 bytes} [Mon Feb  5 07:50:54 2024] GET /api/v2/products/?name=frontend&prod_type=3 => generated 823 bytes in 213 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 670 bytes} [Mon Feb  5 07:50:54 2024] GET /api/v2/engagements/?name=DependencyCheck&product=6 => generated 66 bytes in 94 msecs (HTTP/1.1 200) 8 headers in 245 bytes (1 switches on core 0)
[pid: 26|app: -|req: -/-] 192.168.52.99 (ddimport) {52 vars in 856 bytes} [Mon Feb  5 07:50:54 2024] GET /alerts/count => generated 13 bytes in 64 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {44 vars in 639 bytes} [Mon Feb  5 07:50:55 2024] POST /api/v2/engagements/ => generated 811 bytes in 432 msecs (HTTP/1.1 201) 8 headers in 251 bytes (1 switches on core 0)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 730 bytes} [Mon Feb  5 07:50:55 2024] GET /api/v2/tests/?title=DependencyCheckCI-sonarqube%2Fdependency-check&engagement=10 => generated 66 bytes in 101 msecs (HTTP/1.1 200) 8 headers in 245 bytes (1 switches on core 1)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {42 vars in 660 bytes} [Mon Feb  5 07:50:55 2024] GET /api/v2/test_types/?name=Dependency+Check+Scan => generated 147 bytes in 65 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 0)
[pid: 26|app: -|req: -/-] 192.168.67.33 (-) {44 vars in 627 bytes} [Mon Feb  5 07:50:56 2024] POST /api/v2/tests/ => generated 510 bytes in 200 msecs (HTTP/1.1 201) 8 headers in 251 bytes (1 switches on core 1)
[05/Feb/2024 07:50:56] ERROR [dojo.api_v2.exception_handler:36] not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1709, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/dojo/api_v2/serializers.py", line 2502, in save
    ) = reimporter.reimport_scan(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 609, in reimport_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/dependency_check/parser.py", line 362, in get_findings
    scan = ElementTree.fromstring(content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1711, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3238, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2594, in save
    raise Exception(se)
Exception: not well-formed (invalid token): line 1, column 0
[05/Feb/2024 07:50:56] ERROR [django.request:241] Internal Server Error: /api/v2/reimport-scan/
```

**Comment by tientmse62290** [comment]
The gitlabCI output:

```
Status: Downloaded newer image for docker.xxx.com/qweqq/dd-import:1.0.12
DD_URL:                              https://defect:8443
DD_PRODUCT_TYPE_NAME:                apidemo
DD_PRODUCT_NAME:                     frontend
DD_ENGAGEMENT_NAME:                  Depscan
DD_ENGAGEMENT_TARGET_START:          2024-02-05
DD_ENGAGEMENT_TARGET_END:            2999-12-31
DD_TEST_NAME:                        DepscanCI-sonarqube/dependency-check
DD_TEST_TYPE_NAME:                   CycloneDX Scan
DD_FILE_NAME:                        sbom-universal.vdr.json
DD_ACTIVE:                           True
DD_VERIFIED:                         True
DD_MINIMUM_SEVERITY:                 None
DD_GROUP_BY:                         None
DD_PUSH_TO_JIRA:                     False
DD_CLOSE_OLD_FINDINGS:               True
DD_CLOSE_OLD_FINDINGS_PRODUCT_SCOPE: False
DD_DO_NOT_REACTIVATE:                False
DD_VERSION:                          None
DD_ENDPOINT_ID:                      None
DD_SERVICE:                          None
DD_BUILD_ID:                         None
DD_COMMIT_HASH:                      None
DD_BRANCH_TAG:                       None
DD_API_SCAN_CONFIGURATION_ID:        None
DD_SOURCE_CODE_MANAGEMENT_URI:       None
DD_SSL_VERIFY:                       False
DD_EXTRA_HEADER_1:                   None
DD_EXTRA_HEADER_2:                   None
Product type found, id:  3
Product found,      id:  6
Engagement found,   id:  8
Test found,         id:  6
Scan results imported
DD_URL:                              https://defect:8443
DD_PRODUCT_TYPE_NAME:                apidemo
DD_PRODUCT_NAME:                     frontend
DD_ENGAGEMENT_NAME:                  DependencyCheck
DD_ENGAGEMENT_TARGET_START:          2024-02-05
DD_ENGAGEMENT_TARGET_END:            2999-12-31
DD_TEST_NAME:                        DependencyCheckCI-sonarqube/dependency-check
DD_TEST_TYPE_NAME:                   Dependency Check Scan
DD_FILE_NAME:                        dependency-check-report.xml
DD_ACTIVE:                           True
DD_VERIFIED:                         True
DD_MINIMUM_SEVERITY:                 None
DD_GROUP_BY:                         None
DD_PUSH_TO_JIRA:                     False
DD_CLOSE_OLD_FINDINGS:               True
DD_CLOSE_OLD_FINDINGS_PRODUCT_SCOPE: False
DD_DO_NOT_REACTIVATE:                False
DD_VERSION:                          None
DD_ENDPOINT_ID:                      None
DD_SERVICE:                          None
DD_BUILD_ID:                         None
DD_COMMIT_HASH:                      None
DD_BRANCH_TAG:                       None
DD_API_SCAN_CONFIGURATION_ID:        None
DD_SOURCE_CODE_MANAGEMENT_URI:       None
DD_SSL_VERIFY:                       False
DD_EXTRA_HEADER_1:                   None
DD_EXTRA_HEADER_2:                   None
Product type found, id:  3
Product found,      id:  6
New engagement,     id:  10
New test,           id:  8
500 Server Error: Internal Server Error for url: https://defect:8443/api/v2/reimport-scan/
```

**Comment by kiblik** [comment]
Regarding `CycloneDX Scan`, it looks like your report has a different data structure than the parser expects. Can you provide your report? The parser might be adjusted based on it.

**Comment by kiblik** [comment]
Same for `Dependency Check Scan`

**Comment by tientmse62290** [comment]
[reports.zip](https://github.com/DefectDojo/django-DefectDojo/files/14173628/reports.zip)
Hi this is the report file from scanner

**Comment by manuel-sommer** [comment]
Hi @tientmse62290 ,
regarding dependencycheck: You have a .xml file, but the content is clearly JSON. So you try to upload JSON content here in a .xml file. 
regarding Cyclonedx: I am investigating.

**Comment by tientmse62290** [comment]
Hi @manuel-sommer ,
Sorry for that. I don't know why dependencycheck generate wrong format for XML. I will investigate it more.
Thank you alot

**Comment by manuel-sommer** [comment]
This is the result of Cyclonedx, it just worked fine. 
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/cd3607b2-924c-48b5-a81c-fba37e60850c)

**Comment by manuel-sommer** [comment]
I guess this ticket can be closed @mtesauro .

**Comment by tientmse62290** [comment]
![image](https://github.com/DefectDojo/django-DefectDojo/assets/28757980/56870543-7fa9-4265-b11a-9e16cf2b18cd)
latest testing till get the error. Any idea for the error?
I use VDR result that based on cycloneDX 1.5 format because there are no support for any Depscan output yet.

**Comment by manuel-sommer** [comment]
Could you provide the output file (anonymized)?
I used the latest dev built (2.32.0)

**Comment by manuel-sommer** [comment]
Which version are you using? For me it works fine, out of the box with v 2.32.0. 
I uploaded sbom-universal-vdr.json into cyclonedx

**Comment by manuel-sommer** [comment]
Can you confirm @kiblik ?

**Comment by tientmse62290** [comment]
I use  v. 2.30.4 with prebuild image from dockerhub

**Comment by manuel-sommer** [comment]
I uploaded the file now via REST API with python. It worked fine. 

```
nginx-1         | 172.18.0.1 - - [08/Feb/2024:07:31:42 +0000] "POST /api/v2/reimport-scan/ HTTP/1.1" 201 5116 "-" "DefectDojo_api/1.2.0." "-"
uwsgi-1         | [pid: 30|app: -|req: -/-] 172.18.0.1 (-) {42 vars in 705 bytes} [Thu Feb  8 07:31:42 2024] POST /api/v2/reimport-scan/ => generated 5116 bytes in 158 msecs (HTTP/1.1 201) 8 headers in 241 bytes (1 switches on core 1)
```

Can you close this issue @mtesauro ?
