### ISSUE TITLE
Error: Finding integration tests test failed

### ISSUE THREAD

**Issue by deigott** [DefectDojo/django-DefectDojo#9479]
I'm trying to run integration test on my environment but something happens to be wrong.

```bash
docker compose --env-file ./docker/environments/postgres-redis.env up --no-deps --exit-code-from integration-tests integration-tests
WARN[0000] The "DD_INTEGRATION_TEST_FILENAME" variable is not set. Defaulting to a blank string.
[+] Running 1/0
 ✔ Container django-defectdojo-integration-tests-1  Created                                                                                                                                                0.0s
Attaching to integration-tests-1
integration-tests-1  | wait-for-it.sh: waiting max 30 seconds for postgres:5432
integration-tests-1  | wait-for-it.sh: postgres:5432 is available after 0 seconds
integration-tests-1  | Testing DefectDojo Service
integration-tests-1  | Waiting max 60s for services to start
integration-tests-1  | Succesfully displayed login page, starting integration tests
integration-tests-1  | IT FILENAME:
integration-tests-1  | Running: Finding integration tests
integration-tests-1  | setUpClass (base_test_class.BaseTestCase) ... ERROR
integration-tests-1  |
integration-tests-1  | ======================================================================
integration-tests-1  | ERROR: setUpClass (base_test_class.BaseTestCase)
integration-tests-1  | ----------------------------------------------------------------------
integration-tests-1  | Traceback (most recent call last):
integration-tests-1  |   File "/app/tests/base_test_class.py", line 93, in setUpClass
integration-tests-1  |     dd_driver = webdriver.Chrome(
integration-tests-1  |                 ^^^^^^^^^^^^^^^^^
integration-tests-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
integration-tests-1  |     super().__init__(
integration-tests-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
integration-tests-1  |     self.service.start()
integration-tests-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 100, in start
integration-tests-1  |     self.assert_process_still_running()
integration-tests-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 113, in assert_process_still_running
integration-tests-1  |     raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
integration-tests-1  | selenium.common.exceptions.WebDriverException: Message: Service /opt/chrome-driver/chromedriver unexpectedly exited. Status code was: -5
integration-tests-1  |
integration-tests-1  |
integration-tests-1  | ----------------------------------------------------------------------
integration-tests-1  | Ran 0 tests in 0.522s
integration-tests-1  |
integration-tests-1  | FAILED (errors=1)
integration-tests-1  | launching browser for:  BaseTestCase
integration-tests-1  | starting chromedriver with options:  {'_caps': {'browserName': 'chrome', 'pageLoadStrategy': 'normal', 'acceptInsecureCerts': True}, 'mobile_options': None, '_arguments': ['--headless', '--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--window-size=1280,1024'], '_ignore_local_proxy': False, '_binary_location': '', '_extension_files': [], '_extensions': [], '_experimental_options': {'prefs': {'download.default_directory': '/app'}}, '_debugger_address': None} {'browserName': 'chrome', 'goog:loggingPrefs': {'browser': 'ALL'}}
integration-tests-1  | tearDownDriver:  BaseTestCase
integration-tests-1  | Error: Finding integration tests test failed
integration-tests-1 exited with code 1
```

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Comment by kiblik** [comment]
I'm facing a similar issue.
I have some feeling that if the following lines are fixed
https://github.com/DefectDojo/django-DefectDojo/blob/305146681c43b2d5718f50c62600760a691db1da/tests/base_test_class.py#L94-L99
this error also disappears.

@manuel-sommer, you were pointing to https://github.com/DefectDojo/django-DefectDojo/pull/9136#issuecomment-1964529904. But I suppose the mentioned lines will be the reason for failing.
If you have the capacity to look at it, it might be beneficial.

**Comment by manuel-sommer** [comment]
I was able to reproduce this also, but had not enough time to debug it.

**Comment by valentijnscholten** [comment]
@manuel-sommer @deigott Is this still happening? "It works on my machine(tm)"
