### ISSUE TITLE
I'm frequently getting this below error. Is the Azure ad integration with Defect Dojo causing this issue?

### ISSUE THREAD

**Issue by naveen2131-hue** [DefectDojo/django-DefectDojo#9685]
**I'm frequently getting this below error. Is the Azure ad integration with Defect Dojo causing this issue?**

ERROR [django.security.DisallowedHost:125] Invalid HTTP_HOST header: '100.x.x.xxx:80'. You may need to add '100.xx.xx' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)

 DD_ALLOWED_HOSTS: 'zzz.xyzz.com , defectdojo.default.local,localhost'

@Gby56 @dougmorato @Juu @olafz @gnustavo

**Comment by manuel-sommer** [comment]
@naveen2131-hue did you ask in the slack channel?

I guess this is rather a support case @mtesauro
