### ISSUE TITLE
Migration error key too long

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#969]
### Issue Type 
- [X] Bug

### Description
Exception during migration script ($ ./manage.py migrate). The other 2 migrations ran fine.

### Operating System 
Debian Stretch (9)

### Install

- [X] setup.bash

### DefectDojo Version
dev branch @ 46692a0f7bf568f5739d093ab0e4d2ef6733faf6

### Steps to Reproduce
install defectdojo dev branch from 8 december 2018, perform git pull, run migration:
$ ./manage.py migrate

### Console Logs (optional)
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, custom_field, dojo, sessions, sites, tagging, tastypie, watson
Running migrations:
  Applying dojo.0002_auto_20190322_1427...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 221, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 531, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 706, in _alter_field
    params,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

**Comment by aaronweaver** [comment]
We fixed this in a later release, I think within the last couple months by limiting the length on product.

**Comment by valentijnscholten** [comment]
So how do I fix it? This happened on the latest commit 46692a0 on dev branch.

**Comment by aaronweaver** [comment]
I wonder if you have a longer product name? Looking in the error messages I don't see any indication of the field.

**Comment by valentijnscholten** [comment]
Longest productname is 38 characters

**Comment by valentijnscholten** [comment]
Is there any logging I can add some place to help debugging this? I am new to python, django and DD :)

**Comment by aaronweaver** [comment]
Is this a fresh install? I remember sometimes innodb has to be changed or check out the docker.

SET GLOBAL innodb_file_format=Barracuda;
SET GLOBAL innodb_file_per_table=ON;
ROW_FORMAT=DYNAMIC; -- or COMPRESSED (goes on end of CREATE)
innodb_large_prefix=1

**Comment by valentijnscholten** [comment]
The DB is not new, I just finished setting up 20-ish products, engagements and configured their IDs in Jenkins jobs.

**Comment by valentijnscholten** [comment]
This is the generated migration script:

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='hash_code',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]

Probably choking on the product_type migration. However all my product types have very short names:

MariaDB [DojoDB]> select * from dojo_product_type;
+----+--------------------------+------------------+-------------+----------------------------+----------------------------+
| id | name                     | critical_product | key_product | updated                    | created                    |
+----+--------------------------+------------------+-------------+----------------------------+----------------------------+
|  1 | Research and Development |                0 |           0 | NULL                       | NULL                       |
|  2 | Front-end                |                0 |           0 | 2019-03-15 12:44:49.326292 | 2019-03-15 12:44:49.326320 |
|  3 | BNP Cards                |                0 |           0 | 2019-03-15 12:47:29.893353 | 2019-03-15 12:47:29.893397 |
|  4 | BNP Corporate            |                0 |           0 | 2019-03-22 09:51:51.221466 | 2019-03-22 09:51:51.221505 |
|  5 | BNP YourPlan             |                0 |           0 | 2019-03-22 09:53:27.540248 | 2019-03-22 09:53:17.404001 |
+----+--------------------------+------------------+-------------+----------------------------+----------------------------+
5 rows in set (0.00 sec)

**Comment by valentijnscholten** [comment]
For an existing db it's hard to change your suggested settings:

```
MariaDB [DojoDB]> ALTER TABLE `dojo_product_type` ROW_FORMAT=DYNAMIC;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

I would suggest to make the max length of the product_type equal to 191 to avoid this problem alltogether.

**Comment by valentijnscholten** [comment]
Reopening to see if my suggestion would be OK so I can make a PR. There are multiple Linux distro's that by default will run into the same error because the key can only be 767 / 4 = 191 characters.
Currently it's 255 but I think it would be rare for people to have a product type name > 191 characters?
