### ISSUE TITLE
A string literal cannot contain NUL (0x00) characters - Anchore Grype

### ISSUE THREAD

**Issue by corvusmod** [DefectDojo/django-DefectDojo#9942]
**Bug description**
While import Anchore Grype scan result I got some error 
A string literal cannot contain NUL (0x00) characters., Maybe it's about the value in json report file.

Similar to: https://github.com/DefectDojo/django-DefectDojo/issues/9939

**Steps to reproduce**
Imported an error with dd-importer

**Expected behavior**
No error importing Anchore Grype reports

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.27.4

**Logs** 

`
[pid: 1|app: -|req: -/-] 10.20.21.225 (-) {50 vars in 835 bytes} [Wed Apr 17 12:35:14 2024] GET //api/v2/tests/?title=Anchore+Grype&engagement=2209 => generated 607 bytes in 39 msecs (HTTP/1.1 200) 8 headers in 246 bytes (1 switches on core 0)
[17/Apr/2024 12:35:14] ERROR [dojo.api_v2.exception_handler:36] A string literal cannot contain NUL (0x00) characters.
Traceback (most recent call last):
  File "/app/dojo/api_v2/serializers.py", line 2502, in save
    ) = reimporter.reimport_scan(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 682, in reimport_scan
    ) = self.process_parsed_findings(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/decorators.py", line 48, in __wrapper__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 332, in process_parsed_findings
    item.save(dedupe_option=False)
  File "/app/dojo/models.py", line 2915, in save
    self = apply_cwe_to_template(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/utils.py", line 1698, in apply_cwe_to_template
    cwe=finding.cwe, title__icontains=finding.title, template_match=True).first()
                                                                          ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1047, in first
    for obj in (self if self.ordered else self.order_by("pk"))[:1]:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
`

**Comment by manuel-sommer** [comment]
Do you have a sample file @corvusmod ? Then, I can submit a bugfix.

**Comment by manuel-sommer** [comment]
See PR @corvusmod

**Comment by manuel-sommer** [comment]
This is resolved and can be closed.
